### ISSUE TITLE
Hover on the bars only, not on the area between two bars.

### ISSUE THREAD

**Issue by ng2695** [recharts/recharts#3698] opened 2023-08-11 19:52 UTC
Is it possible to show the tooltip only on MouseOver of the bar, and not the gap between bars?

Here In the image, bar - **Page E** has the gray background when hover on bar and surrounding areas.
I want to hover on only the bar and not the surrounding area.
![image](https://github.com/recharts/recharts/assets/44426015/eb02311a-6bfa-4d09-88c6-4be9b29ec607)

**Comment by ckifer** [comment] 2023-08-11 21:05
Please see this codesandbox for how its possible though its not currently a feature
https://codesandbox.io/s/recharts-custom-tooltip-forked-huz2ub?file=/src/ExampleChart.jsx:1596-1607

duplicate of https://github.com/recharts/recharts/issues/3388
https://github.com/recharts/recharts/issues/2744

**Comment by ckifer** [comment] 2023-08-11 21:06
Going to close this in preference to https://github.com/recharts/recharts/issues/3388, feel free to comment back here though as I'll see it and respond

**Closed by ckifer** 2023-08-11 21:06 UTC

**Comment by ng2695** [comment] 2023-08-11 21:59
yeah, I'm trying something similar, I'm rendering the rechart's tooltip based on state, which is updating in event **onMouseEnter**.

However, since it's rendering it too many times, I'll try this way as well.

Thanks! It would be really nice to add this a feature though ! :)

**Comment by ckifer** [comment] 2023-08-11 22:04
Yep, agreed. Unfortunately it can't be a priority right now due to lack of contributors/time. Will continue to track in the other issue
