### ISSUE TITLE
Recharts 2.1.14: Typing error at DefaultTooltipContent.tsx:83. value and name could be undefined while it is not expected.

### ISSUE THREAD

**Issue by gabgagnon** [recharts/recharts#2999] opened 2022-10-07 17:21 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/recharts/recharts](https://github.com/recharts/recharts)

### Steps to reproduce
- Install Recharts lib in a typescript project.
- Use Tooltip from Recharts.
- See the typing error.
- Open src/component/DefaultTooltipContent.tsx in an IDE
- See the typing error at DefaultTooltipContent.tsx:83 for value & name variables

### What is expected?
The variables Value and Name should never be undefined at this state, but typescript seems to think it can still happen and create an error.

### What is actually happening?
For the value variable
Argument of type 'TValue | undefined' is not assignable to parameter of type 'TValue'.
'TValue' could be instantiated with an arbitrary type which could be unrelated to 'TValue | undefined'.ts(2345)

For the name variable
Argument of type 'TName | undefined' is not assignable to parameter of type 'TName'.
'TName' could be instantiated with an arbitrary type which could be unrelated to 'TName | undefined'.

| Environment | Info |
|---|---|
| Recharts | v2.1.14 |
| React | 18.2.0 |
| System | macOS Monterey |
| Browser | Chrome |

---
https://github.com/recharts/recharts/issues/2945

This file got recently updated in this PR: https://github.com/recharts/recharts/commit/da6b9e2394cd55169ecdf31baf51bfa021eedb18

**Comment by puerschel93** [comment] 2022-12-22 05:45
Is it already fixed ? I faced the same issue but after installing `recharts@latest` the error was gone.

**Comment by ckifer** [comment] 2022-12-29 07:23
This part of the issue seems resolved though #3008 is still open. @gabgagnon Can you confirm that the latest allows you to use a tooltip without this specific error? I can't reproduce even with 2.1.14. Will close this once confirmed

**Comment by ckifer** [comment] 2023-09-17 06:19
This is fixed, closing

**Closed by ckifer** 2023-09-17 06:19 UTC
Labels: typescript
