### ISSUE TITLE
Help!, how to create horizontal scrollable realtime chart

### ISSUE THREAD

**Issue by AmalRichwin** [recharts/recharts#2679] opened 2021-10-07 08:14 UTC
Hello, i need to create a horizontal scrollable areachart, 

for me what is happening 

1. is the data gets crumbled together and brush component is also not moving.it stays fixed. 
2. I have set the startIndex and endIndex on brush component.

Thankyou

Code:

```const [time, setTime] = React.useState('');
  const [arr, setArr] = React.useState([
    { X: 0 },
    { X: 0 },
    { X: 0 },
    { X: 5 },
    { X: 5 },
    { X: 5 },
  ]);

  const timeoutRef = React.useRef(null);

  const validate = React.useCallback(() => {
    setArr((prevState) =>
      [...prevState, { X: Math.random() >= 0.5 ? 5 : 0 }].slice(1)
    );
  }, []);

  React.useEffect(() => {
    if (timeoutRef.current !== null) {
      clearTimeout(timeoutRef.current);
    }
    const interval = 6000;
    const speed = 1000;
    for (let i = 0; i < interval; i++) {
      timeoutRef.current = setTimeout(() => {
        timeoutRef.current = null;
        validate();
      }, i * speed);
    }
  }, [validate]);
  return (
    <div>
      <h1>{time}</h1>
      <AreaChart
        width={730}
        height={250}
        data={arr}
        margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
      >
        {/* <CartesianGrid strokeDasharray='3 3' /> */}

        <YAxis />
        <XAxis additive='sum' />
        <Tooltip />
        <Legend />
        <Area
          type='monotone'
          dataKey='X'
          stroke='#8884d8'
          isAnimationActive={false}
          additive='sum'
        />
        <Brush startIndex={0} endIndex={10}>
          <AreaChart>
            <Area dataKey='X' isAnimationActive={false} />
          </AreaChart>
        </Brush>
      </AreaChart>
    </div>
  );
```

**Comment by jarodsim** [comment] 2021-11-17 14:01
Same issue

**Comment by thareshjose** [comment] 2022-08-22 17:02
The chart add a feature that enables it have a sticky Y-axis and a proper scrollable x-axis (without using the current brush implementation).

**Comment by valentine-dev** [comment] 2022-12-13 20:19
Is this feature added yet?

**Comment by ckifer** [comment] 2022-12-13 20:49
hey @valentine-dev I don't think anyone has touched this in a while - recharts hasn't had anyone working on it in a bit, but we're trying to find contributors and get things moving again. Feel free to make a PR if you feel you could create a fix/enhancement for it. For now, we're focusing on making it easier for people to contribute. Added some labels so this doesn't get lost

**Comment by gouthamsk98** [comment] 2023-02-18 08:11
I think I can help u with this, I also faced a similar situation,
use Brush Components from rechart, pass the **startIndex** props as  "**dataKey array length - no unit u want to display in x-axis**" i.e <Brush startIndex={arr.length-10} >
given below is the newly edited code.

        <YAxis />
        <XAxis additive='sum' />
        <Tooltip />
        <Legend />
        <Area
          type='monotone'
          dataKey='X'
          stroke='#8884d8'
          isAnimationActive={false}
          additive='sum'
        />
        <Brush startIndex={arr.length-10} >
          <AreaChart>
            <Area dataKey='X' isAnimationActive={false} />
          </AreaChart>
        </Brush>
      </AreaChart>
    </div>

**Comment by bloodteller123** [comment] 2023-06-23 21:22
> I think I can help u with this, I also faced a similar situation, use Brush Components from rechart, pass the **startIndex** props as "**dataKey array length - no unit u want to display in x-axis**" i.e given below is the newly edited code.
> 
> ```
>     <YAxis />
>     <XAxis additive='sum' />
>     <Tooltip />
>     <Legend />
>     <Area
>       type='monotone'
>       dataKey='X'
>       stroke='#8884d8'
>       isAnimationActive={false}
>       additive='sum'
>     />
>     <Brush startIndex={arr.length-10} >
>       <AreaChart>
>         <Area dataKey='X' isAnimationActive={false} />
>       </AreaChart>
>     </Brush>
>   </AreaChart>
> </div>
> ```

very smart!

**Comment by mustafa-alfar** [comment] 2024-06-05 12:02
The solution I found is setting the width of ResponsiveContainer according to your data length  and setting its overflow-x:  scroll
here's an example 
`
    <ResponsiveContainer
          width={calculateBarchartWidth(
            data.length
          )}
          height={300}
          className="overflow-x-scroll">
          Your inner JSX goes here ...
    </ResponsiveContainer>
`
I'm using Tailwind, you can use whatever you like 
and here's the method of calculateBarchartWidth
`
const calculateBarchartWidth = (numberOfItem = 9) => {
  if (numberOfItem > 9) return numberOfItem * 100;
  return '100%';
};
`

**Comment by ckifer** [comment] 2024-07-16 00:08
closing this as a duplicate of https://github.com/recharts/recharts/issues/1364

**Closed by ckifer** 2024-07-16 00:08 UTC
Labels: bug, enhancement, P1
