### ISSUE TITLE
Two extra lines are generated in CartesianGrid for dataMin and dataMax and there seems to be no way to hide it

### ISSUE THREAD

**Issue by gaurav5430** [recharts/recharts#2153] opened 2020-05-28 19:42 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/w53z90qa/](https://jsfiddle.net/w53z90qa/)

### Steps to reproduce
If the domain of YAxis is set to `['dataMin', 'dataMax']` and `scale="linear"`, then there is no guarantee to always have a tick at the min and max of the yaxis, but the Grid lines are still drawn for these values. There should be a way to only draw grid lines wherever y axis ticks are shown.

Is there any customization allowed in how grid lines are calculated/shown ?

### What is expected?
There is a way to hide/show particular grid lines, or at least the grid lines can be based on the ticks, or a boolean prop to say whether or not to show grid lines at dataMin, dataMax.

### What is actually happening?
The grid lines are appearing at start and end of the domain and there is no way to hide them

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 16 |
| System | MacOS |
| Browser | Chrome |

**Comment by Opty1712** [comment] 2021-12-30 10:25
@gaurav5430 Have you found the fix? I faced the same problem

**Comment by gaurav5430** [comment] 2022-01-02 16:56
No, i don't think i did. And i stopped working on this so didn't explore further

**Comment by ckifer** [comment] 2022-12-30 21:10
There is currently no way to specify how many grid lines are in a cartesian grid or if they are rendered on the edges or now.

Here is a working CodeSandbox
https://codesandbox.io/s/simple-line-chart-forked-looz8n?file=/src/App.tsx

This will need to be an enhancement to make CartesianGrid more configurable

**Comment by morozovkirill** [comment] 2023-09-02 07:46
There is a function in src/util/ChartUtils.ts - getCoordinatesOfGrid. It adds min and max values to ticks array for grid. I think it should be an option.

/**
 * Calculate the Coordinates of grid
 * @param  {Array} ticks The ticks in axis
 * @param {Number} min   The minimun value of axis
 * @param {Number} max   The maximun value of axis
 * @return {Array}       Coordinates
 */
export const getCoordinatesOfGrid = (ticks: Array<TickItem>, min: number, max: number) => {
  let hasMin, hasMax;

  const values = ticks.map(entry => {
    if (entry.coordinate === min) {
      hasMin = true;
    }
    if (entry.coordinate === max) {
      hasMax = true;
    }

    return entry.coordinate;
  });

  if (!hasMin) {
    values.push(min);
  }
  if (!hasMax) {
    values.push(max);
  }

  return values;
};

It is called from src/chart/generateCategoricalChart.tsx

    verticalCoordinatesGenerator = ({ xAxis, width, height, offset }: ChartCoordinate) =>
      getCoordinatesOfGrid(
        getTicks({
          ...CartesianAxis.defaultProps,
          ...xAxis,
          ticks: getTicksOfAxis(xAxis, true),
          viewBox: { x: 0, y: 0, width, height },
        }),
        offset.left,
        offset.left + offset.width,
      );

I think it must be an option. So, only thing we should do, is to add flag or something like this.

**Comment by nikolasrieble** [comment] 2023-09-02 10:06
This sounds like a reasonable feature request. @morozovkirill Would you consider to contribute to recharts to get rid of your hackaround? A solution in recharts could even be simpler. 

What could the API look like?

**Comment by morozovkirill** [comment] 2023-09-03 11:37
@nikolasrieble I'm not sure, but I can try. I haven't ever committed to libraries.

I guess there should be an option in CartesianGrid component. For instance - syncWithTicks (false at default). I think we shouldn't change default behaviour. But, if it's value will set to true, getCoordinatesOfGrid must return array of ticks coordinates without extra max and min values.

**Comment by nikolasrieble** [comment] 2023-09-03 12:33
That sounds like a great proposal, and it would not be breaking, thus could be released directly without a major release. I think you have already figured out the problem, the solution is just one step away. Let me know if I can help anyhow.

**Comment by khajimatov** [comment] 2023-09-07 11:38
can confirm that disabling `getCoordinatesOfGrid` function does remove those extra lines.
As @nikolasrieble pointed out @morozovkirill's proposal would not be breaking, and it would be great to release this solution as soon as possible, @morozovkirill is there any started/ongoing process to address this issue?

The API might look like this
```jsx
<YAxis
    gridlines="syncWithTicks"
/>

**Comment by morozovkirill** [comment] 2023-09-07 11:58
@khajimatov i’ve forked to add/edit some code, but cannot install all node modules because of outdated macOS. Now I’m trying to update it, but not sure, if everything will be ok. So, if anyone can do it, feel free to realise this feature.

**Comment by morozovkirill** [comment] 2023-09-08 12:29
> That sounds like a great proposal, and it would not be breaking, thus could be released directly without a major release.
> 
> We could also have an API such as: `type gridlines = undefined | 'syncWithTicks' | number[]` Where the default is `undefined` which behaves as you describes. Alternatively, one can pass an array of numbers for which the gridlines will be drawn. It would allow further customisation and include your case as well.
> 
> I think you have already figured out the problem, the solution is just one step away. Let me know if I can help anyhow.

@nikolasrieble I'm not sure about 'number[]' because in this case we should provide two arrays - for both axes. But it's a good idea, anyway. I'll try to implement.

I hope this weekend I'll make a pr.

**Comment by ckifer** [comment] 2023-10-15 06:43
Should be solved by the customization allowed by `syncWithTicks` in 2.9.0, resolving! Thanks @morozovkirill

**Closed by ckifer** 2023-10-15 06:43 UTC
Labels: enhancement, feature request, P2

**Comment by nik-webdevelop** [comment] 2023-12-26 10:40
@ckifer it looks like this property is missing from the CartesianGrid [docs](https://recharts.org/en-US/api/CartesianGrid) page

**Comment by ckifer** [comment] 2023-12-26 15:47
@nik-webdevelop feel free to open a PR to add it. The property should be in the storybook

**Comment by abdullahkaraman** [comment] 2024-07-17 14:33
I couldn't use syncWithTicks in version 2.12.7 @ckifer

**Comment by ckifer** [comment] 2024-07-17 14:35
Can you explain more or provide a reproduction?

**Comment by ckifer** [comment] 2024-07-17 15:03
No worries, thanks!

**Comment by vajajak** [comment] 2025-07-27 22:17
Perhaps this should be added to the docs? I just spent some time looking this up and there is no mention in the docs whatsoever, so I was quite surprised to stumble upon this prop here on GH

**Comment by ckifer** [comment] 2025-07-27 22:42
It should be in the storybook but we can add it to the website too
