### ISSUE TITLE
Problems when trying to print a chart

### ISSUE THREAD

**Issue by pedromdantunes** [recharts/recharts#2746] opened 2021-12-23 10:42 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gyazo.com/87101936af01f67575c3096bdba12536](https://gyazo.com/87101936af01f67575c3096bdba12536)

### Steps to reproduce
```
<div style={{ width: '100%', height: 400, marginTop: 80, border: '1px solid red' }}>
    <ResponsiveContainer>
        <BarChart width={10} height={10} data={data}>
            <CartesianGrid vertical={false} />
            <YAxis
                tickMargin={16}
                tickCount={8}
                axisLine={false}
                tickLine={false}
                interval={0}
            />
            <Tooltip content={<TooltipChart />} />
            <Bar dataKey="value" isAnimationActive={!isExport}>
                {data.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={getColor( entry.key)} />
                ))}
            </Bar>
        </BarChart>
    </ResponsiveContainer>
</div>
```

### What is expected?
Chart fit with its parent

### What is actually happening?
Chart overwride parent div width

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | react@^17.0.1 |
| System | Windows 10 |
| Browser | Chrome 96.0.4664.110 |

**Comment by gsteja2307** [comment] 2021-12-31 18:37
can you provide the code sample ? where this bug is reproducible ?

**Comment by gsteja2307** [comment] 2021-12-31 19:40
could you provide a working example in codesandbox ?

**Comment by kevincastell-np** [comment] 2023-04-21 23:07
[Issue #1114 ](https://github.com/recharts/recharts/issues/1114) that closed is addressing this same issue. It is still not resolved. 

The solution in the linked issue does not seem to work when using the inline `width` prop on the responsive container.

**Comment by ckifer** [comment] 2023-04-21 23:34
I re-opened #1114 because it has more info, lets prefer to discuss this there. 

IMO we'd need a print API trigger of sorts similar to highcharts where the consumer would need to call `chartRef.print()` in order to get something correct

Closing this one, can use the older issue

**Closed by ckifer** 2023-04-21 23:34 UTC
