### ISSUE TITLE
Tooltip rendering crashes when resizing the chart "Cannot read properties of undefined (reading 'payload')"

### ISSUE THREAD

**Issue by tran-simon** [recharts/recharts#3981] opened 2023-11-20 16:25 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-voice-tgydrx?file=/src/App.js)

### Steps to reproduce
1. Hover the chart to show the tooltip
2. Press the button
3. Resize the window (to show/hide the scrollbar)
4. Repeat 3 times

The app crashes sometimes with "Cannot read properties of undefined (reading 'payload')" when the window is resized.

The crash is not consistent, so you should reload and try multiple times to reproduce

### What is expected?
The tooltip should appear correctly

### What is actually happening?
The whole app crashes (null pointer exception)

| Environment | Info |
|---|---|
| Recharts | v2.10.1 |
| React | 18.2.0 |
| System | codesandbox |
| Browser | Chrome |

---
This is due to a mistake in `getItemByXY` in `generateCategoricalChart.tsx`. 
https://github.com/recharts/recharts/blob/0d5326a8cdcad34a3b9d7c0644abbb645ddffe87/src/chart/generateCategoricalChart.tsx#L2250-L2252

https://github.com/recharts/recharts/blob/7fb227dae542c3d3093506e6d80a2c2c366f9a26/src/util/ActiveShapeUtils.tsx#L142-L152

`isFunnel`, `isPie` and `isScatter` do not check if `activeItem` is defined, so it might cast it as a defined `FunnelItem`/`PieItem`/`ScatterItem` even if `activeItem` is undefined

**Comment by ckifer** [comment] 2023-11-20 17:42
Thanks for the fix. I can't reproduce at all, I wonder why its so random

**Comment by tran-simon** [comment] 2023-11-20 18:11
@ckifer yeah it's really hard to reproduce, I'll keep looking for a way to reproduce it consistently

But I still think that part of the code is smelly, `activeItem` is typed as optional but the `isFunnel`/`is...` functions cast it as defined without checking if it actually is

**Comment by ckifer** [comment] 2023-11-20 18:46
makes sense

**Comment by ckifer** [comment] 2023-11-29 04:53
fixed merged and released in 2.10.2 - please comment back if this persists

**Closed by ckifer** 2023-11-29 04:53 UTC
