### ISSUE TITLE
Better documentation of tooltips

### ISSUE THREAD

**Issue by paddymul** [recharts/recharts#5181] opened 2024-10-30 14:02 UTC
## Do you want to request a feature or report a bug?

I'm requesting better documentation.  ReCharts might currently be capable of doing what I want, but that is not clear.
## What is the current behavior?
There is only a single tooltip example in the docs. https://recharts.org/en-US/examples/CustomContentOfTooltip

Here is the code for the tooltip element
https://github.com/recharts/recharts/blob/a2a780a543c3a0e7fc97d23b308fd4f32f5323f1/src/component/Tooltip.tsx#L245-L267

The type has a little more documentation
https://github.com/recharts/recharts/blob/a2a780a543c3a0e7fc97d23b308fd4f32f5323f1/src/component/Tooltip.tsx#L59-L102

## What is the expected behavior?
Ideally I would like to see documentation and examples of different tooltype configs.  In particular I need to to use createPortal somehow.  Explaining places when you would want to use createPortal would be helpful.  

In my case I'm embedding a rechart into a custom ag-grid element.  I'm fairly sure I need to use createPortal, because the tooltip is completely clipped.

Examples showing a custom `content` element would also be helpful

**Comment by ckifer** [comment] 2024-10-30 14:13
https://release--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-tooltip--custom-content-example


https://github.com/recharts/recharts/blob/3.x/storybook/stories/Examples/Tooltip.stories.tsx#L215

**Comment by ckifer** [comment] 2024-10-30 14:34
But also you cannot use Tooltip portals with the current release. It will be released in 3.0.

**Comment by ckifer** [comment] 2024-10-30 14:37
You could try using `allowEscapeViewbox` so the Toolip can render outside of the svg

**Comment by paddymul** [comment] 2024-10-30 14:43
Ahh good to know about the storybook examples.  

I had copied half of Tooltip.tsx in my repo to get portals working.  And I believe it had worked previously, but on upgrade of AG-Grid it stopped working.

For createPortal, what I would really like is an example that creates a portal off of `document.body` and absolutely positions it on top of the bar in the chart.

AG-Grid embeds elements in a div with `overflow:hidden` set.  So the tooltip is clipped.

I'll start looking at the 3.0 branch

**Comment by ckifer** [comment] 2024-10-30 14:49
I don't think you'll be able to replicate what we're doing for portals in your code without changes to recharts. 

There should be an example in the file I linked you of using Tooltip portals. You would add a ref to your target element, position that target element wherever you want it to be, and then pass that ref to the tooltip element and it will render the content into the target. 

Not too sure what you mean by using document.body

**Comment by ckifer** [comment] 2024-10-30 14:51
This is the 3.x storybook portal example
https://63da8268a0da9970db6992aa-mfnsnugdsk.chromatic.com/?path=/story/examples-tooltip--tooltip-with-portal

Code ref https://github.com/recharts/recharts/blob/3.x/storybook/stories/Examples/Tooltip.stories.tsx#L374-L399

**Comment by paddymul** [comment] 2024-10-30 14:58
Trying to keep up here.  Thanks for actively engaging with my request ! 

> You could try using allowEscapeViewbox so the Toolip can render outside of the svg
`allowEscapeViewBox` doesn't work for my usecase.

I will try to come up with a small limited reproducible example of recharts embedded into AG-Grid in codepen for demonstration.

Thanks for the updated link.  I had a bit of trouble finding the -with-portal example

**Comment by ckifer** [comment] 2024-10-30 15:01
No worries :D

Sounds good!

And... yeah while there are two active branches its hard to keep things straight. That example only exists in the 3.x branch (which is currently the default branch) and is unreleased. master is current released 2.x and does not have anything related to portal in its storybook or in its code.

The first storybook link is 2.x which is what I usually share since 3.0 features are not out yet. Sorry for the confusion.

**Comment by paddymul** [comment] 2024-10-30 15:09
for now I'm most curious if I should build off of the 3.0 branch.

There are other features I can work on for Buckaroo instead of this.  So this isn't necessarily a blocker for me.

**Comment by ckifer** [comment] 2024-10-30 15:15
I mean its stable...ish in its current state especially for those charts and especially if you didn't update anything until release (we're making breaking changes all the time).

But we're not even to a point where I would consider releasing an alpha version yet so I would personally say don't depend on it until we're at least to that point. Estimates are hard because this is a spare-time project for me and one other at the moment. So it could be a month, it could be 6.

If you can get it working any other way besides using 3.0 I'd do first as a temp workaround and adjust later.

**Comment by ckifer** [comment] 2024-10-30 15:37
Oh also if you want to throw together  codesandbox which uses ag grid and recharts without buckaroo and reproduce the issue as simply as possible (bar chart inside grid with tooltip) then I'm totally willing to try to help find something that will work in the mean time.

**Comment by paddymul** [comment] 2024-10-30 18:56
Here is a minimally reproducible example.  This uses ag-grid 32.3.2 and recharts 2.13.2

https://codesandbox.io/p/sandbox/4gml9g

Play with the rowHeight setting on index.tsx line 81 to see how tooltips are clipped.

For reference, in buckaroo rows are more compact than 50px

**Comment by paddymul** [comment] 2024-10-30 19:22
Bahh. Sorry about that.
https://codesandbox.io/p/sandbox/get-cell-renderer-forked-rkcqw6?workspaceId=5d3c7e6a-4f10-4d63-b56a-6e222ec3935f

Try that.  I checked it in a private browser window

**Comment by ckifer** [comment] 2024-10-30 19:23
Good now, thanks

**Comment by ckifer** [comment] 2024-10-30 19:33
![image](https://github.com/user-attachments/assets/ba22d66f-f22a-4df3-a218-7d281617c2a8)
For the item outside of the grid (gotta start somewhere) I added
```
 <Tooltip
       allowEscapeViewBox={{ x: true, y: true }}
       wrapperStyle={{ zIndex: 9999, color: "#111" }}
  />
```

Seems to be working.

But those styles for the grid, even if I remove `overflow: hidden` still aren't great
![image](https://github.com/user-attachments/assets/ed90273b-4b14-4880-b8e3-f0aa71e174ba)

**Comment by ckifer** [comment] 2024-10-30 20:16
I think I have something that will work. I will post it as soon as I can get it together

**Comment by ckifer** [comment] 2024-10-30 22:28
Here we go
https://codesandbox.io/p/sandbox/get-cell-renderer-forked-rkcqw6

<img width="421" alt="image" src="https://github.com/user-attachments/assets/7683a77a-2dfc-439d-892d-44ccc8b64a29">

**Comment by ckifer** [comment] 2024-10-30 22:31
```jsx
const CustomTooltip = ({ active, payload, label, screenCoords }) => {
  if (active && payload && payload.length && screenCoords) {
    return createPortal(
      <div
        style={{
          backgroundColor: "#eee",
          padding: "5px 10px 5px 10px",
          color: "#111",
          position: "absolute",
          top: screenCoords.y + 10,
          left: screenCoords.x + 10,
        }}
      >
        <p className="label">{`${label} : ${payload[0].value}`}</p>
      </div>,
      document.body
    );
  }

  return null;
};
```

Custom tooltip content rendered as a portal to `document.body`.

Absolutely positioned with the current `clientX` `clientY` coordinates from the `onMouseMove` event of `BarChart`

**Comment by paddymul** [comment] 2024-10-30 22:50
Thank you soo much.

BTW your link didn't work.  This one should
https://codesandbox.io/p/sandbox/get-cell-renderer-forked-wxmdx7?workspaceId=5d3c7e6a-4f10-4d63-b56a-6e222ec3935f

**Comment by ckifer** [comment] 2024-10-30 22:54
Oops, fixed my link. But yep looks like yours is working the same.

> Thank you soo much.

Np, glad there was something that worked in lieu of 3.0. When that is released this should be an easy port.

**Comment by ckifer** [comment] 2024-11-08 07:11
Going to close this as 3.0 should include what is needed here - docs and otherwise

**Closed by ckifer** 2024-11-08 07:11 UTC
Labels: docs needed, Tooltip, 3.0
