### ISSUE TITLE
Recharts Responsive Chart not responsive inside a CSS grid

### ISSUE THREAD

**Issue by rodoabad** [recharts/recharts#1423] opened 2018-08-03 04:02 UTC
## What is the current behavior?

Responsive Charts are do not resize when resizing windows if it's inside a CSS grid.

![example](https://user-images.githubusercontent.com/1240667/43623675-025059ee-96a8-11e8-8139-da0deb03421a.gif)

```css
.home {
  border: 1px solid blue;
  display: grid;

  grid-template-areas:
    'hello'
    'links'
    'main';
 }
```

```css
.charts {
  border: 1px solid green;
  grid-area: main;
}
```

## What is the expected behavior?

It should resize when window is resizing.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

https://github.com/rodoabad/automatic-palm-tree/tree/e557ebf246078c418da0678cba5b43c7abb41357

`"recharts": "^1.1.0"`

**Comment by rodoabad** [comment] 2018-08-07 15:31
A quick solution is to use `99%` width so that `recharts` can calculate the width properly.

**Comment by rodoabad** [comment] 2018-08-08 16:38
Maybe we need to update `react-resize-detector` - https://github.com/maslianok/react-resize-detector/releases since we're still using the old version.

**Comment by DonovanCharpin** [comment] 2018-08-31 17:48
Hi

Same thing with flex. @rodoabad your fix with `99%` seems to work 👍 

``` javascript
<ResponsiveContainer width="99%">
```

**Comment by suddencreator** [comment] 2018-09-23 02:05
The issue I have is that it does not display at all when in a responsive container. I am using bootstrap if anything. I tried different percentages. It wants a defined width in px but it does not display with the width="100%" ot 99%

**Comment by rodoabad** [comment] 2018-09-27 20:11
Any comments from the development team on this one?

**Comment by rodoabad** [comment] 2018-09-27 20:28
@suddencreator `aspect` property?

**Comment by suddencreator** [comment] 2018-09-27 20:30
It automatically resizes well with the page even with mobile breakpoints.

**Comment by rodoabad** [comment] 2018-09-27 20:33
@suddencreator With CSS grids? Can you show me a test repo that I can clone? I'm testing it right now and if it's inside a CSS grid, it's not resizing properly.

It will resize to go big, but it will not resize to go down. See gif I posted.

**Comment by suddencreator** [comment] 2018-09-28 02:30
@rodoabad sorry for the late reply. check the fork i made
https://jsfiddle.net/ishaans/n2tkvwgr/

just resize the page (in JSFiddle) and it stretches accordingly

**Comment by rodoabad** [comment] 2018-09-28 02:55
@suddencreator it looks like we're talking about two different things when I mentioned [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/grid).

Please take a look at this updated fork.

https://jsfiddle.net/ftcqko32/5/

**Comment by suddencreator** [comment] 2018-09-28 03:16
@rodoabad responds with a column width
https://jsfiddle.net/ishaans/ftcqko32/8/

**Comment by suddencreator** [comment] 2018-09-28 03:34
it works in jsfiddle though, the 100%

**Comment by rodoabad** [comment] 2018-09-28 03:34
Another quick edit - https://jsfiddle.net/ftcqko32/25/

I can't get `fr` to be recognized by jsfiddle.

**Comment by suddencreator** [comment] 2018-09-28 04:38
@rodoabad https://jsfiddle.net/ishaans/ftcqko32/30/

i merged the CSS into one class. from `otherGrid` to `otherChildGrid`. it does recognize, if you do a chrome inspect, the grid shows up.
![othergrid](https://user-images.githubusercontent.com/43156366/46188389-d51bb780-c2b6-11e8-8dee-833d08fd73e8.PNG)

**Comment by rodoabad** [comment] 2018-09-28 13:27
I can't fully render JS Fiddle right now because I'm at work but I will test this again later. Were you able to get the graph to resize if you use `1fr` instead of `100%`?

**Comment by suddencreator** [comment] 2018-09-28 15:27
its not rendering anything anymore, i changed so much attempting to debug. probably react changed overnight, its throwing a react error and jsfiddle is complaining about `</LineChart>` closing tag. i checked all the tags

**Comment by rodoabad** [comment] 2018-09-29 13:32
Further investigation while looking at your latest.

At a high level, this is your structure...

```jsx
      <div className="parentGrid"> // not a grid
        <div className="rodoabad"> // grid
          <ResponsiveContainer aspect={1.6}>
          </ResponsiveContainer>
        </div>
        <div className="otherChildGrid">{'Other Grid'}</div> // grid
      </div>
```

`parentGrid` must be a grid.

**Comment by rodoabad** [comment] 2018-09-29 13:48
I got more out of this, this weekend. LOL.

If the parent grid is set to 100%, this works.

https://jsfiddle.net/ftcqko32/38/

```scss
.parentGrid {
  display: grid;
  grid-template-areas:
    'rodoabad'
    'otherGrid';
    grid-template-columns: 100%;
}

.otherChildGrid {
  grid-area: otherGrid
}

.rodoabad {
  grid-area: rodoabad;
}
```

**Comment by rodoabad** [comment] 2018-09-29 13:49
With `fr`, it does not work.

https://jsfiddle.net/ftcqko32/39/

```scss
.parentGrid {
  display: grid;
  grid-template-areas:
    'rodoabad'
    'otherGrid';
    grid-template-columns: 1fr;
}

.otherChildGrid {
  grid-area: otherGrid
}

.rodoabad {
  grid-area: rodoabad;
}
```

**Comment by maslianok** [comment] 2018-10-04 16:11
Hi guys,
`react-resize-detector` author is here.

I've made some experiments described in this issue maslianok/react-resize-detector#47 and I couldn't reproduce the bug. 
Please, try to upgrade to the most recent version 3.1.x. and let me know if the bug won't be fixed.

**Comment by mpbunch** [comment] 2018-10-08 17:55
FYI: Demo does not work (is not responsive).
http://recharts.org/en-US/examples/AreaResponsiveContainer

**Comment by gonzalonaveira** [comment] 2019-01-14 22:04
@rodoabad did you manage to find a solution? I'm facing the same issue, your input was really helpfull.
I'm not working with grid tho, flex box Thanks.

**Comment by yash2code** [comment] 2019-07-20 12:22
> @rodoabad did you manage to find a solution? I'm facing the same issue, your input was really helpfull.
> I'm not working with grid tho, flex box Thanks.

same issue

**Comment by ralphwillgoss** [comment] 2019-10-04 13:29
Adding width 99% when in a grid worked for me
`<ResponsiveContainer width={'99%'} height={300}>`

**Comment by eoghanmccarthy** [comment] 2019-10-04 13:33
@ralphwillgoss Wrapping the chart in a `display: block` div will solve this issue.

**Comment by sznowicki** [comment] 2019-10-05 17:20
I can confirm it happens on grid when `<ResponsiveContainer>` is rendered in a cell with `fr` sizing.

My workaround is to use this kind of approach for now:

`setForceLoading` sets a state that removed whole chart from DOM and replaces it with loading animation. Seems good enough for UX. It's quite a rare edge case anyway.

```
useEffect(() => {
    let resizeThrottleTimeout;
    let skip = false;
    const resizeCb = () => {
      if (skip) {
        return;
      }

      setForceLoading(true);
      skip = true;
      resizeThrottleTimeout = setTimeout(() => {
        setForceLoading(false);
        skip = false;
      }, 100);
    };
    window.addEventListener('resize', resizeCb);

    return () => {
      clearTimeout(resizeThrottleTimeout);
    }
  }, [setForceLoading]);
```

**Comment by iamdevlinph** [comment] 2019-10-28 07:55
The `width="99%"` workaround works but the transition from wide to smaller width is very slow 😅

**Comment by iamdevlinph** [comment] 2019-10-28 09:10
I just used `calc` to get the width. And keep using `width="100%"`, it's much faster than using the 99% workaround.

**Comment by kalbert312** [comment] 2019-10-30 18:16
Not related to CSS grids but if you're using this inside css flexbox, make sure to set `min-width: 0;` on the flex item to allow it to shrink.

**Closed** 2019-12-03 05:58 UTC

**Comment by sznowicki** [comment] 2019-12-03 14:58
@xile611 why this is closed?

**Comment by raymond-ong** [comment] 2020-01-03 04:03
For my case, I am using CSS Grid. My Rechart-PieChart can be positioned beside a multiselect combobox from Semantic UI, or a react-table with Show 10, Show 20, Show 30 rows options.
So these 'neighbour' controls can grow/shrink depending on the user's actions.
The effect of 1 control growing in CSS Grid is that it would also grow the other controls in that row.
-> That's my desired behaviour.

Initially, I ran into issues also with the Pie chart. It grows as the 'neighbour' controls grow, but fails to shrink back when the 'neighbour' controls shrink.

After some trial and error (I still don't have 100% confidence), these workarounds seem to be working (hopefully I don't run into other issues anymore!)

**[1] Add/Overrode the following css class:**
`.recharts-responsive-container {
    position: absolute;
}`

**[2] Just for completeness, this is my pie chart config:**
```
ResponsiveContainer  width="90%" height="90%">
<PieChart margin={{top: 10, right: 20, left: 20, bottom: 10}}>
```
Actually, setting width and/or height to 100% also works for me (after workaround), but I need to increase the margin.

**Comment by kxxoling** [comment] 2020-01-19 04:03
@kalbert312 `min-width: 0` Fixed my problem perfectly!

@xile611 I think this issue is still under discussion, why close it?

**Comment by onichandame** [comment] 2020-04-21 08:46
This issue still persists on the day of writing this comment with the latest version available when using flexbox.

**Comment by bmitchinson** [comment] 2020-04-29 04:40
> I just used `calc` to get the width and set to the parent container. And kept using `width="100%"`, it's much faster than using the 99% workaround.

Could you post a snippet of this? Experiencing the easy + responsive stretch but slow shrink issue.

**Comment by bmitchinson** [comment] 2020-04-29 04:51
@kxxoling Do you experience slow shrink? No due to min-width: 0? Mind sharing a snippet?

**Comment by iamdevlinph** [comment] 2020-04-30 01:52
> > I just used `calc` to get the width and set to the parent container. And kept using `width="100%"`, it's much faster than using the 99% workaround.
> 
> Could you post a snippet of this? Experiencing the easy + responsive stretch but slow shrink issue. @iamdevlinph

```
width: calc(100vw - 200px);
```

The `200px` will control how much the graph will expand/contract.

**Comment by bmitchinson** [comment] 2020-04-30 05:01
Sorry @iamdevlinph , so:
```
<div style={{width: calc(100vw - 200px)}}>
    <ResponsiveContainer width="99%" height={400}>
        <BarChart data={datapoints} margin={{ right: 60, top: 60 }}>
            ...
        </BarChart>
    </ResponsiveContainer>
</div>
```

Is that right? This didn't work for me, still getting slow shrinks in a flexbox + min-width didn't help

**Comment by iamdevlinph** [comment] 2020-04-30 05:31
```
const GraphContainer = styled.div`
  width: 100%;
  transition: all 0.3s ease;

  &.expand-graph {
    width: calc(100vw - 200px);
  }
  &.compress-graph {
    width: calc(100vw - 490px);
  }
`;

<GraphContainer className={showFilterRail ? "compress-graph" : "expand-graph"}>
  <ResponsiveContainer width="100%" height={400}>
    <ScatterChart
      margin={{ top: 50, bottom: 50, left: marginLeft, right: marginRight }}
    />
  </ResponsiveContainer>
</GraphContainer>;

```
It's quick when there's not a lot of data on the graph.

![responsive](https://user-images.githubusercontent.com/19337229/80675191-70ee5480-8ae6-11ea-83a2-4d3c6a21a314.gif)

**Comment by bmitchinson** [comment] 2020-04-30 05:34
thank so much

**Comment by kestutisg** [comment] 2020-07-01 19:53
> @kxxoling Do you experience slow shrink? No due to min-width: 0? Mind sharing a snippet?

Add minWidth="0" to ResponsiveContainer and it should allow to shrink

```
<ResponsiveContainer width="100%" height={400} minWidth="0">
```

**Comment by AndrejGajdos** [comment] 2021-01-12 08:36
This is the reason why I developed PostCSS plugins [PostCSS Grid Reset](https://github.com/AndrejGajdos/postcss-grid-reset) and [PostCSS Flexbox Reset](https://github.com/AndrejGajdos/postcss-flexbox-reset).

**Comment by dimosmera** [comment] 2021-08-23 18:24
The demo here works https://recharts.org/en-US/examples/AreaResponsiveContainer and uses recharts version `2.0.6`.
I am writing this using version `2.1.0` and can confirm the `ResponsiveContainer` does not work well.

Switch to a previous version like `2.0.6` and it will solve these problems.

**Comment by oleksandrtaran** [comment] 2021-08-29 15:10
@dimosmera perfect, finally the resizing works. Thank you so much. I tried all the solutions above and nothing worked.
I used version 2.0.10. I switched back to 2.0.6 and it started working! I tried also the latest available version 2.1.2 and it works too. It looks to me simply like a bug in some versions (I see multiple commits to fix ResponsiveContainer).
For the responsiveness to work, you don't need any magic.
My use case was a div with 100% width and a fixed height block having a ResponsiveContainer without any additional props and a BarChart inside of it.

**Comment by neodmy** [comment] 2021-09-11 21:34
@oleksandrtaran Same here. Switching to `2.0.6` didn't work for me though, but `2.1.2` did. Your combination of div (with width 100% and fixed height) + _standalone_ `ResponsiveContainer` works amazingly. `ResponsiveContainer` `width="100%"` + `aspect` does work too.

**Comment by Emdsh** [comment] 2022-06-14 12:48
Hey, still having an issue with this on `2.1.10`.

That's my code:
```html
<div className="parentGrid">
  <div className="childChart">
    <ResponsiveContainer width="100%" aspect={1.5}>
      <BarChart data={data}>
        <!-- ... -->
      </BarChart>
    </ResponsiveContainer>
  </div>
</div>
```
```css
.parentGrid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  grid-template-areas: "chart chart chart aside";
}

.childChart {
  grid-area: chart;
}
```

I've tried pretty much every solutions in this issue that was `CSS` and/or `HTML`.
I'd like to avoid surcharging my code with extra `JS`, like [the solution with the `useEffect` hook](https://github.com/recharts/recharts/issues/1423#issuecomment-538670179).

Any idea on how I can make it work?

**Comment by lloydjatkinson** [comment] 2023-03-01 12:10
This is still a problem with the latest version.

**Comment by ckifer** [comment] 2023-03-03 15:34
@lloydjatkinson please see this PR with linked older issue https://github.com/recharts/recharts/pull/3391

Using min-width: 0 for your flex children resolves this. Changed that to 0 by default in that merged PR which will be released relatively soon. Keeping this closed
