### ISSUE TITLE
bar chart tooltip doesn't display

### ISSUE THREAD

**Issue by weitunglin** [recharts/recharts#2206] opened 2020-07-21 03:23 UTC
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-bar-chart-tooltip-display-error-39sh6?file=/src/App.js)

### Steps to reproduce
here is the template: [link](https://codesandbox.io/s/recharts-bar-chart-tooltip-display-error-39sh6?file=/src/App.js)
tooltip in the bar chart doesn't display

### What is expected?
tooltip work correctly

### What is actually happening?
tooltip doesn't show up

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 16.13.0 |
| System | mac os catalina 10.15.5  |
| Browser | Chrome 83.0.4103.116 |

**Comment by VladislavKsen** [comment] 2020-12-21 10:08
Duplicate of #2348

**Closed** 2020-12-22 03:39 UTC

**Comment by AnnabellFlem** [comment] 2023-04-19 08:36
Hi there.

@xile611 @dillonreedy I'm still have this issue with **payload=[]** for **Tooltip** when **allowDuplicatedCategory={false}** in **XAxis**.
For **recharts 2.5.0** this issue exists and here is an example of this issue [Rechart issue with payload](https://codesandbox.io/s/recharts-issue-template-forked-nbgm9j?file=/src/index.js:1426-1449).

_**My Environment info**_
```
Recharts v2.5.0
React 17.0.2
```
I'll appreciate any help with this.
Thank you

**Comment by ledfordtj** [comment] 2024-09-19 20:34
> Hi there.
> 
> @xile611 @dillonreedy I'm still have this issue with **payload=[]** for **Tooltip** when **allowDuplicatedCategory={false}** in **XAxis**. For **recharts 2.5.0** this issue exists and here is an example of this issue [Rechart issue with payload](https://codesandbox.io/s/recharts-issue-template-forked-nbgm9j?file=/src/index.js:1426-1449).
> 
> _**My Environment info**_
> 
> ```
> Recharts v2.5.0
> React 17.0.2
> ```
> 
> I'll appreciate any help with this. Thank you

@antsukanova Did you get help with this? You can make a few simple changes for the tooltip to work as expected.

https://codesandbox.io/p/sandbox/recharts-issue-template-forked-lf743l
