### ISSUE TITLE
Not displayed when component is split

### ISSUE THREAD

**Issue by mrskiro** [recharts/recharts#2595] opened 2021-07-15 11:24 UTC
hi.

If you split the contents of ResponsiveContainer into other components, it will not be displayed.
Is there a way to solve this problem?

sandbox
https://codesandbox.io/s/eager-feynman-ff3mx?file=/src/App.tsx

**Comment by monkeyDvrus** [comment] 2021-12-07 19:25
Hey,
I have the same problem.
Did you find a solution?

**Comment by uvarov-frontend** [comment] 2022-09-21 11:00
Duplicate of the discussion: https://github.com/recharts/recharts/issues/412

**Comment by ckifer** [comment] 2024-11-27 01:51
This is on purpose as there is only meant to be one child within responsive container as a part of the recharts api

**Closed by ckifer** 2024-11-27 01:51 UTC
