### ISSUE TITLE
ScatterPlot points render problem with animations

### ISSUE THREAD

**Issue by daalgi** [recharts/recharts#4151] opened 2024-02-06 14:17 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-scatterplot-7v5fww?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsa6bwun0006356j9yunle4f%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsa6bwun0002356j8gh61z6z%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsa6bwun0003356jgtt3uw0f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsa6bwun0005356jlks8d7xt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsa6bwun0002356j8gh61z6z%2522%253A%257B%2522id%2522%253A%2522clsa6bwun0002356j8gh61z6z%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clsa6bwun0005356jlks8d7xt%2522%253A%257B%2522id%2522%253A%2522clsa6bwun0005356jlks8d7xt%2522%252C%2522activeTabId%2522%253A%2522clsa6bwun0004356juj64unbg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsa6bwun0004356juj64unbg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clsa6egu20071356jecb1vk9l%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clsa6bwun0003356jgtt3uw0f%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsa6bwun0003356jgtt3uw0f%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
Click on the button "New Polygon" to update the plot

### What is expected?
Only show the points of the new series.

### What is actually happening?
The new series points are displayed along with the repeated points from the previous series, including some intermediary points resulting from the animation.

| Environment | Info |
|---|---|
| Recharts | v2.11 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Google Chrome Version 121.0.6167.140 (Official Build) (64-bit) |

---
For a scatter plot with animations, when a series of data points contains two points with identical coordinates {x, y}, and the plot is updated, the duplicate point from the previous series is retained in the render of the updated series. However, hovering over reveals the information of a current point.

If the animation duration is zero `animationDuration={0}`, there's no render problem.

**Comment by ckifer** [comment] 2024-02-06 18:37
95% sure this is caused by non-unique keys see https://github.com/recharts/recharts/issues/4060

Should be resolved in next release

**Comment by ckifer** [comment] 2024-02-09 01:07
fixed in 2.12!

**Closed as completed by ckifer** 2024-02-09 01:07 UTC
Labels: bug
