### ISSUE TITLE
LineChart does not render point when there is only a single data point

### ISSUE THREAD

**Issue by adrianmc** [recharts/recharts#149] opened 2016-07-19 12:55 UTC
I am working on a LineChart, and I noticed that there is a bug where the point is not being rendered when there is only one data point. [JS Fiddle Example Here](http://jsfiddle.net/248r5yha/1/)

# Input

Normally, I have this data:

```jsx
data: [
    { varX: 'Mon', varY: 10 },
    { varX: 'Tue', varY: 24 },
    { varX: 'Wed', varY: 34 },
    { varX: 'Thu', varY: 40 },
    { varX: 'Fri', varY: 52 },
    { varX: 'Sat', varY: 62 },
    { varX: 'Sun', varY: 70 },
  ],
```

But with a single point, I will have this data:

```jsx
data: [
    { varX: 'Mon', varY: 10 },
    { varX: 'Tue' },
    { varX: 'Wed' },
    { varX: 'Thu' },
    { varX: 'Fri' },
    { varX: 'Sat' },
    { varX: 'Sun' },
  ],
```

# Potential Cause

After some testing, I believe it is because of [this line](https://github.com/recharts/recharts/blob/master/src/cartesian/Line.js#L238) in `src/cartesian/Line.js`:

```jsx
if (isAnimationActive && !this.state.isAnimationFinished) {
  return null;
}
```

This line is inside the `renderDots()` function, and it seems that `this.state.isAnimationFinished` is causing the function to exit early.

# Temporary Workaround

Since I do not need animation for a single data point, I have put in these two lines to make the point appear:

```
const numData = data.filter(item => item.varY).length;
```

and inside my `<Line>` component:
```
isAnimationActive={numData !== 1}
```

Essentially, I disable animation so the `if` statement returns false and it does not go into that code block.

# Live Example of Bug

I've made a JSFiddle to demonstrate the bug and workaround: http://jsfiddle.net/248r5yha/1/

**Comment by xile611** [comment] 2016-07-19 13:03
@adrianmc When a Line has a single point, the length of this Line is 0. Then no animation will be triggered, so the state `isAnimationFinished` is always false. 
It's a bug of Line, I'll fix it.

**Comment by xile611** [comment] 2016-07-21 09:58
Fixed in version 0.12.6.

**Closed by xile611** 2016-07-21 09:58 UTC

**Comment by nicholasgonzalezsc** [comment] 2018-08-03 19:40
@xile611 I'm running into this bug with `<Area />` as well

**Comment by dantenol** [comment] 2022-04-08 20:23
It looks like the issue is back on `2.1.9`.

**Comment by leeyeh** [comment] 2022-07-27 12:25
Instead of rendering a zero-length line, how about rendering a real dot in such cases?

**Comment by oliverrees** [comment] 2023-09-11 10:26
Would be great to include this fix in new version - @adrianmcli's work around works well but still frustrating!
