### ISSUE TITLE
Dots now showing when line graph has animation

### ISSUE THREAD

**Issue by Osuriel** [recharts/recharts#2165] opened 2020-06-11 13:38 UTC
## Do you want to request a feature or report a bug?
bug
## What is the current behavior?
Line chart doesn't show Dots when it has an animation on it. i want to use the animation but i have to have the line dots.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
can't get jsfiddle to work
## What is the expected behavior?
shows dots
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
"recharts": "1.7.1",
latest chrome
Latest Mac OS X

**Comment by michaeltomasik** [comment] 2020-07-01 13:29
@Osuriel I was able to fix this problem temporarily with this 
https://github.com/recharts/recharts/issues/804#issuecomment-461251128

but now I modified sth else and the problem is still there, I tried to upgrade to the latest version but it didn;t work

**Comment by ckifer** [comment] 2024-09-22 21:39
closing this since its a duplicate

**Closed by ckifer** 2024-09-22 21:39 UTC
