### ISSUE TITLE
ReferenceLine always positioned at 0 if value passed is not a string, console error thrown

### ISSUE THREAD

**Issue by justrealmilk** [recharts/recharts#4239] opened 2024-02-27 23:06 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/p/sandbox/wandering-cookies-5tkqwq

### Steps to reproduce
Create a chart (I use the ComposedChart) and draw some components. Add a reference line and specify `x="string"`. The shape of my data was as follows and I was trying to draw on the label value: 
```
{
    "id": 1918,
    "date": "2023-09-27T22:14:40.000Z",
    "crawled": 934330,
    "assessed": 934330,
    "frequency": 244882,
    "value": 244882,
    "label": "27/9/2023"
}
```

### What is expected?
Draw on the label.

### What is actually happening?
"NaN" is passed to the SVG component and several errors are thrown to the console

| Environment | Info |
|---|---|
| Recharts | v2.12.1 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

---
I searched around and then thought I'd try a number instead but obviously an axis of timestamps is useless so I'll need to use the label formatter in place of converting my numbies to strings first

**Comment by ckifer** [comment] 2024-02-27 23:12
Can you give some code? What field are you using for your XAxis?

**Comment by justrealmilk** [comment] 2024-02-27 23:24
I've added an example out of frustration of a second issue https://codesandbox.io/p/sandbox/wandering-cookies-5tkqwq

**Comment by ckifer** [comment] 2024-02-27 23:45
Thank you 🙏🏼. Its hard to help without anything to go off of. 

Apologies for the frustration.

If an axis is type of category (default), then the item used in ReferenceLine must be one of those categories. If axis type is number, then the item used in ReferenceLine must be a number.

Based on the example, it looks like your axis is being treated as if it was categorical even though its a number (sometimes you want that, sometimes you don't. I'm not sure what you need here). Changing the axis type to number and then adjusting the domain allows me to see all of the reference lines.

```tsx
          <XAxis
            dataKey="label"
            strokeOpacity="0"
            tick={{ fill: 'var(--foreground)', fillOpacity: '0.6' }}
            tickLine={false}
            domain={([dataMin, dataMax]) => [dataMin, dataMax + 10000000]}
            type="number"
            // tickFormatter={(value) => new Date(value).toLocaleDateString(locale)}
          />
```


> if the particular value isn't one of the chosen ticks

This is a bug for sure, it shouldn't matter if it is a tick or not

**Comment by ckifer** [comment] 2024-02-27 23:49
if I set `ticks` on XAxis to a singular datapoint on a `number` axis or a `category` axis the Reference Lines don't disappear for datapoints that are not ticks, so I don't think the ticks thing is an issue. But will keep checking

**Comment by ckifer** [comment] 2024-02-27 23:56
As for the original issue, it seems to work fine with strings
![image](https://github.com/recharts/recharts/assets/25180830/308fdb5f-ef5b-4d50-864a-955e7a8fd5ed)

```tsx
        <XAxis
            dataKey="label"
            strokeOpacity="0"
            tick={{ fill: 'var(--foreground)', fillOpacity: '0.6' }}
            tickLine={false}
          />
       <ReferenceLine x="27/11/2023" ifOverflow="extendDomain" stroke="red" strokeWidth={2} label="hello" isFront />
       <ReferenceLine x="27/10/2023" ifOverflow="extendDomain" stroke="red" strokeWidth={2} label="hello" isFront />
```

With data like the following (treated as categorical since it is a string):
```
    const data = [
      {
        id: 2114,
        date: '2024-02-13T02:15:23.000Z',
        crawled: 967531,
        assessed: 967531,
        frequency: 265996,
        value: 265996,
        label: '27/9/2023',
      },
      {
        id: 2115,
        date: '2024-02-14T13:30:32.000Z',
        crawled: 967846,
        assessed: 967846,
        frequency: 266059,
        value: 266059,
        label: '27/10/2023',
      },
      {
        id: 2116,
        date: '2024-02-15T07:14:57.000Z',
        crawled: 967926,
        assessed: 856609,
        frequency: 273031,
        value: 273031,
        label: '27/11/2023',
      },
      {
        id: 2117,
        date: '2024-02-16T02:50:25.000Z',
        crawled: 968143,
        assessed: 856811,
        frequency: 273067,
        value: 273067,
        label: '27/12/2023',
      },
    ];
```

**Comment by ckifer** [comment] 2024-02-28 01:27
Hmm. allowDuplciatedCategory is defaulted to true on the XAxis which shouldn't affect reference lines... 

I'll check the sandbox when I get a chance, thanks.

**Comment by ckifer** [comment] 2024-02-28 05:58
you can set `allowDuplicatedCategory={false}` if you want the line to show even when there are duplicates. This essentially removes the duplicate during rendering.

The problem is that when there is a categorical axis with a duplicate, the code uses serial numbers instead of the actual categories to generate the domain. 

When duplicated categories are allowed, it would render it like so 
<img width="515" alt="image" src="https://github.com/recharts/recharts/assets/25180830/66d67589-81b3-43e3-ab19-03721e286d18">
and now the reference line does not know where to render. 
Do I render at the first instance of 27/12/2023, or the second?

To be fair this shouldn't break other reference lines but it does and it looks like the serial number thing is the reason. Reference code here https://github.com/recharts/recharts/blob/3.x/src/chart/generateCategoricalChart.tsx#L384

@PavelVanecek this is interesting and a potential problem when touching these files. Just FYI

**Comment by ckifer** [comment] 2024-02-28 15:04
Ok, will check that. 

Either way, there's some unwanted behavior here so labeled as a bug. Ideally we would render all reference lines that can be rendered (on non-duplicate axis items) and then either render a line at both duplicates, or throw a clear error saying what the issue is.

**Comment by justrealmilk** [comment] 2024-02-28 16:29
Sounds good to me. You might want more options for duplicates but just working at all with them would be great to start - maybe first match with the behaviour noted somewhere.

Here's another fork to show the previously mentioned behaviour where I would expected to see a second reference line between 
https://codesandbox.io/p/sandbox/wandering-cookies-forked-d339y2
<img width="817" alt="image" src="https://github.com/recharts/recharts/assets/156681/e45ab842-c566-476c-878d-d50fa0695def">

**Comment by ckifer** [comment] 2024-02-28 22:42
@justrealmilk the sandbox given uses values for `x` that do not represent one of the categories in the data.

From the docs:
> If the specified x-axis is a category axis, the value of x must be one of the categories, otherwise no line will be drawn.

As soon as you change `x={}`.. to a label that is a part of the data, the lines show up.
[![Edit wandering-cookies (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/wandering-cookies-forked-d339y2?file=%2Fsrc%2FApp.js%3A92%2C14-92%2C24)

**Comment by justrealmilk** [comment] 2024-02-28 22:44
but there's plenty of occasions on which you'd want to display reference lines even if they don't match a precise value in the data set - especially for a time series for example

**Comment by ckifer** [comment] 2024-02-28 22:45
As mentioned earlier, `XAxis` is treated as categorical by default. In order to interpolate by number, you'll have to use `type="number"` on the XAxis and use a formatter to get the display value you want

**Comment by justrealmilk** [comment] 2024-02-28 22:47
that's an excellent point

**Comment by ckifer** [comment] 2024-02-28 22:48
https://codesandbox.io/p/sandbox/wandering-cookies-forked-ht82yq?file=%2Fsrc%2FApp.js%3A99%2C20

**Comment by justrealmilk** [comment] 2024-02-28 23:16
Yeah it's all working now! I can't remember if there's an actual bug or not anymore. In any case, converting to a number type axis meant `tickCount` kicked in and defaulted to 5 ticks so now I'm abusing by setting it to 1000 so that it displays as many as it can fit with the tick labels being snug. It works but maybe there's a better way?

**Comment by ckifer** [comment] 2024-02-28 23:21
> I can't remember if there's an actual bug or not anymore

I'll use this issue to track the fact that ReferenceLines render at `0` when they are invalid and fix that

> maybe there's a better way


Try `interval={0}` and `tickCount={null}`?

**Comment by justrealmilk** [comment] 2024-02-29 01:55
`tickCount={1000}`
<img width="1118" alt="image" src="https://github.com/recharts/recharts/assets/156681/67c53d5b-4777-4df9-841d-1539918098c4">

`interval={0} tickCount={null as any}` 😅
<img width="1120" alt="image" src="https://github.com/recharts/recharts/assets/156681/1d03fb6c-97f6-4ce0-b534-2508488d7eda">

**Comment by ckifer** [comment] 2024-02-29 02:14
lol, interval 0 won't watch for collisions. Try "equidistantPreserveStart". I guess typescript in codesandbox wasn't working or else I'd have seen that need to cast. 

I would just set to the length of your data personally

**Comment by ckifer** [comment] 2024-02-29 06:57
Another reason the lines appeared at `0` was because of `ifOverflow="extendDomain"` without that set this bug isn't noticeable because the data gets cut off which is probably why no one reported it yet

**Comment by ckifer** [comment] 2024-02-29 07:22
https://github.com/recharts/recharts/pull/4244

**Comment by ckifer** [comment] 2024-02-29 08:20
Ok the "bug fix" here is merged though won't be released until v3. Going to close this issue since your issues have cleared up and the NaN behavior has been mitigated for the future

**Closed by ckifer** 2024-02-29 08:20 UTC
Labels: bug, enhancement
