### ISSUE TITLE
Console warning

### ISSUE THREAD

**Issue by KevinBurton** [recharts/recharts#2231] opened 2020-08-11 14:36 UTC
When I run my code I get the following warning on the console:

```
react_devtools_backend.js:2273 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Bar, BarChart
```

The code I am using to render the chart is

```
const CustomizedLabel:FC<CustomLabelProps> = ({x, y, stroke, value}) => {
   	return <text x={x} y={y} dy={-4} fill={stroke} fontSize={10} textAnchor="middle">{value}</text>
};
. . .
                <BarChart width={900} height={600} data={chartData}
                          margin={{top: 5, right: 30, left: 20, bottom: 5}}>
                  <CartesianGrid strokeDasharray="3 3"/>
                  <XAxis dataKey="name" height={60}/>
                  <YAxis/>
                  <Tooltip/>
                  <Legend />
                  <Bar dataKey="positive" fill="#8884d8" label={<CustomizedLabel/>}/>
                  <Bar dataKey="newpos" fill="#8884d8"/>
                  <Bar dataKey="hospitalization" fill="#82ca9d" />
                  <Bar dataKey="deaths" fill="#f00c0c" />
                  <Bar dataKey="newdeaths" fill="#f00c0c" />
                </BarChart>

```

**Comment by trevoro** [comment] 2020-08-11 15:46
The warning more or less explains the issue.
The library needs to be refactored to use `componentDidUpdate` instead.

**Comment by ckifer** [comment] 2020-08-11 15:47
Duplicate of #1835

**Closed** 2020-12-18 09:28 UTC
