### ISSUE TITLE
AreaChart active index isn't captured as expected.

### ISSUE THREAD

**Issue by ajay-studio137** [recharts/recharts#5270] opened 2024-11-25 04:59 UTC
## Do you want to request a feature or report a bug?
AreaChart is displaying 4 different value. On hover, I want to display only the value which is hovered.

## What is the current behavior?
As of now, it shows correct top value and second top. The bottom 2 seems to be taken over by the second top as no change is visible on hovering over bottom 2 values.

## What is the expected behavior?
I want to display only the hovered value in the tooltip as content.

`<Area type="monotone" dataKey="green" stroke="#41B768" fill="url(#colorGreen)" onMouseMove={e => setActiveIndex(0)} />`
Tooltip -> <p className={"intro"}> ${payload?.[activeIndex].value}</p>

The value seems to be fuzzy and not working as expected, as of now.

**Comment by ajay-studio137** [comment] 2024-11-25 05:42
1. Area 4 is overriding the values of Area2 and Area3 as Area4 has higher value than Area2 and Area3.
2. The tooltip value isn't getting changed on hovering over data point but is getting changed on hovering over particular area segment. The value should get updated on hovering over the data point.

**Comment by ajay-studio137** [comment] 2024-11-25 06:16
Used a custom activeDot
```
  activeDot={({cx, cy}) => <g
          key={`dot`}
          onMouseEnter={() => setActiveIndex(2)}
          onMouseLeave={() => setActiveIndex(null)}
        >
          <circle
            cx={cx || 0}
            cy={cy || 0}
            r={4}
            fill="#FF6596"
            stroke="#FF6596"
            strokeWidth={1}
          /></g>}  
```

The last dot seems to be unreachable which means no hover would be triggered for the same. Areas are getting overridden by other areas.

**Comment by ckifer** [comment] 2024-11-25 06:33
Can you make a codesandbox?

**Comment by ajay-studio137** [comment] 2024-11-25 07:49
Code is available at [Recharts Playground](https://playcode.io/2166906)

**Comment by ckifer** [comment] 2024-11-25 16:29
Working codesandbox based off your code https://codesandbox.io/p/sandbox/synchronized-area-chart-forked-yg6mll
(I need to be able to fork it)

This isn't currently possible. Since these are not stacked area charts the Areas overlay each other. SVG does not have a notion of "z-index" so order is determined by render order. If green is rendered over blue then blue's event handlers will never be accessible. If green is over blue but not over purple then purple's event handlers will be accessible, etc.

You can see this if you inspect the area elements one by one to notice where they are rendered.

Ideally the `shared={false}` prop on the area would separate the points like you want, but that doesn't currently work for area charts. Nothing we can really do about it for now.

**Comment by ckifer** [comment] 2024-11-25 19:54
Essentially a duplicate of https://github.com/recharts/recharts/issues/488

**Comment by ajay-studio137** [comment] 2024-11-26 04:00
Is their any value to display tooltip content according to y coordinates like mapping y coordinate to yaxis and then checking for nearest value in the array.

**Comment by ckifer** [comment] 2024-11-26 04:07
You could try. 

Make a YAxis scale with d3 and pass it to YAxis.

But I think generally you only scale from Y value to Y position not Y position to Y value. So you may have to convert and check against your high and low end values in each category.

**Comment by ajay-studio137** [comment] 2024-11-26 04:13
Is their any way to get the max yaxis value of area chart?

This code is showing the correct y value.
```
 const CustomTooltip = (props) => {
    const { active, payload, coordinate, activeIndex, nearestValue } = props;
    if (active && payload && payload.length && payload[activeIndex]) {
      const closest = payload.map(p => p.value).reduce(function(prev, curr) {
        const curVal = curr - nearestValue;
        const prevVal = prev - nearestValue;
        if ( curVal < 0 ) return prev;
        else if ( prevVal < 0 ) return curr;
        return curr - nearestValue < prev - nearestValue ? curr : prev;
      });

      return (
        <div className={"areaChartTooltip"}>
          {closest}
        </div>
      );
    }
  }
```

**Comment by ckifer** [comment] 2024-11-26 04:15
You'd have to find it yourself from your data. You can get the max value in the domain prop of your `YAxis` but that isn't helpful here.

**Comment by ajay-studio137** [comment] 2024-11-26 04:22
ok, passing `domain={[0,'dataMax']}` to `YAxis` and then computing dataMax manually from the given data. 

Thank You for guidance `Coltin`.

**Comment by ckifer** [comment] 2024-11-26 04:33
Solved it @ajay-studio137 

https://codesandbox.io/p/sandbox/synchronized-area-chart-forked-mldvdv

**Comment by ckifer** [comment] 2024-11-26 04:35
Code is really messy and you can definitely clean it up quite a bit but the theory is right.

1. custom scale, pass it to YAxis
2. get y position from tooltip and convert it to y value with scale.invert
3. find the closest value in the `payload` object to the converted Y value
4. display that value

```tsx
const CustomTooltip = (props) => {
  const { active, payload, coordinate, activeIndex } = props;
  const currentY = coordinate.y;
  if (
    active &&
    payload &&
    payload.length &&
    payload[activeIndex] &&
    payload[activeIndex].payload
  ) {
    const currentPayload = payload[activeIndex].payload;
    // remove date from currentPayload
    delete currentPayload.date;
    // invert the custom scale to get the value for currentY
    const currentYScaledToValue = yScale.invert(currentY);
    console.log("convertedY", currentYScaledToValue);

    // convert object to array
    const arrValues = Object.values(currentPayload);

    console.log(arrValues);
    // find value nearest to the current Y
    const nearest = nearestValue(arrValues, currentYScaledToValue);

    return (
      <div className={"customTooltip"}>
        <p className={"intro"}>{` ${nearest} ml`}</p>
      </div>
    );
  }
  return null;
};
```

**Comment by ajay-studio137** [comment] 2024-11-26 07:06
`d3Scale` is hiding the max value on yAxis when value is lower than the next `scale linear` value.

**Comment by ckifer** [comment] 2024-11-26 07:08
Not sure what you mean. You can set the domain and range on the scale you pass in if you need to.

**Closed** 2024-12-13 07:39 UTC
Labels: enhancement, feature request
