### ISSUE TITLE
ReferenceArea sometimes disappears near edges

### ISSUE THREAD

**Issue by shelbylsmith** [recharts/recharts#3275] opened 2023-01-24 09:58 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/barchart-reference-area-dxfoj1)

### Steps to reproduce
Change the size of the container rendering the bar chart with your mouse until you reach a point where the the ReferenceArea disappears.

### What is expected?
The ReferenceArea does not disappear at any size

### What is actually happening?
The ReferenceArea sometimes disappears at certain widths.

| Environment | Info |
|---|---|
| Recharts | v2.3.2 |
| React | 17.0.1 |
| System | macos 13.1 |
| Browser | Chrome 109.0.5414.87 |

![Kapture 2023-01-24 at 10 57 17](https://user-images.githubusercontent.com/76775332/214262143-2d8c876f-a724-48ef-bcff-3f042e95daf1.gif)

**Comment by shelbylsmith** [comment] 2023-01-24 10:06
I believe the issue is related to:
https://github.com/recharts/recharts/blob/90ed7e7a81b4ff8c4df54e31503aa778edd36caa/src/util/CartesianUtils.ts#L201-L209
And there is an unused epsilon in the `ScaleHelper` which should be included in this condition?
https://github.com/recharts/recharts/blob/90ed7e7a81b4ff8c4df54e31503aa778edd36caa/src/util/CartesianUtils.ts#L139-L143

**Comment by shelbylsmith** [comment] 2023-01-24 10:11
I have previously verified that the reason for the `ReferenceArea` disappearing is that one of the points doesn't pass the `isInRange` function.

**Comment by proke03** [comment] 2023-01-24 10:38
Thank you!
I checked this bug is reproduced locally.

**Comment by ckifer** [comment] 2023-02-02 01:56
Ah actually looks like there is a flag for this

```
<ReferenceArea
          x1={"Oct 21"}
          x2={"Oct 27"}
          y1={0}
          y2={1000}
          stroke="red"
          strokeOpacity={0.3}
          ifOverflow="extendDomain"
/>
```

The default is `ifOverflow = 'discard'` which is why this happens. 

Maybe we could change the default to `extendDomain` because it makes the most sense?

**Comment by ckifer** [comment] 2023-02-02 02:02
@nikolasrieble @proke03 @Yilun-Sun for viability

**Comment by Yilun-Sun** [comment] 2023-02-02 08:10
### The differences between `ifOverflow` values

Using the example in the CodesandBox link

#### extendDomain
```
<ReferenceArea
  y1={-1000}
  y2={1000}
  ifOverflow='extendDomain'
/>
```
![image](https://user-images.githubusercontent.com/43896664/216265527-c92ab456-ae64-4636-8af4-18b773f16103.png)

#### visible
```
<ReferenceArea
  y1={-1000}
  y2={1000}
  ifOverflow='visible'
/>
```
![image](https://user-images.githubusercontent.com/43896664/216266008-759e8a32-84df-4ecf-a80e-2d140c418084.png)


#### hidden
```
<ReferenceArea
  y1={-1000}
  y2={1000}
  ifOverflow='hidden'
/>
```
![image](https://user-images.githubusercontent.com/43896664/216266302-805145fa-bc73-4e47-998d-d460264a11df.png)


#### discard
```
<ReferenceArea
  y1={-1000}
  y2={1000}
  ifOverflow='discard'
/>
```
![image](https://user-images.githubusercontent.com/43896664/216266376-32a6c190-9dc6-4254-a73f-1d51e4a6c2d5.png)

### The reason
If the start and end points of the reference area are overflowed the current scales
- `discard` will hide all the reference area
- `hidden` will clip the reference area to the current domain
- `extendDomain` will extend the current domain to fit the overflowed points
- `visible` will show all the reference area in current domain, even if it's out of range

**Comment by Yilun-Sun** [comment] 2023-02-02 08:16
I will add this to our doc, and yes set the default value to `extendDomain` could avoid the area blinkling while resizing the component. Also make it less likely to appear that set a overflowed reference area but not display any of it.

**Comment by Yilun-Sun** [comment] 2023-02-02 08:24
> 

No problem, is the storybook ready?

**Comment by nikolasrieble** [comment] 2023-02-02 08:29
> > @Yilun-Sun What do you think about directly adding a story to storybook for this example?
> 
> No problem, is the storybook ready?

Just landed. And is already deployed.

**Comment by proke03** [comment] 2023-02-02 08:38
Permalink
https://master--63da8268a0da9970db6992aa.chromatic.com

**Comment by Yilun-Sun** [comment] 2023-02-14 07:11
```Javascript
<ReferenceArea
  y1={-1000}
  y2={1000}
  ifOverflow='hidden'
/>
```
Closes issue

**Closed by Yilun-Sun** 2023-02-14 07:11 UTC
Labels: bug
