### ISSUE TITLE
TypeScript type definitions are outdated

### ISSUE THREAD

**Issue by havenchyk** [recharts/recharts#2410] opened 2021-01-25 12:36 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com](https://github.com)

### Steps to reproduce
try to run `npm run tsc` from latest master and you'll notice difference between published and generated type definitions

### What is expected?
types generated are correct

### What is actually happening?
e.g. Line doesn't have `data` and many other type definitions missed, it can be fixed easily with just `npm run tsc && npm publish`

| Environment | Info |
|---|---|
| Recharts | v2.0.3 |
| React | 16 |
| System | macOS |
| Browser | any |

---
I can help with automation if you want to review/accept a PR

**Comment by borisyordanov** [comment] 2021-01-26 11:16
@xile611 When can we have a release?

**Comment by terenceodonoghue** [comment] 2021-01-27 08:51
Just noticed a possibly related issue @xile611 after PR https://github.com/recharts/recharts/pull/2408 - the new types added in the PR are produced under `types/src` while the old ones are published under `types` and referenced in the package.json.

**Comment by avindra** [comment] 2021-01-28 20:10
Duplicate of #2398

**Closed by avindra** 2021-01-28 20:10 UTC

**Comment by avindra** [comment] 2021-01-28 20:15
> I can help with automation ...

@havenchyk  I think this would be a welcome change. Are there any standard ways to publish npm modules with Github actions yet?


> Just noticed a possibly related issue

@terenceodonoghue Not able to see an issue here, can you clarify or open a new issue if it persists?

**Comment by terenceodonoghue** [comment] 2021-01-29 00:59
@avindra I meant to say, that PR I referenced updated some existing types and added new ones - the published package contained these changes, but it also contained the old, outdated definitions.

**Comment by avindra** [comment] 2021-01-31 16:15
> the published package ... also contained the old, outdated definitions

Gotcha. I think that may be related to whatever happened in #2398

**Comment by havenchyk** [comment] 2021-02-02 13:25
@avindra still the same problem

**Comment by avindra** [comment] 2021-02-02 16:31
Unfortunately I do not have publish access, so I can't do anything. @xile611 or @arcthur are the only 2 with that AFAIK.
