### ISSUE TITLE
Pie chart with animation causes 'non-unique keys' react-dom warning

### ISSUE THREAD

**Issue by lennartfranke** [recharts/recharts#4004] opened 2023-11-30 09:52 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-lhq77z?file=%2Fsrc%2Findex.js)

### Steps to reproduce
Open codesandbox and open console, see react non-unique key warnings.

### What is expected?
All generated sector elements have a unique key in any case.

### What is actually happening?
If `isAnimationActive` is set to `true` all sectors in the pie chart are initially rendered with the same start and end angle and therefore have the same key prop.

| Environment | Info |
|---|---|
| Recharts | v2.10.2 |
| React | react 18.2.0 |
| System | MacOS 14.1.1 |
| Browser | Chrome 119.0.6045.159 |

**Comment by ckifer** [comment] 2023-11-30 15:04
@imagine Life

**Comment by ckifer** [comment] 2023-11-30 17:58
@imagineLife it looks like there are more instances of this. Can you go through the demo and look for all instances? They don't show on the storybook for some reason...

`npm run demo` -> ComposedChart - produces another duplicate set of keys for tooltip

**Comment by ckifer** [comment] 2023-11-30 18:00
same with legend item

**Comment by imagineLife** [comment] 2023-11-30 18:07
Surely 👍 
- Can this convo be "migrated" to [this issue](https://github.com/recharts/recharts/issues/3273)? there are perhaps _many_ keys that need updating that aren't "throwing" lint errors during development :/ I can post more based on some of my findings either here or the other issue

**Comment by ckifer** [comment] 2023-11-30 18:19
Summarized over there

**Comment by ckifer** [comment] 2023-12-01 01:52
This should be resolved in the latest (see sandbox https://codesandbox.io/s/pie-chart-of-straight-angle-forked-rvsnly)

We'll try to be more careful when making key changes!

**Comment by HHongSeungWoo** [comment] 2023-12-02 04:08
Unfortunately, it seems that `Bar` also need to be reverted

**Comment by imagineLife** [comment] 2023-12-02 12:06
> Unfortunately, it seems that `Bar` also need to be reverted
Hi @HHongSeungWoo 👋 Do you have &/or can you put together an example showing the key error, like a code sandbox? :/ The `bar` tests all pass and the `demo` bar charts all render without key errors, I'd love to see what props and/or features cause the key issue! (_and likely reset the recent key-change back to index-based until more thorough testing is done on cases like this!_)

**Comment by DiegoZan** [comment] 2024-01-10 17:13
Hi!
I am also having this warning.
Code is very straightforward:
```
<ResponsiveContainer width='100%' height='100%'>
   <BarChart
      data={dataPercentage}
      layout='vertical'
      margin={{ top: 5, right: 10, left: 10, bottom: 5,}}
   >
      <CartesianGrid strokeDasharray='3 3' fill='#eee' />
      <XAxis type='number' />
      <YAxis type='category' dataKey="name" tick={{ fontSize: 12 }} />
      <Tooltip content={<CustomTooltip />} />
      <Legend wrapperStyle={{fontSize: 12, fontWeight: 600}} formatter={renderColorfulLegendText} iconSize={12} />
      <Bar dataKey="inSLA" stackId="a" fill="#007700" maxBarSize={10} />
      <Bar dataKey="outSLA" stackId="a" fill="#cc0000" maxBarSize={10} />
   </BarChart>
</ResponsiveContainer>
```

The warning only shows when two bars have the exact same values. E.g.:
```
{
   name: 'Service 1',
   inSLA: 5,
   outSLA: 7
}
 
{
   name: 'Service 2',
   inSLA: 5,
   outSLA: 7
}```

Warnings are:
```
Warning: Encountered two children with the same key, `rectangle-164.62-5-83,100`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

**Comment by ckifer** [comment] 2024-01-10 17:15
Is this after updating to 2.10.4?

**Comment by DiegoZan** [comment] 2024-01-10 17:31
It happens with both `2.10.3` and `2.10.4`.

**Comment by ckifer** [comment] 2024-01-10 17:39
Thanks - sorry about this, these key issues are hard to manage...

**Comment by ckifer** [comment] 2024-01-10 17:40
@imagineLife - I don't think its possible to use your approach for `key` in pie sectors, we'll have to add the index in there to prevent bugs like this

**Comment by imagineLife** [comment] 2024-01-18 12:58
Hello all 👋 
[here's a fork+branch showing no errors](https://github.com/imagineLife/recharts-fork/tree/animated-bar-same-names) using the example in the above comment, sans legend and tooltip, as some code is not in that snippet.  

@ckifer @DiegoZan can a separate issue+codesandbox be made to show the key error? 
![Screenshot 2024-01-18 at 7 57 16 AM](https://github.com/recharts/recharts/assets/24195040/dc146da1-e89a-4b04-b89c-78b4f3d91d39)

**Comment by TVYDev** [comment] 2024-01-26 03:40
I have also been facing this warning with PieChart.

`recharts: 2.10.4`
`react: 18.2.0`

**Comment by ckifer** [comment] 2024-01-26 04:40
Can you provide us the data that causes this?

**Comment by TVYDev** [comment] 2024-01-26 07:00
@ckifer 
I've done a little more testing.
It seems to show warning when two or more items of `data` have `value` property equals zero.

[CodeSandbox](https://codesandbox.io/p/sandbox/react-recharts-pie-wd2547?file=%2Fsrc%2FAccountPieChart.tsx%3A11%2C4&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clru8n1v90006356a0nbnw9jx%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clru8n1v80002356ax8vyy1k3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clru8n1v90003356aro035z5n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clru8n1v90005356ae9t1fjzq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clru8n1v80002356ax8vyy1k3%2522%253A%257B%2522id%2522%253A%2522clru8n1v80002356ax8vyy1k3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clru8n1v80001356akp29eqao%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clru9zj9a00023569elj1p5an%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A4%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A4%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FAccountPieChart.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clru9zj9a00023569elj1p5an%2522%257D%252C%2522clru8n1v90005356ae9t1fjzq%2522%253A%257B%2522id%2522%253A%2522clru8n1v90005356ae9t1fjzq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clru8n1v90004356a0y1o33yq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clru8n1v90004356a0y1o33yq%2522%257D%252C%2522clru8n1v90003356aro035z5n%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clru8n1v90003356aro035z5n%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to check out.

**Comment by ckifer** [comment] 2024-01-26 15:06
@imagineLife

**Comment by sudojoseph** [comment] 2024-02-01 08:14
follwoing

**Comment by ckifer** [comment] 2024-02-09 01:12
re-added index in 2.12. Not the end of the overall issue but should resolve the errors

**Closed by ckifer** 2024-02-09 01:12 UTC

**Comment by viniciusrad** [comment] 2024-04-10 18:07
I had this problem for a whole day, it took my sleep, the next day after a lot of research I partially understood the reason for the problem/warning and managed to make it stop

I used a trick that may not be the best solution, but at least the warning disappeared

I used
`import dynamic from "next/dynamic";
`
` const NoSSR = dynamic(() => import('../componentes/NeedleChartComponent'), { ssr: false })
`
I don't know why but 'use client' in the files involved wasn't enough

and on return I used
`      <NoSSR charValue={40} labelTitle='Cpu Usage'/>
`

Maybe everyone should try this approach when the problem arises.

**Comment by ckifer** [comment] 2024-04-10 19:06
>  it took my sleep

😅 - hoping that this issue doesn't take anyone else's sleep

@viniciusrad can you share the code and the data that made the chart throw the key error? You shouldn't have to do that work-around. Does this happen when not using next?

**Comment by TimonSotiropoulos** [comment] 2024-04-16 02:18
I am having the same issue, basically I am rendering 2 Scatter datasets because i want the resulting points to be different sizes (and there doesn't seem to be a way to get access to that within the Scatter Cells, or at least not in the documentation).

The easiest way to solve this would be to add the key from the parent Scatter component down onto the actual Layer that is wrapping each ScatterPoint render:

```
  renderSymbolsStatically(points: ScatterPointItem[]) {
    const { shape, activeShape, activeIndex } = this.props;
    const baseProps = filterProps(this.props, false);

    return points.map((entry, i) => {
      const isActive = activeIndex === i;
      const option = isActive ? activeShape : shape;
      const props = { key: `symbol-${i}`, ...baseProps, ...entry };

      return (
        <Layer
          className="recharts-scatter-symbol"
          {...adaptEventsOfChild(this.props, entry, i)}
          // eslint-disable-next-line react/no-array-index-key
          key={`symbol-${entry?.cx}-${entry?.cy}-${entry?.size}-${i}`} // <---- Update this line to pass the key from the scatter parent
          role="img"
        >
          <ScatterSymbol option={option} isActive={isActive} {...props} />
        </Layer>
      );
    });
  }
```

**Comment by ckifer** [comment] 2024-04-16 02:23
@TimonSotiropoulos feel free to create a PR if you have something that makes sense

**Comment by TimonSotiropoulos** [comment] 2024-04-16 02:53
> @TimonSotiropoulos feel free to create a PR if you have something that makes sense

https://github.com/recharts/recharts/pull/4434 is the idea, i'm sure it can be improved.

**Comment by danielchernilov** [comment] 2024-11-14 11:15
Hi all,
I'm encountering the same behavior with the BarChart component. I'm using Recharts v2.12.7 and I get the following warning:

_Warning: Encountered two children with the same key, `rectangle-74.93023899018233-160-0,0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version._

Has anyone found a solution or workaround for this?

Thanks

**Comment by ckifer** [comment] 2024-11-14 15:11
@danielchernilov can you create a new issue and include a reproduction? Thanks!
