### ISSUE TITLE
Scatter chart with custom shape and responsive container does not set correct height on initial render

### ISSUE THREAD

**Issue by NikoLehtovirta** [recharts/recharts#4060] opened 2024-01-17 13:03 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-responsive-scatter-issue-8459n5)

### Steps to reproduce
Create responsive scatter chart and add legend and custom shape to scatter element.

### What is expected?
Expected chart to show custom shapes inside the chart below the legend on the initial render

### What is actually happening?
Custom shapes are currently rendered too high on the chart and it will only move to correct position after chart size changes.

| Environment | Info |
|---|---|
| Recharts | v2.10.4 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Firefox 121.0, Chrome 120 |

---
I've tested that issue has come up with the 2.10 release as this does not happen with the 2.9 release

**Comment by HHongSeungWoo** [comment] 2024-01-27 13:42
This seems to be an issue caused by non-unique keys.
imo, reverting to the previous state seems to be the easiest solution. What do you think?
@imagineLife

**Comment by ckifer** [comment] 2024-02-09 01:06
released in 2.12!

**Closed by ckifer** 2024-02-09 01:06 UTC
Labels: bug
