### ISSUE TITLE
connectNulls={true} does not work with stacked area chart.

### ISSUE THREAD

**Issue by Gunner17** [recharts/recharts#2316] opened 2020-11-03 20:04 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/gunner17/vz19yfw0/4/](https://jsfiddle.net/gunner17/vz19yfw0/4/)

### Steps to reproduce
Please check our both these fiddles:
[https://jsfiddle.net/gunner17/vz19yfw0/4/](https://jsfiddle.net/gunner17/vz19yfw0/4/) (Example: 1, single series stacked area)
[https://jsfiddle.net/gunner17/vz19yfw0/4/](https://jsfiddle.net/gunner17/puadhm3g/3/) (Example: 2, multiple series stacked area)

The stacked area chart null points are not connecting even after using `connectNulls={true}` in Area component. If I remove `stackId="1"` from the first example's Area component, the null points get connected.

### What is expected?
When using `connectNulls={true}` on stacked area charts, null points should get connected.

### What is actually happening?
When using `connectNulls={true}` on stacked area chart, null points are not getting connected.

<img width="578" alt="Screen Shot 2020-11-02 at 5 49 14 PM" src="https://user-images.githubusercontent.com/11354728/98034969-a5f89e00-1dcc-11eb-81c6-8c150ca8ff9e.png">

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.13.1 |
| System | MacOS Mojave 10.14.6 |
| Browser | Safari 13.1.2, Chrome 84.0.4147.135 |

**Comment by anselmpaul** [comment] 2021-01-23 14:35
Hey, I've tried looking into this but I'm absolutely not familiar with the code base and have no idea, how or where the points / baseLine is calculated. 
I've reproduced the issue int the official demo files, see [my fork](https://github.com/anselmpaul/recharts/blob/master/demo/component/AreaChart.tsx)
To me it looks like the stacked areas are being calculated wrong. I'd like to investigate this further if someone can point me in the right direction.
![image](https://user-images.githubusercontent.com/22657579/105583651-7f754e00-5d90-11eb-9bec-c694e31decb8.png)

**Comment by ckifer** [comment] 2024-11-18 21:10
https://codesandbox.io/p/sandbox/recharts-issue-template-forked-skp393?workspaceId=d53913d8-85a8-463b-9dc1-f7770946ba51

Updated sandbox
![image](https://github.com/user-attachments/assets/4827710b-2e27-4539-a6ed-0e3f5d3fa0f8)


Looks like this is resolved in the latest

**Closed by ckifer** 2024-11-18 21:10 UTC
Labels: bug
