### ISSUE TITLE
Points attribute unnecessarily included on Line, Area, Scatter path elements

### ISSUE THREAD

**Issue by tylerben** [recharts/recharts#2478] opened 2021-03-05 17:57 UTC
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unnecessary-points-attribute-issue-9vbxc?file=/src/App.tsx)

### Steps to reproduce
1. Open code sandbox
2. Open the browser dev tools and inspect the path element for one of the rendered lines
3. Notice that the points attribute is present on the path element and looks something like "points="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]"

### What is expected?
I would not expect the points attribute to exist on the path element.

### What is actually happening?
The points attribute to exists on the path element with the value set to the internally generated points prop.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | MacBook Pro (16-inch, 2019) macOS BigSur Version 11.2.1 |
| Browser | Firefox Version 86.0 |

---
This is present for the Line, Area, and Scatter components. It doesn't break anything but adds noise to the DOM and has the potential to slow down diffing.This might be intentional but thought I would flag it in case it wasn't!

**Comment by schroeer** [comment] 2022-01-26 12:43
Duplicate of #2610

**Comment by ckifer** [comment] 2022-12-14 23:55
Closing this in favor of #2610

**Closed by ckifer** 2022-12-14 23:55 UTC
