### ISSUE TITLE
Patterns not filled on bar charts after multiple recharts created

### ISSUE THREAD

**Issue by paddymul** [recharts/recharts#5230] opened 2024-11-09 22:43 UTC
## Do you want to request a feature or report a bug?
This is a bug
## What is the current behavior?
With my app build using recharts, when I inject multiple instances of the charts, the bars go from being filled to being just an outline. (Screenshots below)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).

I have spent a lot of time trying to get this to a minimally reproducable test case, and have failed.

My app is a complex jupyter widget, that is primarily an ag-grid table, that optionally has recharts in some cells.

If you got to this link, then execute the cells by Menu Kernel > Restart Kernel and Run All Cells
https://paddymul.github.io/buckaroo-examples/lab/index.html?path=Histograms-demo.ipynb

I would get all of the cells to execute, then inspect the dome to see what's happening.

I have a simpler JS-only test environment where even after putting 20 some odd widgets on the screen they all render properly, I don't have that version available on a playground.  You can play with the general setup here https://buckaroo-data.readthedocs.io/en/latest/examples/#/DFViewerEx_string_index 

## What is the expected behavior?

Charts should look like this
<img width="758" alt="Screenshot 2024-11-09 at 5 25 30 PM" src="https://github.com/user-attachments/assets/72775237-356a-4b3f-81af-7de766e5ca18">
but after multiple injections into the dom they end up looking like
<img width="666" alt="Screenshot 2024-11-09 at 5 27 02 PM" src="https://github.com/user-attachments/assets/808f9d74-dcdf-4abe-9b82-9368b74299c9">

**Comment by ckifer** [comment] 2024-11-10 01:31
Hey Paddy, thanks for the report. 

Since it's not reproducible I'm not 100% sure how to proceed here. Can you try making your defs in an svg outside of recharts and see if that helps?

**Comment by paddymul** [comment] 2024-11-10 16:14
I understand that this is a specific issue with my setup.  If anyone else has these problems, I'd be very interested to figure out how they fix them.  It's not reasonable for you to work from this bug report.

Since my app does no manipulation of the fill patterns, all of this is a bit surprising.

Sometimes just filing a bug makes me explicitly think through the problem thoroughly. 

Here are a couple of other things I could try, open to further suggestions:
1. I have seen this problem in both Firefox and Chrome
2. I could compare the SVG in the DOM for filled vs non-filled charts.
3. I could embed the exact SVG into the same place that I see the bug with the recharts component and see if I still see the non-fill problem
4. I could instrument Recharts with deubgging console statements, especially around `fill`. Open to suggestions
Anything else?

**Comment by paddymul** [comment] 2024-11-10 16:19
In that process, I just saw this.  The fill dissappears and reappears based on scroll position.

Some of this feels like a browser bug, but the same behavior in FF and Chrome is a counter factual.

https://github.com/user-attachments/assets/1b7f6ef5-ccaf-49bb-84d6-f6ba260943a2

**Comment by ckifer** [comment] 2024-11-10 16:19
Makes sense!

If you do 2 and 4 from that list and there are issues with what fill resolves to in recharts I can definitely look into it from there. 

The difference in dom might tell me we have some extra rerenders or something weird going on with defaults.

Thanks!

**Comment by ckifer** [comment] 2024-11-10 16:20
Super weird. Can you get the dom diff for that?

**Comment by paddymul** [comment] 2024-11-10 16:26
Working DOM for NA (Red cross striped)
```
<svg class="recharts-surface" width="100" height="24" viewBox="0 0 100 24" style="width: 100%; height: 100%;">
   <title></title>
   <desc></desc>
   <defs>
      <clipPath id="recharts955-clip">
         <rect x="5" y="5" height="14" width="90"></rect>
      </clipPath>
   </defs>
   <defs>
      <pattern id="star" width="10" height="10" patternUnits="userSpaceOnUse">
         <polygon stroke="pink" points="0,0 2,5 0,10 5,8 10,10 8,5 10,0 5,2"></polygon>
      </pattern>
      <pattern id="stripe" width="4" height="4" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
         <rect width="2" height="4" fill="red"></rect>
      </pattern>
      <pattern id="circles" width="4" height="4" patternUnits="userSpaceOnUse">
         <circle data-color="outline" stroke="pink" cx=".5" cy=".5" r="1.5"></circle>
      </pattern>
      <pattern id="checkers" x="0" y="0" width="4" height="4" patternUnits="userSpaceOnUse">
         <rect stroke="#0f0" x="0" width="2" height="2" y="0"></rect>
         <rect x="2" width="2" height="2" y="2"></rect>
      </pattern>
      <pattern id="leafs" x="0" y="0" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="translate(1, 1) rotate(0) skewX(0)">
         <svg width="5" height="5" viewBox="0 0 100 100">
            <g fill="teal" opacity="1">
               <path d="M99.9557 99.9557C45.4895 98.3748 1.6248 54.5101 0.0439453 0.0439453C54.5101 1.6248 98.3748 45.4895 99.9557 99.9557Z"></path>
            </g>
         </svg>
      </pattern>
   </defs>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle">
               <path x="14" y="5" width="72" height="14" radius="0" fill="url(#stripe)" name="NA" class="recharts-rectangle" d="M 14,5 h 72 v 14 h -72 Z"></path>
            </g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
</svg>
```

**Comment by paddymul** [comment] 2024-11-10 16:27
Non-working DOM for NA
```
<svg class="recharts-surface" width="100" height="24" viewBox="0 0 100 24" style="width: 100%; height: 100%;">
   <title></title>
   <desc></desc>
   <defs>
      <clipPath id="recharts1063-clip">
         <rect x="5" y="5" height="14" width="90"></rect>
      </clipPath>
   </defs>
   <defs>
      <pattern id="star" width="10" height="10" patternUnits="userSpaceOnUse">
         <polygon stroke="pink" points="0,0 2,5 0,10 5,8 10,10 8,5 10,0 5,2"></polygon>
      </pattern>
      <pattern id="stripe" width="4" height="4" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
         <rect width="2" height="4" fill="red"></rect>
      </pattern>
      <pattern id="circles" width="4" height="4" patternUnits="userSpaceOnUse">
         <circle data-color="outline" stroke="pink" cx=".5" cy=".5" r="1.5"></circle>
      </pattern>
      <pattern id="checkers" x="0" y="0" width="4" height="4" patternUnits="userSpaceOnUse">
         <rect stroke="#0f0" x="0" width="2" height="2" y="0"></rect>
         <rect x="2" width="2" height="2" y="2"></rect>
      </pattern>
      <pattern id="leafs" x="0" y="0" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="translate(1, 1) rotate(0) skewX(0)">
         <svg width="5" height="5" viewBox="0 0 100 100">
            <g fill="teal" opacity="1">
               <path d="M99.9557 99.9557C45.4895 98.3748 1.6248 54.5101 0.0439453 0.0439453C54.5101 1.6248 98.3748 45.4895 99.9557 99.9557Z"></path>
            </g>
         </svg>
      </pattern>
   </defs>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle"></g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
   <g class="recharts-layer recharts-bar">
      <g class="recharts-layer recharts-bar-rectangles">
         <g class="recharts-layer">
            <g class="recharts-layer recharts-bar-rectangle">
               <path x="14" y="5" width="72" height="14" radius="0" fill="url(#stripe)" name="NA" class="recharts-rectangle" d="M 14,5 h 72 v 14 h -72 Z"></path>
            </g>
         </g>
      </g>
      <g class="recharts-layer"></g>
   </g>
</svg>
```

**Comment by paddymul** [comment] 2024-11-10 16:28
I really appreciate the support and enjoy debugging with you @ckifer !

**Comment by ckifer** [comment] 2024-11-10 16:46
Another thing you could try is just making an svg rect outside of recharts with the same fill in the same grid and see if it still happens or not

**Comment by ckifer** [comment] 2024-11-10 17:47
Besides the `clipPath` id these DOMs are exactly the same. Clip Path ID is generated and it being different should not matter

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/578de349-bb21-448d-b690-ad48de41e97e">

**Comment by paddymul** [comment] 2024-11-10 18:02
I'll play with that and a couple of different things.

I'm also going to try an example in my js sandbox where each time I click, it adds another grid.

I double checked in Firefox and I get the exact same fill/no-fill behavior while scrolling on the third grid.  

Don't take too much of your time on this, I have some more homework to do.

**Comment by ckifer** [comment] 2024-11-10 18:12
Sounds good. Just one more thing for information - recharts does nothing with gradients or patterns except for apply them to the target element. Thats mostly why I think it might be outside of recharts, but still hard to tell

**Comment by paddymul** [comment] 2024-11-10 19:49
Well dynamically adding grids with embedded recharts in a simple environment (non-jupyter) doesn't reproduce the bug.
```
<h2>Count: {count}</h2>
      <button onClick={increment}>Increment</button>
      <button onClick={decrement}>Decrement</button>
      <button onClick={reset}>Reset</button>
      {items.map((item, index) => (
        <div>
                  <HistoWidget />
                  <StringWidget />
                  <div style={{border:"10px solid green", height:"500px", }}>interstitial</div>
        </div>
      ))}
    </div>
```

**Comment by ckifer** [comment] 2024-11-10 19:54
Right. I guess I'm not familiar enough with the internals of Jupyter to know anything around how they render. Could be a bug with Jupyter itself if they only support a subset of the svg spec (just making this up, I assume since this is running in the browser all of the svg spec is fair game)

**Comment by paddymul** [comment] 2024-11-10 20:35
Yep.  I'm just keeping a log of approaches I have tried.

**Comment by paddymul** [comment] 2024-11-11 01:00
I think it's due to duplicate pattern IDs.
I have a relatively limitted jupyter notebook that just has inline SVGs which reproduces the bug.

I have a theory for what is happening.  The first time the patterns with the ids are defined in the dom, those are the elements that are referenced.
When that svg block scrolls out of view, the patterns are no longer available.  and the fill goes away.

Sadly you can't use classnames on patterns.  So I have to generate unique fill names on each chart.

This is not a recharts bug, but a general SVG bug.  I still can't figure out how to reproduce this outside of Jupyter.

**Comment by ckifer** [comment] 2024-11-11 01:35
Weird but makes sense. Although why would they get removed from the dom at all? Even on scroll they should just be there? Unless Jupyter does some lazy loading or something

**Comment by paddymul** [comment] 2024-11-11 14:47
I can stop commenting here if you want, just say the word.  

I created a gist with injected SVGs and a shared definition section (no redefinition of duplicate IDs).  This does the showing/hiding of patterns on scroll when executed dynamically, however, when rendered into a static HTML file (as the example links too), Everything stays rendered properly.

https://gist.github.com/paddymul/8ecf0251f74a5ab1813971fc46b612a9

**Comment by ckifer** [comment] 2024-11-11 15:02
Huh, interesting. I'm going to close this, if you find anything pertinent to recharts please still post it here and I'll get a notification for it. 

Thanks!!! And nice deep dive

**Closed** 2024-11-11 15:40 UTC

**Comment by paddymul** [comment] 2024-11-11 17:23
My fix FWIW
