### ISSUE TITLE
[bug]can not open http://recharts.org/en-US/api/Customized

### ISSUE THREAD

**Issue by p2227** [recharts/recharts#1776] opened 2019-06-17 13:23 UTC
## Do you want to request a feature or report a bug?
report a bug
## What is the current behavior?
can not open this web page  http://recharts.org/en-US/api/Customized

## What is the expected behavior?
can open

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
![image](https://user-images.githubusercontent.com/4214942/59607475-f9ba0700-9145-11e9-95c6-3d4d4c323722.png)

**Comment by PabloSzx** [comment] 2019-06-29 02:05
no workaround? no answer whatsoever?

**Comment by sainthkh** [comment] 2019-10-17 00:35
Closed because it's a duplicate of #1802.

**Closed by sainthkh** 2019-10-17 00:35 UTC
