### ISSUE TITLE
-90 degree Y-Axis Label is overlapped by long tick labels on y-axis

### ISSUE THREAD

**Issue by HerrPfister** [recharts/recharts#4862] opened 2024-08-07 15:06 UTC
## Do you want to request a feature or report a bug? 

Bug

## What is the current behavior? 

Adding a y-axis label to my line chart rotated -90 degrees isn't positioned correctly in relation to the ticks on the axis. When the labels for those ticks get large, they overlap the label, instead of pushing the label.

<img width="135" alt="Screenshot 2024-08-07 at 9 57 03 AM" src="https://github.com/user-attachments/assets/547500f1-f8f5-4576-84f5-9eb8cb6d6695">

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).

1. Create a line chart
2. Create a y axis component and add it to the chart
3. Create a y axis label like so `<Label  style={{ textAnchor: 'middle' }} angle={-90} position="insideLeft" value="some y axis label" /> ` then add it to the y axis
4. Create some data with a really long y-axis tick label

## What is the expected behavior?

When data is loaded into the chart if the y-axis tick labels that are generated overlap the y axis label then it should push the y axis label so it isn't overlappign

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts v2.12.1, Chrome v126.0.6478.127

**Comment by ckifer** [comment] 2024-08-07 15:21
Hi, this isn't a bug but just an unimplemented feature (labels have never adjusted axis display). You can try adjusting the width of your Y Axis to work around it for now

**Comment by ckifer** [comment] 2024-08-08 01:13
Lot of workarounds here https://github.com/recharts/recharts/issues/782#issuecomment-331203175

**Comment by ckifer** [comment] 2024-10-28 23:12
Going to close this. At the moment this is intentional and not a bug

**Closed by ckifer** 2024-10-28 23:12 UTC
Labels: pending response
