### ISSUE TITLE
Error: <rect> attribute height: A negative value is not valid.

### ISSUE THREAD

**Issue by talk2rajeev** [recharts/recharts#1462] opened 2018-09-04 03:51 UTC
## chart height is set to negative

* when i use axios to get data from my NODE chart-api, Re-Chart is not displaying properly. it throws an error 
`"Error: <rect> attribute height: A negative value is not valid."`

* when i remove axios and use hardcoded data, chart is rendering properly.
below is my code
`
comnponentDidMount(){
  axios.get(url).then(res=>{ this.setstate({data: res.data}) })
}
render(){
return !this.state.data.length ? "Loading" : (
<ComposedChart width={600} height={300} data={data} margin={{top: 20, right: 20, bottom: 0, left: 20}}>
            <CartesianGrid stroke='#fafafa'/>
            <XAxis dataKey="month"/>
            <YAxis />
            <Tooltip />
            <Legend />
            <Bar dataKey='sellin' barSize={20} fill='#ec1b25' label={{ position: 'top', fill: '#ec1b25', fontSize: '10px' }}/>
            <Bar dataKey='sellout' barSize={20} fill='#fbce06' label={{ position: 'top', fill: '#fbce06', fontSize: '10px' }}/>
            <Line type='monotone' dataKey='target' stroke='#ff7300' />
        </ComposedChart>
)
}
`

**Comment by natasha-robarge** [comment] 2019-04-12 01:20
I'm having this issue as well - have you found a fix for this?

**Comment by joshuagish** [comment] 2019-04-19 19:11
I'm having the same issue but for <rect> width on the bar chart.

When the browser is resized, recharts updates the width of the bars to fill space. The issue is once it shrinks past a certain width, recharts starts inputting negative values.

**Comment by mzzfederico** [comment] 2020-03-13 21:14
This is still an issue as of 2.0.0.beta-3

**Comment by xile611** [comment] 2020-03-17 07:30
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Closed by xile611** 2020-03-17 07:30 UTC

**Comment by msabaeian** [comment] 2020-03-31 20:41
try to put your rechart chart inside a ResponsiveContainer and don't forgot to set its width and height
like:
```
import {
    ResponsiveContainer,
} from 'recharts';

<ResponsiveContainer width="100%" height={400}>
    <PieChart>
        <Pie
            data={pieChart}
            innerRadius={60}
            fill="#8884d8"
            paddingAngle={5}
            dataKey="value">
        {pieChart.map((entry, index) => <Cell key={`cell-${index}`} fill={entry.color} />)}
        </Pie>
        <Legend />
        <Tooltip />
    </PieChart>
</ResponsiveContainer>
```

I had this issue and fixed with ResponsiveContainer

**Comment by sgtkuncoro** [comment] 2020-12-08 13:19
> I had this issue and fixed with ResponsiveContainer

got the same issue, and this still doesn't work in my case, the error log still occurred

**Comment by report-zone** [comment] 2020-12-26 04:07
> I had this issue and fixed with ResponsiveContainer

n start

**Comment by report-zone** [comment] 2020-12-26 04:07
I seems to get into this particular scenario only when using a Brush and multiple bars.

**Comment by marnixhoh** [comment] 2021-01-16 17:11
I am also still experiencing this issue using Recharts: 2.0.3. It doesn't appear to be influencing layout though (or anything else for that matter)...

**Comment by sumitWebDev** [comment] 2022-05-20 07:55
I am using rechart 2.1.10 and facing the same issue. Try to add a wrapper around the charts and add a height with vh unit for eg: height: 41vh;

This resolved my issue

**Comment by ashrth** [comment] 2023-06-01 16:30
I removed my ResponsiveContainer and it worked
