### ISSUE TITLE
Prop types warning on allowEscapeViewBox

### ISSUE THREAD

**Issue by harsohailB** [recharts/recharts#2938] opened 2022-08-12 17:47 UTC
Recharts: "^1.7.1"

Warning:
```
Warning: Failed prop type: Tooltip: prop type `allowEscapeViewBox.x` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
    in Tooltip (created by LineChart)
    in LineChart (created by LineChart)
```

Code:
```jsx
<RechartLineChart
  cartesianGridProps={null}
  data={[
    {
      date: 'March 1',
      rate: 20
    },
    {
      date: 'March 2',
      rate: 25
    },
    {
      date: 'March 3',
      rate: 15
    },
    {
      date: 'March 4',
      rate: 45
    },
    {
      date: 'March 5',
      rate: 10
    }
  ]}
  dataMapping={[
    {
      color: '#596060',
      key: 'rate'
    }
  ]}
  height={300}
  referenceLineProps={{
    stroke: '#FF9240',
    strokeDasharray: '5 5',
    strokeWidth: 2,
    y: 35
  }}
  strokeWidth={2}
  unit="%"
  width="100%"
  xAxisProps={{
    dataKey: 'date'
  }}
  yAxisProps={{
    tickFormatter: () => {}
  }}
/>
```

**Comment by KarthikeyanM28** [comment] 2022-09-14 11:04
Failed prop type: Tooltip: prop type `allowEscapeViewBox.x` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`
` Tooltip (webpack-internal:///./node_modules/recharts/es6/component/Tooltip.js:172:5)`

Failed prop type: Line: prop type `points[0].value` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

`CategoricalChartWrapper (webpack-internal:///./node_modules/recharts/es6/chart/generateCategoricalChart.js:142:7)`

how to fix this?

**Comment by brightmileDaniel** [comment] 2022-11-09 14:27
+1

**Comment by danvc** [comment] 2022-11-11 15:16
Facing the same issue.. I've been trying to inject the property as function or even as object with certain attributes... it didn't work so far

**Comment by ckifer** [comment] 2023-01-02 04:43
The above looks like a custom component, I cannot reproduce with the `allowEscapeViewBox` property on `Tooltip`.

I think this was fixed with the move to TypeScript, please upgrade to the latest recharts to resolve this issue. Feel free to comment back if this is not resolved and I will re-open but closing as completed for now.

**Closed by ckifer** 2023-01-02 04:43 UTC

**Comment by VidyullathaKandipati** [comment] 2023-06-06 01:25
I am still facing this issue even with the basic in built <Tooltip /> , but I could not reproduce in code sandbox.

**Comment by ckifer** [comment] 2023-06-06 01:41
Please upgrade to the latest recharts version if you can, 1.x isn't being supported

**Comment by VidyullathaKandipati** [comment] 2023-06-06 01:49
Thank you I will upgrade and try now

**Comment by VidyullathaKandipati** [comment] 2023-06-06 02:05
Upgrading recharts to latest version helped. Thanks @ckifer
