### ISSUE TITLE
ErrorBar inside LineChart or ComposedChart with multiple data sources overrides the yAxis domain attribute.

### ISSUE THREAD

**Issue by hunderi** [recharts/recharts#2851] opened 2022-05-10 22:37 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-fewks2?file=/src/index.js)

### Steps to reproduce
1. Create a yAxis component in a LineChart or ComposedChart and set the yaxis domain property to for instance [1000,10000] (important that the domain range start is more than 0).
2. Create two data arrays, one with both values and error values and one with just values. 
3. Create two line objects and set the data attribute to one of the two data arrays from step 2.
4. Create an ErrorBar inside the line element that uses the data that also has error value keys. 
The y-axis is no longer spanning from dataMin but from some lower value (0 or a negative number, depending on the size of the error data  key). It seems to override the yAxis component's domain property entirely.

### What is expected?
The error bar should be shown for the value points without the y-axis domain changing.

### What is actually happening?
The error bar is shown, but the graph is shifted so that the min value of the axis is 0 or at least less than dataMin.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | ^16.13.1 |
| System | Windows 10 |
| Browser | Edge |

---
This bug seems to have been created when going from 1.8.4 to 1.8.5. The issue does not look like it happens for version 1.8.4 (It also seems to work for 1.8.3, 1.8.2 and 1.8.1).

**Comment by hunderi** [comment] 2022-05-29 12:35
Anyone have a chance to look at this issue?

**Comment by lukask-proxora** [comment] 2022-06-05 16:15
From looking at the code, it looks like the problem is the calculation of the error bar domain.
This searches for the lowest/largest point to draw including the error bars.
- It first determines all error bars that should be considered - in your case that's the only one error bar.
- It then calculates for every data point the value plus the error value and the value minus the error value. However, it does not distinguish between your two data sets. That means it's searching for a field named `hValue` in your first data set and takes 0 as a default value if that field does not exist.
- In the end it takes the lowest and highest of the calculated values as the domain. Since 0 is lower than the single point of your second data set minus the error value, 0 is the lower bound of the domain.

So it seems like this logic assumes that all lines in a line chart use a shared data set, or at least data sets with the same fields. If you add a field `hValue` to every object in your first data set with the same value as the `pv` value, the problem disappears. 

In general, I'm not sure if the use of different data sets in one chart is supported by recharts. In the docs, there is no `data` property for the `Line` component, just for the `LineChart` component.

**Comment by ckifer** [comment] 2024-11-26 23:41
This no longer happens in the latest. Resolving

**Closed by ckifer** 2024-11-26 23:41 UTC
