### ISSUE TITLE
Recharts 2.13.0-alpha.4 - Encountered two children with the same key

### ISSUE THREAD

**Issue by jzombie** [recharts/recharts#4858] opened 2024-08-06 21:58 UTC
## What is the current behavior?

Experiencing a "Warning: Encountered two children with the same key" error when using the `PieChart` / `Pie` combination, that I wasn't previously experiencing on the non-alpha version.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).

![Screenshot 2024-08-06 at 3 53 28 PM](https://github.com/user-attachments/assets/6de8d9cd-680f-4dc5-8766-eab67a4cccb9)

```ts
import React from "react";

import {
  Cell,
  LabelList,
  Pie,
  PieChart,
  PieLabelRenderProps,
  ResponsiveContainer,
  Tooltip,
} from "recharts";

import useStoreStateReader from "@hooks/useStoreStateReader";

import formatByteSize from "@utils/formatByteSize";

// TODO: Centralize somewhere else
const COLORS = ["#8884d8", "#82ca9d", "#ffc658", "#ff8042", "#00C49F"];

// Define a type for the data entries
interface CacheDetail {
  key: string;
  size: number;
}

// Define a type for the props used in the customized label
interface CustomizedLabelProps extends PieLabelRenderProps {
  cx: number;
  cy: number;
  midAngle: number;
  innerRadius: number;
  outerRadius: number;
  percent: number;
  index: number;
  payload: CacheDetail;
}

const renderCustomizedLabel = (props: CustomizedLabelProps) => {
  const { cx, cy, midAngle, innerRadius, outerRadius, percent, payload } =
    props;
  const RADIAN = Math.PI / 180;
  const radius = 25 + innerRadius + (outerRadius - innerRadius);
  const x = cx + radius * Math.cos(-midAngle * RADIAN);
  const y = cy + radius * Math.sin(-midAngle * RADIAN);

  // Show label if space allows
  const isSpaceAvailable = percent > 0.05; // Adjust this threshold as needed

  if (isSpaceAvailable) {
    return (
      <text
        x={x}
        y={y}
        fill="white"
        textAnchor={x > cx ? "start" : "end"}
        dominantBaseline="central"
      >
        {`${payload.key}: ${formatByteSize(payload.size)}`}
      </text>
    );
  }
  return null;
};

export default function CachePieChart() {
  const { cacheDetails } = useStoreStateReader("cacheDetails");

  // Provide a default value if cacheDetails is undefined
  const data: CacheDetail[] = cacheDetails || [];

  return (
    <ResponsiveContainer height={300}>
      <PieChart>
        <Pie
          data={data}
          dataKey="size"
          nameKey="key"
          cx="50%"
          cy="50%"
          outerRadius={100}
          fill="#8884d8"
          label={renderCustomizedLabel}
        >
          <LabelList
            dataKey="size"
            // @ts-expect-error FIXME: Having a hard time debugging this type
            content={renderCustomizedLabel}
          />
          {data.map((entry, index) => (
            <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
          ))}
        </Pie>
        <Tooltip
          formatter={(value, name) => [
            `${formatByteSize(value as number)}`,
            name,
          ]}
        />
      </PieChart>
    </ResponsiveContainer>
  );
}

```

## What is the expected behavior?

Not expected to get the warning.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts `2.13.0-alpha.4`.  Chrome 127.0.6533.89 (Official Build) (arm64) Mac Ventura 13.6.7.

**Comment by ckifer** [comment] 2024-08-06 22:06
Do you not get the error on 2.12.7? We haven't done anything on the alpha version that changes keys.

**Comment by jzombie** [comment] 2024-08-06 22:16
> Do you not get the error on 2.12.7? We haven't done anything on the alpha version that changes keys.

No, I wasn't getting the error on 2.12.7.  I rolled back and compared with the same code.

**Comment by ckifer** [comment] 2024-08-06 22:20
Could you make a code sandbox that reproduces the issue?

**Comment by jzombie** [comment] 2024-08-06 22:21
> Could you make a code sandbox that reproduces the issue?

Yep, I'm making one now.

**Comment by jzombie** [comment] 2024-08-06 22:32
@ckifer   Here's the sandbox:  https://codesandbox.io/p/devbox/j8sjsj

![Screenshot 2024-08-06 at 4 32 01 PM](https://github.com/user-attachments/assets/99a5ed03-5aea-4132-9e2e-1684cc987451)

**Comment by ckifer** [comment] 2024-08-08 01:10
Hi

This is because "key" is a reserved property in react. You cannot name your "nameKey" as "key". Changing your "nameKey" to something like "name" resolves the issue

**Comment by ckifer** [comment] 2024-08-08 01:11
But these props shouldn't be getting spread on the elements at all, so a bug it is

**Comment by jzombie** [comment] 2024-08-08 01:22
@ckifer Thanks for the feedback here, pointing out the issue, and letting me know how to work around it.

**Comment by ckifer** [comment] 2024-08-08 01:25
Sure thing

**Comment by ckifer** [comment] 2024-09-03 18:42
Update: I don't think this is an alpha version issue, I can reproduce in any 2.x version

**Comment by ckifer** [comment] 2024-09-05 17:33
Fixed in alpha version
https://www.npmjs.com/package/recharts/v/2.13.0-alpha.5

Still would recommend not using `key` as a dataKey

**Closed by ckifer** 2024-09-05 17:33 UTC
Labels: bug
