### ISSUE TITLE
How can I increase the size of the pie chart

### ISSUE THREAD

**Issue by margaiwangara** [recharts/recharts#2965] opened 2022-09-13 12:47 UTC
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

I've tried increasing the width and height but I can't increase the size of the pie chart

**Comment by ckifer** [comment] 2022-12-29 17:52
Hi @margaiwangara 

Can you give a reproduction/example if this is still a issue? Generally increasing the height/width should do it.

**Comment by ckifer** [comment] 2023-06-20 05:13
Going to close this since there hasn't been a response in about 1/2 a year and it is a question rather than an issue

**Closed by ckifer** 2023-06-20 05:13 UTC
Labels: pending response
