### ISSUE TITLE
Next.js 15 Support

### ISSUE THREAD

**Issue by xdajay** [recharts/recharts#5146] opened 2024-10-23 04:11 UTC
Since Next.js 15 stable release is out, it would be great to have support for it. I tried with the latest version of Recharts, but nothing is getting rendered on Next.js 15 stable release. I also tried with react-is.

**Comment by ckifer** [comment] 2024-10-23 04:27
Support for a specific framework is not guaranteed. 

But React 19 is not stable even if Next 15 supposedly is, so if anything we need to wait for R19 release. Make a reproduction and I'll try to get it to work.

**Comment by xdajay** [comment] 2024-10-23 04:52
@ckifer Thanks, will add reproduction, errors shortly with fresh next 15 project.

**Comment by Rikard-Johansson97** [comment] 2024-10-23 11:56
> @ckifer Thanks, will add reproduction, errors shortly with fresh next 15 project.

I had to manually set the width and height for my bar chart to make it visible. However, I’m struggling to get it to work with a responsive container.

**Comment by ckifer** [comment] 2024-10-23 12:03
@Rikard-Johansson97 are you rendering the chart on the server?

**Comment by songkeys** [comment] 2024-10-23 12:31
I have exactly the same issue. I am using  `@mantine/recharts` that wraps `recharts`.

But when I try to reproduce it in a minimum demo by copying the responsive demo from recharts website, it works good. I think it's due to an unexpected usage in our code. But I couldn't spot it out now. Could you please help share your MRD so that we can debug quickly @Rikard-Johansson97 ? Here's mine: https://github.com/songkeys/next15-recharts-repro

**Comment by ckifer** [comment] 2024-10-23 12:37
Next 15 is React 19 right? You have to override your react-is version

**Comment by ckifer** [comment] 2024-10-23 12:37
https://github.com/recharts/recharts/issues/4558

**Comment by ckifer** [comment] 2024-10-23 12:46
This will be more clear in 3.0 because we'll be able to add react-is as a peer dependency but this is also mentioned in the 2.13 release notes

**Comment by xdajay** [comment] 2024-10-23 14:39
@ckifer Did a fresh install of next 15,  Recharts does not work out of the box.
This did the trick + clearing  package cache is required. Works with shadcn too.
 
```
  "pnpm": {
    "overrides": {
      "react-is": "19.0.0-rc-45804af1-20241021"
    }
  }
```

**Comment by ckifer** [comment] 2024-10-23 14:44
Yep that's expected and called out in the most recent release notes 👍. We can't help it because R19 made a breaking change where those versions have to match your react version. When 3.0 comes out we will either remove its use or make it a peerDependency

**Comment by ckifer** [comment] 2024-10-23 14:44
I'm going to close this as resolved

**Closed by ckifer** 2024-10-23 14:44 UTC

**Comment by pradel** [comment] 2024-10-26 07:51
I am still having this issue with react 18.3.1 and next 15 in 2 monorepos (one is [public](https://github.com/pradel/stackspulse/pull/146)), tried both pnpm approach but none is working
```
"pnpm": {
    "overrides": {
      "react-is": "18.3.1"
    }
  }
```
and this to mimic the next major release where it's added as a peerDeps
```
"pnpm": {
    "packageExtensions": {
      "recharts": {
        "peerDependencies": {
          "react-is": "^18"
        }
      }
    }
  }
```

@ckifer any idea what could be wrong there?

**Comment by ckifer** [comment] 2024-10-26 08:47
There should be no issue with React 18

**Comment by pradel** [comment] 2024-10-26 08:48
@ckifer no idea but that could be the issue tho

**Comment by ckifer** [comment] 2024-10-26 08:55
As far as I know your react-is version has to exactly match your react version. So I'd start listing out what react version you actually have installed. I can't help much more than that right now but I'll check back in a few days.

**Comment by pradel** [comment] 2024-10-26 08:59
@ckifer sounds good thanks, had a look and just have one react version in my pnpm lockfile

**Comment by Rikard-Johansson97** [comment] 2024-10-26 11:47
> @ckifer sounds good thanks, had a look and just have one react version in my pnpm lockfile

I Added pnpm override in the root package.json in my monorepo and it works.

**Comment by pradel** [comment] 2024-10-26 12:15
> I Added pnpm override in the root package.json in my monorepo and it works.

yup the override was in the root package.json but not working unfortunately

**Comment by mgandolfi7** [comment] 2024-10-26 14:38
Do I need to use the --force or --legacy-peer-deps flag or is   "overrides": {
    "react-is": "19.0.0-rc-45804af1-20241021" 
  } 
  
  sufficient?

**Comment by ckifer** [comment] 2024-10-26 14:42
If you are installing with react 19 you'll probably need to use legacy peer deps anyways because recharts can't add R19 to peerDeps until it's actually released. So worth a shot but if it's not failing to install then that's probably not the issue

**Comment by mgandolfi7** [comment] 2024-10-26 14:51
Thanks for the prompt reply @ckifer. Got it to work with --legacy-peer-deps.

**Comment by mgandolfi7** [comment] 2024-10-26 16:04
I switched to pnpm from npm and got it to work without flags.

**Comment by ckifer** [comment] 2024-10-28 18:19
@pradel are you still having issues or are you good? Looks like everyone else in the thread is good. Lmk if not

**Comment by pradel** [comment] 2024-10-28 20:46
@ckifer still having the issue on both projects, tried to upgrade to next 15.0.1 but it's not helping

**Comment by ckifer** [comment] 2024-10-28 20:47
Ok I'll take a look at the public one

**Comment by ckifer** [comment] 2024-10-28 21:15
@pradel can you update your README to be more clear? I can't get the project started without an unreasonable amount of effort

**Comment by pradel** [comment] 2024-10-29 09:28
@ckifer I updated the next.js upgrade branch to make it easy to view the problem.

To reproduce:
1. clone the repo
2. checkout the `feat/next-15` branch
3. pnpm i
4. pnpm turbo build --filter=@stackspulse/protocols
5. pnpm dev
6. navigate to http://localhost:3000/protocols/alex and see the empty graph

**Comment by DominicYonce22** [comment] 2024-10-30 09:24
@pradel I have the same issue as you and also tried what you did. Changing the versions and even overriding react-is does not really do anything. My react is also version 18 and not 19. Have you found the fix yet??

**Comment by DominicYonce22** [comment] 2024-10-30 09:57
![Screenshot 2024-10-30 175441](https://github.co
![Screenshot 2024-10-30 175615](https://github.com/user-attachments/assets/1ed94500-60c1-4170-a762-28fecc59ea18)
m/user-attachments/assets/e1bac607-a5d9-47f9-ab2b-7fcc21cb7141)
![Screenshot 2024-10-30 175543](https://github.com/user-attachments/assets/85aeeed4-94f6-4c16-9ccd-e9a3f00ca3d2)

**Comment by DominicYonce22** [comment] 2024-10-30 09:59
![Screenshot 2024-10-30 175441](https://github.com/user-attachments/assets/d9d1a1af-5be5-4043-a76c-caeb36b9476b)
![Screenshot 2024-10-30 175543](https://github.com/user-attachments/assets/a8de8172-8e79-4365-8eda-44537de9cc7f)
![Screenshot 2024-10-30 175615](https://github.com/user-attachments/assets/cf3ca465-e8f8-4491-b814-44107d70f49f)

**Comment by DominicYonce22** [comment] 2024-10-30 10:09
Downgrading next 15 to 14.2 solved the issue for me. Now the charts work fine without the width and height inside responsive container

**Comment by ckifer** [comment] 2024-10-30 11:20
Next 15 uses React 19 so it doesn't matter if you are trying to use R19 or not, it Next will use it for you. So your react-is version need to match your react version. Easy to confirm that by "npm ls react-is"

**Comment by Gabriel-Passoss** [comment] 2024-10-30 15:25
I'm trying to manually set the react-is dependency of recharts to 19.0.0-rc-0bc30748-20241028 but he refuses to use that version

![image](https://github.com/user-attachments/assets/9281163f-3a72-42ea-9ca1-e70acb67b1ec)

I don't know if it has anything to do with me using npm workspaces with turborepo

![image](https://github.com/user-attachments/assets/f5129e90-9322-485b-bd32-9e6a6828ee1b)

**Comment by ckifer** [comment] 2024-10-30 15:29
You'll have to install with legacy-peer-deps. 

It also looks like you npm ls doesn't say overridden. So your override is not taking effect correctly for whatever reason. Make sure all syntax is correct and that if you are using a different package manager other than npm you have the correct method of specifying overrides.

**Comment by Gabriel-Passoss** [comment] 2024-10-30 16:03
Get using a library to force the update of this subdependency. In case it helps anyone, this material helped me solve it:
https://www.geeksforgeeks.org/how-to-override-nested-npm-dependency-versions/

**Comment by ckifer** [comment] 2024-10-30 17:09
Glad you got it sorted out. Once R19 is stable this will be less of a pain

**Comment by ckifer** [comment] 2024-10-31 13:33
Sorry @pradel I got distracted and forgot to check. I'll look at it today

**Comment by ckifer** [comment] 2024-10-31 15:11
@pradel it seems that `pnpm ls` is much less helpful than `npm ls` is. There were a bunch of older versions of `react-is` being installed.

I got this working with React 19, I couldn't get it with React 18
Add
```
  "pnpm": {
    "overrides": {
      "react": "19.0.0-rc-603e6108-20241029",
      "react-dom": "19.0.0-rc-603e6108-20241029",
      "react-is": "19.0.0-rc-603e6108-20241029"
    }
  },
```

To your workspace package.json file.
Set those same versions in your `web` project package.json file.

Run `pnpm store prune`

Start the project and see the graph.
<img width="806" alt="image" src="https://github.com/user-attachments/assets/7f2b1473-add9-4da7-8288-7777c6b2cbeb">

**Comment by ckifer** [comment] 2024-10-31 15:40
@eps1lon don't mean to summon you, but do you have any insight in to why the above would be an issue?

**Comment by pradel** [comment] 2024-11-01 08:54
@ckifer thanks for taking a look. I can't migrate to react 19 for now as we have multiple versions of react in our monorepo and can't migrate the old apps. My understanding of the issue is that react-is can't detect that it's a valid element and return false? Maybe I can work around by patching the function and use smth like React.isValidElement? Or can you think of another workaround that could be applied (I will modify the package with pnpm patch on my repo)

**Comment by ckifer** [comment] 2024-11-01 11:41
I would just comment the check out and perch it that way, it shouldn't have that large of an effect

**Comment by eps1lon** [comment] 2024-11-01 15:51
No idea why this is happening. I'd need a repro to dig further.

**Comment by ckifer** [comment] 2024-11-01 15:54
Cool, appreciate the reply. I'll see if I can repro in a new project

**Comment by ckifer** [comment] 2024-11-01 16:08
@eps1lon reproduced [here] - react versions shown here (https://github.com/ckifer/recharts-next15-r18-repro/) https://github.com/ckifer/recharts-next15-r18-repro/blob/main/package.json#L12-L20

This works if you change all the R18 references to the latest R19 RC

I added a `patch-package` which logs the return of `isElement` as false in R18

**Comment by ckifer** [comment] 2024-11-01 19:27
@pradel try 2.13.3, I changed the `isElement` check from `react-is` to `React.isValidElement` which seems to work fine in React 18/Next.

Still seems to be an issue in general with `react-is` working in Next 15 with `react-is`/`react` < 19 but that isn't on recharts.

The only other thing that relies on `react-is` is a check using `isFragment` (issue reference https://github.com/recharts/recharts/issues/2462). As long as you avoid fragments in your direct chart children you should be ok.

**Comment by lucasassisrosa** [comment] 2025-03-28 01:38
@ckifer thanks

since I'm also using fragments in my charts children, I had to override react-is to point to react 19 for it to work: https://github.com/recharts/recharts/issues/2462#issuecomment-2715233201

```
  "dependencies": {
    "react-is": "19.0.0",
  },
  "overrides": {
    "react-is": "19.0.0",
  }
```
