### ISSUE TITLE
ComposedChart missing unique "key" prop

### ISSUE THREAD

**Issue by patryk0605** [recharts/recharts#322] opened 2016-11-04 18:28 UTC
Within my console, I noticed the following message after latest update: 

```
Each child in an array or iterator should have a unique "key" prop. Check the render method of `ComposedChart`. See https://fb.me/react-warning-keys for more information.
    in AnimationDecorator(ComposedDataDecorator(BarChart)) (created by ComposedChart)
    in ComposedChart (created by ComposedDataDecorator(ComposedChart))
    in ComposedDataDecorator(ComposedChart) (created by ComposedDataDecorator(ComposedChart))
    in svg (created by Surface)
    in Surface (created by ComposedDataDecorator(ComposedChart))
    in div (created by ComposedDataDecorator(ComposedChart))
    ...
```

After reviewing the changes made, I believe the following is what is triggering the error: 

https://github.com/recharts/recharts/commit/5860c457d87f93a6be0dd002b25cb274073ab17f#diff-82345e535b9ce2e7ebed868402aee7ceR110

I recommend setting a unique key to suppress the warning.

**Comment by xile611** [comment] 2016-11-07 08:55
@patryk0605 Thanks! It'll be fixed soon.

**Comment by xile611** [comment] 2016-11-08 13:20
Fixed in version 0.17.1.

**Closed by xile611** 2016-11-08 13:20 UTC
Labels: bug

**Comment by nick-barth** [comment] 2016-11-16 15:07
Running version 18.0 still receiving this warning, on Area chart.  Quick workaround is assigning keys based on Math.Random(), or from the first parameter, but I'd much rather not.

**Comment by xile611** [comment] 2016-11-17 05:59
@nick-barth Can you create a jsfiddle demo ? I can't reproduce this warning.
