### ISSUE TITLE
Animation rendering fails into Pie Chart.

### ISSUE THREAD

**Issue by lcustodio** [recharts/recharts#1083] opened 2017-12-13 09:31 UTC
## Do you want to request a feature or report a bug?

I would like to report a bug.
Animation rendering fails into Pie Chart, there is space for improvement on the fallback.

## What is the current behavior?

There is an intermittent failure on the chart rendering. As exposed on the gif below:

1. The first rendering works nicely as expected.
2. The second rendering (page reload) is intercepted somehow and a default rendering takes place removing the animation and the legend information.

![out2](https://user-images.githubusercontent.com/585672/33879490-d8458844-df2e-11e7-93c8-dcf245849fa7.gif)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

http://jsfiddle.net/lcustodio/x5x1de34/

## What is the expected behavior?

The animation to always work, and if some error happens fallback like it's the case currently, but the `label` and `labelLine` function should be called as well.
In addition, some error logging in order to understand and try to solve the problem.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

All the tests were made with Chrome 62 + macOS 10.13.1

**Comment by ptdede** [comment] 2018-06-10 20:00
I also facing the same issue. Exactly after facing data from internet using 'redux-saga', the animation stop immediately. I think it's because react triggered re-render after props changed. But, when using 'LineChart' the animation works perfectly.

@lcustodio did you find how to handle this already?

**Comment by squierts** [comment] 2018-06-21 16:57
For me the Line Chart has the same problem and is resolved by turning off animations.

**Comment by AlexMiroshnikov** [comment] 2018-07-30 06:13
Regarding the original (PieChart) problem - the reason is that `src/polar/Pie.js`::`handleAnimationEnd()` is not being called in case there is more than one pie chart on the page, meaning this component never gets state `isAnimationFinished:true`, which leads the labels not to appear.

**Comment by lcustodio** [comment] 2018-09-11 11:10
@ptdede we removed the animation.
Did you manage to try @AlexMiroshnikov's suggestion?

**Comment by KalvinHom** [comment] 2018-11-20 19:41
Ran into the same issue, and had to disable animation to get labels to show on initial render.  I am also using two piecharts in one page, which sounds like is the cause of the bug.

**Comment by xile611** [comment] 2019-02-12 03:17
@KalvinHom Any demo to reproduce this problem ?

**Comment by eglenfield** [comment] 2019-02-14 11:34
@xile611 

![donut_behaviour_gif](https://user-images.githubusercontent.com/13347714/52784245-57c9c700-304c-11e9-9ec3-9bd2c086ab5e.gif)

(You should see the graph render three times, it's a long gif)
- In the first instance the state of the donuts is cached, so we see the two donuts rerender smoothly. 
- The end of the gif shows the donuts suddenly rendering without animation, and this is after the cache has been removed, so we've had to fetch the data again and set state.

**Comment by loopbender** [comment] 2019-03-21 12:23
I ran into a similar issue too, and spent 5 hours to resolve it so I'll try to help any future readers too. 

@AlexMiroshnikov's answer was really helpful and guided me to solution, so thx for that.

- For animation to be truly rendered, `renderSectorsWithAnimation` actually have to be called many times. The problem is that `renderSectorsStatically` is being called somehow when animation is already started with first `renderSectorsWithAnimation`and cancels all other `renderSectorsWithAnimation` calls and causes the fail of animation. I think this part is common in all of our problems.

- So in my situation, I was using the brand new React Hooks for the `PieChart` component and therefore had to use inline arrow functions for `onMouseEnter` props of `<Pie>` component:
```
    const [activeIndex, setActiveIndex] = useState(-1),

    <Pie
        isAnimationActive={true}
        activeIndex={activeIndex}
        activeShape={renderActiveShape}
        dataKey="duration"
        data={data}
        onMouseEnter={()=> setActiveIndex(i)}>
```

And using this inline arrow function was causing a re-render on the component when data is not actually changed and it triggers a call to `renderSectorsStatically`. To avoid any confusion, it is not the onMouseEnter function that causes `renderSectorsStatically`, just the fact that there is an inline arrow function causes an unneccesary re-render. You can google on this one.

So I don't know if you are using any inline arrow functions or not, but try to find what triggers `renderSectorsStatically` call in your situation and get rid of that. Maybe providing a different prop than data to your chart component is causing a re-render?

I hope these tips help someone.

and huge thanks for the amazing library @xile611

**Comment by guvengorgun** [comment] 2019-09-25 15:30
> 
> 
> I ran into a similar issue too, and spent 5 hours to resolve it so I'll try to help any future readers too.
> 
> @AlexMiroshnikov's answer was really helpful and guided me to solution, so thx for that.
> 
>     * For animation to be truly rendered, `renderSectorsWithAnimation` actually have to be called many times. The problem is that `renderSectorsStatically` is being called somehow when animation is already started with first `renderSectorsWithAnimation`and cancels all other `renderSectorsWithAnimation` calls and causes the fail of animation. I think this part is common in all of our problems.
> 
>     * So in my situation, I was using the brand new React Hooks for the `PieChart` component and therefore had to use inline arrow functions for `onMouseEnter` props of `<Pie>` component:
> 
> 
> ```
>     // FAILS ANIMATION
>     const [activeIndex, setActiveIndex] = useState(-1)
> 
>     <Pie
>         isAnimationActive={true}
>         activeIndex={activeIndex}
>         activeShape={renderActiveShape}
>         dataKey="duration"
>         data={data}
>         onMouseEnter={()=> setActiveIndex(i)}>
> ```
> 
> And using this inline arrow function was causing a re-render on the component when data is not actually changed and it triggers a call to `renderSectorsStatically`. To avoid any confusion, it is not the `onMouseEnter` callback that causes `renderSectorsStatically`, just the fact that there is an inline arrow function causes an unneccesary re-render. You can google on this one or try to dig into React Hooks API `useCallback` to memoize this inline arrow function to avoid unneccesary re-renders. I solved my problem by getting rid of the inline arrow functions, or using a useCallback (just trying to stick with the new Hook thing)
> 
> ```
>     // RENDERS WITH ANIMATION
>     const [activeIndex, setActiveIndex] = useState(-1),
>         onMouseEnter = useCallback((_, i) => setActiveIndex(i), []);
> 
>     <Pie
>         isAnimationActive={true}
>         activeIndex={activeIndex}
>         activeShape={renderActiveShape}
>         dataKey="duration"
>         data={data}
>         onMouseEnter={onMouseEnter}>
> ```
> 
> So I don't know if you are using any inline arrow functions or not, but try to find what triggers `renderSectorsStatically` call in your situation and get rid of that. Maybe providing a different prop than data to your chart component is causing a re-render?
> 
> I hope these tips help someone.
> 
> and huge thanks for the amazing library @xile611

I ran into the same issue with a similar configuration using React Hooks. After reading @loopbender s answer and understanding that re-render causes this problem, I just tried to making my hook component as a **PureComponent** using `React.memo(...)` then this resolved my issue. For example:

```
const ActiveShapePieChart = React.memo(props => {
    const [activeIndex, setActiveIndex] = useState(0);
    const onPieEnter = (data, index) => {
        setActiveIndex(index);
    };
    return (
            <PieChart width={width} height={height}>
                <Pie
                    ...
                </Pie>
            </PieChart>
     );
});
```

You can also see that all examples are implemented as a PureComponent on [Recharts ](http://recharts.org/en-US/examples) website. Hope this helps.

**Closed** 2020-03-13 06:06 UTC

**Comment by Mikowhy-owl** [comment] 2020-12-16 12:09
I don't understand why the problem is still not fixed by authors of this library but it is closed... ridiculous

**Comment by stanley-su** [comment] 2021-01-01 10:03
> > I ran into a similar issue too, and spent 5 hours to resolve it so I'll try to help any future readers too.
> > @AlexMiroshnikov's answer was really helpful and guided me to solution, so thx for that.
> > ```
> > * For animation to be truly rendered, `renderSectorsWithAnimation` actually have to be called many times. The problem is that `renderSectorsStatically` is being called somehow when animation is already started with first `renderSectorsWithAnimation`and cancels all other `renderSectorsWithAnimation` calls and causes the fail of animation. I think this part is common in all of our problems.
> > 
> > * So in my situation, I was using the brand new React Hooks for the `PieChart` component and therefore had to use inline arrow functions for `onMouseEnter` props of `<Pie>` component:
> > ```
> > 
> > 
> > ```
> >     // FAILS ANIMATION
> >     const [activeIndex, setActiveIndex] = useState(-1)
> > 
> >     <Pie
> >         isAnimationActive={true}
> >         activeIndex={activeIndex}
> >         activeShape={renderActiveShape}
> >         dataKey="duration"
> >         data={data}
> >         onMouseEnter={()=> setActiveIndex(i)}>
> > ```
> > 
> > 
> > And using this inline arrow function was causing a re-render on the component when data is not actually changed and it triggers a call to `renderSectorsStatically`. To avoid any confusion, it is not the `onMouseEnter` callback that causes `renderSectorsStatically`, just the fact that there is an inline arrow function causes an unneccesary re-render. You can google on this one or try to dig into React Hooks API `useCallback` to memoize this inline arrow function to avoid unneccesary re-renders. I solved my problem by getting rid of the inline arrow functions, or using a useCallback (just trying to stick with the new Hook thing)
> > ```
> >     // RENDERS WITH ANIMATION
> >     const [activeIndex, setActiveIndex] = useState(-1),
> >         onMouseEnter = useCallback((_, i) => setActiveIndex(i), []);
> > 
> >     <Pie
> >         isAnimationActive={true}
> >         activeIndex={activeIndex}
> >         activeShape={renderActiveShape}
> >         dataKey="duration"
> >         data={data}
> >         onMouseEnter={onMouseEnter}>
> > ```
> > 
> > 
> > So I don't know if you are using any inline arrow functions or not, but try to find what triggers `renderSectorsStatically` call in your situation and get rid of that. Maybe providing a different prop than data to your chart component is causing a re-render?
> > I hope these tips help someone.
> > and huge thanks for the amazing library @xile611
> 
> I ran into the same issue with a similar configuration using React Hooks. After reading @loopbender s answer and understanding that re-render causes this problem, I just tried to making my hook component as a **PureComponent** using `React.memo(...)` then this resolved my issue. For example:
> 
> ```
> const ActiveShapePieChart = React.memo(props => {
>     const [activeIndex, setActiveIndex] = useState(0);
>     const onPieEnter = (data, index) => {
>         setActiveIndex(index);
>     };
>     return (
>             <PieChart width={width} height={height}>
>                 <Pie
>                     ...
>                 </Pie>
>             </PieChart>
>      );
> });
> ```
> 
> You can also see that all examples are implemented as a PureComponent on [Recharts ](http://recharts.org/en-US/examples) website. Hope this helps.

Unfortunately didn't work for me.

**Comment by avindra** [comment] 2021-02-05 02:47
Related: https://github.com/recharts/react-smooth/issues/44

**Comment by CiroGomes** [comment] 2021-03-24 15:05
Hello guys! On #1624  issue, @klarstrup gave a solution that worked for me. Apparently this problem happens in other types of graphic too, as in my case, was using Bar.

The solution, proposed by @klarstrup, was to put a key prop on the BarChart component, so when it changes, the whole graphic will re-render, with all the animations. I just put key={Math.random()}, so he always renders now :)

**Comment by Harukisatoh** [comment] 2021-07-27 15:48
> Hello guys! On #1624 issue, @klarstrup gave a solution that worked for me. Apparently this problem happens in other types of graphic too, as in my case, was using Bar.
> 
> The solution, proposed by @klarstrup, was to put a key prop on the BarChart component, so when it changes, the whole graphic will re-render, with all the animations. I just put key={Math.random()}, so he always renders now :)

That second solution could be a problem if you trying to do an interactable pie chart, that's because every time onMouseEnter function gets called the whole chart is re-render triggering animations.

**Comment by j-jmnz** [comment] 2021-11-08 12:40
> Hello guys! On #1624 issue, @klarstrup gave a solution that worked for me. Apparently this problem happens in other types of graphic too, as in my case, was using Bar.
> 
> The solution, proposed by @klarstrup, was to put a key prop on the BarChart component, so when it changes, the whole graphic will re-render, with all the animations. I just put key={Math.random()}, so he always renders now :)

Worked for me, as my chart is not interactive 👍
