### ISSUE TITLE
Regression: horizontal bar chart with tooltip

### ISSUE THREAD

**Issue by ilteoood** [recharts/recharts#3990] opened 2023-11-23 09:40 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-9mffgj?file=/src/index.js)

### Steps to reproduce
With the cursor, hover on one of the bars
The background for that bar will turn to grey

### What is expected?
The same behavior of version 2.9.3: the tooltip is rendered when you hover the bar, without any additional background

### What is actually happening?
The background of a bar turns to grey

| Environment | Info |
|---|---|
| Recharts | v2.10.1 |
| React | 18.2.0 |
| System | OS X 13.6.2 |
| Browser | Chrome |

**Comment by makedatanotlore** [comment] 2023-11-23 14:37
Can confirm we are seeing the same errant behavior on a custom Tooltip component, showing a grey background where before there was none.

Likely related to this, we can no longer hover individual bars in our stacked bar chart.

It feels strange that a breaking change such as this was intended, especially when it wasn't part of a new major. It must be a bug?

**Comment by ckifer** [comment] 2023-11-23 15:29
Definitely not intentional. Probably a result of trying to fix a different bug. 

@HHongSeungWoo?

**Comment by HHongSeungWoo** [comment] 2023-11-24 10:06
It seems there was a small logical error during the process of removing lodash. Sorry about that! 😅

**Comment by ckifer** [comment] 2023-11-29 04:52
fixed in 2.10.2

**Closed by ckifer** 2023-11-29 04:52 UTC

**Comment by nbran** [comment] 2024-02-15 23:22
Seeing same issue with vertical bars in 2.12.0

In the clip below, as soon as the `active` prop for `<Tooltip />` is set to `true` all that's rendered is a gray background taking the full width of the X-axis position.

[Screencast from 02-15-2024 06:19:42 PM.webm](https://github.com/recharts/recharts/assets/25080013/500f8a5a-d92c-47ad-8376-414b3ad9a712)

**Comment by ckifer** [comment] 2024-02-15 23:37
that would be the cursor, could you try setting `cursor={false}` on your tooltip? If that doesn't fix the issue could you provide a codesandbox?

**Comment by ckifer** [comment] 2024-02-15 23:41
Still seems like it shouldn't be happening. @HHongSeungWoo do you mind taking a look at some point?

**Comment by HHongSeungWoo** [comment] 2024-02-16 02:57
@ckifer It seems normal for the cursor to be displayed when the TooltipEventType is 'axis'. 
Do you want this behavior to be modified?

**Comment by ckifer** [comment] 2024-02-16 02:58
The issue isn't the cursor displaying, it's that the bars are behind the cursor

**Comment by HHongSeungWoo** [comment] 2024-02-16 03:06
Ah, it seems to be an issue with the order in which the SVG is rendered. I will try adjusting the rendering order.
