### ISSUE TITLE
Render failure in Text component (Uncaught TypeError: Cannot read property 'map' of undefined)

### ISSUE THREAD

**Issue by domarp-j** [recharts/recharts#2388] opened 2021-01-13 00:02 UTC
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/alidingling/90v76x08/](https://jsfiddle.net/alidingling/90v76x08/)

### Steps to reproduce
Recreate the stacked bar chart example from the documentation (see JSFiddle link)

### What is expected?
The stacked bar chart documentation example should render.

### What is actually happening?
The stacked bar chart example is failing to render.

| Environment | Info |
|---|---|
| Recharts | v2.0.2 |
| React | v16.2 |
| System | N/A |
| Browser | Chrome v87.0.4280.88, Firefox v84.0.1 |

**Comment by ckifer** [comment] 2021-01-13 00:17
Duplicate of #2375 - this error is caused by JSFiddle. 
https://github.com/recharts/recharts.org/issues/156

Reverting Recharts to v1.8.5 fixes this issue. 2.0.2 should work fine locally/on codesandbox.

https://jsfiddle.net/tfbngj1o/

**Closed by ckifer** 2021-01-13 00:17 UTC
