### ISSUE TITLE
ErrorBar doesn't work with stacked bars

### ISSUE THREAD

**Issue by danvc** [recharts/recharts#2585] opened 2021-07-04 01:20 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/line-chart-specified-domain-forked-h3k8v?file=/src/App.tsx)

### Steps to reproduce
ErrorBar works perfectly while the bar is not stacked with others.

- In the source code mentioned as example, we can see 2 charts;
- Both charts contains ErrorBars;
- The chart in the bottom is not stacked.

### What is expected?
The ErrorBar should be displayed to the bar which is connected to.

### What is actually happening?
After stacking the bars, the ErrorBar disappear

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | MacOS 11.4 |
| Browser | Firefox 89.0.2 |

**Comment by ckifer** [comment] 2023-05-26 22:29
Looks like this is still an issue with current recharts 2.6.2. Labeled and new reproduction link:
https://codesandbox.io/s/line-chart-specified-domain-forked-e7xs7u?file=/src/App.tsx:2628-2650

**Comment by ckifer** [comment] 2023-06-15 06:07
Released in 2.7

**Closed by ckifer** 2023-06-15 06:07 UTC
Labels: bug, P1
