### ISSUE TITLE
Tooltip value not changing for stacked bar chart

### ISSUE THREAD

**Issue by kaaviya-min** [recharts/recharts#5186] opened 2024-10-31 14:54 UTC
## Do you want to request a feature or report a bug?

I tried to recreate the same codebase on code sandbox https://codesandbox.io/p/sandbox/stacked-bar-chart-forked-c5q8f8?file=%2Fsrc%2FStackedBarChart.tsx%3A59%2C1

The tooltip, Tootlip value and the highlight of the bar are working as expected. But When I reuse the same code on my codebase, the tooltip value does not change.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Rechart version - 2.12.4
React - 17.0.2
typescript - 4.7.4

**Comment by ckifer** [comment] 2024-10-31 15:04
> But When I reuse the same code on my codebase

This is impossible to diagnose without a reproduction outside of your codebase. It looks like everything is working in the codesandbox.

**Comment by ckifer** [comment] 2024-11-01 16:45
Going to close this, I'll reopen it once more details are added

**Closed by ckifer** 2024-11-01 16:45 UTC
Labels: pending response, needs reproduction
