### ISSUE TITLE
Is it possible to make Y-axis sticked on the left when X-axis is scrollable?

### ISSUE THREAD

**Issue by jasonn0118** [recharts/recharts#2607] opened 2021-07-27 21:15 UTC
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When my chart is getting smaller, x-axis is scrollable as I expected, but there is no y-axis to stick on the left.

### What does the proposed API look like?
There is no way to solve this issue without hacking the elements that recharts given.

![Screen Shot 2021-07-27 at 2 12 49 PM](https://user-images.githubusercontent.com/44929334/127228374-eb0ef440-928f-44b4-b573-d303678e6437.png)
![Screen Shot 2021-07-27 at 2 13 07 PM](https://user-images.githubusercontent.com/44929334/127228382-e4b0f2f8-0458-4d03-82cb-617bb9edf256.png)

**Comment by thareshjose** [comment] 2022-08-22 16:56
As far as I checked, recharts doesn't support it already, and it's sad to see that this issue has been open with ZERO response, for over a year!!..probably the contributors on the recharts have no clue how to implement that!

**Comment by ckifer** [comment] 2024-07-16 00:07
closing this as a duplicate of https://github.com/recharts/recharts/issues/1364

**Closed by ckifer** 2024-07-16 00:07 UTC
