### ISSUE TITLE
Performance Issues with Cartesian Axis (getStringSize)

### ISSUE THREAD

**Issue by lightsinthesky** [recharts/recharts#2589] opened 2021-07-08 16:48 UTC
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/magical-kilby-r8npx?file=/src/App.js)

### Steps to reproduce
Start a performance profile in chrome dev tools and you can see that there is a force reflow for every axis tick, which in the example is 5.

### What is expected?
the recharts render method would not utilize getStringSize because of its performance implications.

### What is actually happening?
As sample size increases and several charts are rendered on the same page the above reflow completely cripples the application performance.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 16.8.1 |
| System | OSX and Windows |
| Browser | Chrome, Safari, and Firefox |

---
this issue was submitted previously https://github.com/recharts/recharts/issues/1465 and closed.

**Comment by nikolasrieble** [comment] 2023-01-06 23:30
We could also look into how https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText performs in comparison to the current approach.

**Comment by Eric24** [comment] 2023-06-29 23:44
This is still a severe issue (since #1465, which shouldn't have been closed). ReCharts works great for relatively small numbers of items in a data-series, but with a few thousand items, the rendering time runs into several seconds. The root issue is confirmed to be `getStringSize()`, which is called at least 4 or 5 times per item.

**Comment by nikolasrieble** [comment] 2023-10-23 07:42
@ckifer Is this issues solved with the PR? The description states:
 > While not a fundamental solution, it will better utilize caching.

It seems to me that this is still an issue.

**Comment by ckifer** [comment] 2023-10-23 16:07
Oh apologies, it auto closed when I merged the PR

**Comment by nikolasrieble** [comment] 2023-11-19 18:30
We have since merged two PRs to tackle this issue. We have opened another follow up issues to improve cache clearing strategy https://github.com/recharts/recharts/issues/3955. 

Both improvements are released with https://github.com/recharts/recharts/releases/tag/v2.10

**Closed by nikolasrieble** 2023-11-19 18:30 UTC
Labels: P1

**Comment by bernardobelchior** [comment] 2023-11-19 22:50
I think there's still some room for improvement here.

[Here's](https://observablehq.com/@sto3psl/text-measurement-in-the-browser) a comparison of text measuring APIs. Basically, canvas' `measureText` seems to be the fastest, but maybe a bit inaccurate. 

We might allow Recharts' users to decide whether they prefer a faster API or a more accurate one (`getBoundingClientRect`?). When `minTickGap > 0`, it's unlikely there will be an overlap between consecutive ticks, so we might want to use that as a heuristic?

**Comment by nikolasrieble** [comment] 2023-11-20 07:00
@bernardobelchior That sounds like a great specific suggestion. Can you please create an issue for it? I prefer specific issues to long living generic ones, since specific issues are more easy to tackle, i.e. for new contributors.

**Comment by bernardobelchior** [comment] 2023-11-20 22:54
Sure thing, @nikolasrieble 👍 

[Here](https://github.com/recharts/recharts/issues/3983) you have it
