### ISSUE TITLE
Brush for line chart no longer shows anything other than the line components

### ISSUE THREAD

**Issue by HerrPfister** [recharts/recharts#4193] opened 2024-02-15 22:14 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-l7lp5l?file=%2Fsrc%2Findex.js%3A7%2C17&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsnqq88q00073b6k7w09k95p%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsnqq88q00033b6k2e1w6m4s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsnqq88q00043b6kzl61ndpm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsnqq88q00063b6krqdgt3q2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsnqq88q00033b6k2e1w6m4s%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsnqq88q00023b6kxnpvqnb3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A17%257D%255D%257D%255D%252C%2522id%2522%253A%2522clsnqq88q00033b6k2e1w6m4s%2522%252C%2522activeTabId%2522%253A%2522clsnqq88q00023b6kxnpvqnb3%2522%257D%252C%2522clsnqq88q00063b6krqdgt3q2%2522%253A%257B%2522id%2522%253A%2522clsnqq88q00063b6krqdgt3q2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsnqq88q00053b6knet0ae78%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsnqq88q00053b6knet0ae78%2522%257D%252C%2522clsnqq88q00043b6kzl61ndpm%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsnqq88q00043b6kzl61ndpm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
1. Create a <ComposedChart>
2. Add <Line> <CartesianGrid> and <ReferenceLine> components to it
3. Create a Brush and add it to the chart
4. Add the same <Line> <CartesianGrid> and <ReferenceLine> components to it
5. See how the lines appear in the brush but not the reference line and the cartesian grid is rendered oddly

### What is expected?
All components rendered in the chart, and given to the brush chart, are rendered.

> The Following image was created with version 2.10.4

<img width="876" alt="Screenshot 2024-02-15 at 4 05 16 PM" src="https://github.com/recharts/recharts/assets/3292704/b79d089f-ede2-42e0-9199-dc308c72881b">

### What is actually happening?
All components rendered in the chart, and given to the brush chart, are not rendered.

> The Following image was created with version 2.12.0

<img width="958" alt="Screenshot 2024-02-15 at 4 13 55 PM" src="https://github.com/recharts/recharts/assets/3292704/854c4333-1f0b-4696-9ded-2e9c7290ec84">

| Environment | Info |
|---|---|
| Recharts | v2.12.0 |
| React | React ^17.0.2 |
| System | MacOS Sonoma 14.2.1 |
| Browser | Chrome 120 |

**Comment by ckifer** [comment] 2024-02-15 22:56
Thanks for the report. Looks like the change happened between 2.10.4 and 2.11.0. @recharts/maintainers FYI, will probably try to patch this in 2.x

**Comment by ckifer** [comment] 2024-02-15 23:03
The cartesian grid behavior is the same, no change between 2.10.4 and 2.11/2.12

**Comment by ckifer** [comment] 2024-02-15 23:35
@PavelVanecek I think this might be from context changes?

**Comment by PavelVanecek** [comment] 2024-02-15 23:38
Possible! Did you find which commit causes the problem?

**Comment by ckifer** [comment] 2024-02-15 23:43
No not yet unfortunately, wish we had a storybook entry with the graph-in-brush like this

**Comment by ckifer** [comment] 2024-02-15 23:49
@PavelVanecek first issue (ReferenceLine) is probably from here https://github.com/recharts/recharts/commit/2e5f0042539949b640a4dbb4ceea1412f2ba1109

Second issue (CartesianGrid) is probably either https://github.com/recharts/recharts/commit/3eb2fb3222c0186e0170253f41ceb3d13936134b or https://github.com/recharts/recharts/commit/b8575df466d3eb1cd503a80af28c144ead853d98

**Comment by ckifer** [comment] 2024-02-16 01:58
ReferenceLine issue confirmed this PR by checking out each commit https://github.com/recharts/recharts/pull/4033

Cartesian Grid issue from this PR confirmed by checking out each commit https://github.com/recharts/recharts/pull/4086

**Comment by ckifer** [comment] 2024-02-16 03:04
Wrapping

` if (compact) {...` here https://github.com/recharts/recharts/blob/3.x/src/chart/generateCategoricalChart.tsx#L2210

in another chart layout context provider with `width`, `height` instead of `offset.width`, `offset.height` does the trick

**Comment by ckifer** [comment] 2024-02-20 17:54
Fixed in 2.12.1 https://github.com/recharts/recharts/releases/tag/v2.12.1

**Closed by ckifer** 2024-02-20 17:54 UTC
Labels: bug, P0

**Comment by Yyana22** [comment] 2024-04-27 10:16
Good afternoon. Can you please tell me how i can fix Brush in my lineChart ? 
![image](https://github.com/recharts/recharts/assets/70588429/8f7ad0b4-bc7d-454d-943b-1554f2623bb5)
![image](https://github.com/recharts/recharts/assets/70588429/914769e9-0b46-40c4-8619-708215183540)
is it possible to make sure that the lines are not depending on the Brush for the entire graph, and not cut off?
