### ISSUE TITLE
In stacked barchart the When I hover the xaxis data is overlap 

### ISSUE THREAD

**Issue by vel-kathir** [recharts/recharts#3969] opened 2023-11-16 08:55 UTC
import { Box, Grid, Typography } from "@mui/material";
import React, { useEffect, useState } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  Label,
  Line,
  ResponsiveContainer,
} from "recharts";
import DropDown from "../../utils/DropDown";
import Month from "../../utils/month.json";
import Year from "../../utils/year.json";

const CustomTooltip = ({ active, payload, label, chartMonth, chartYear }) => {
  console.log(payload, "pay", active, payload[0]?.value, chartMonth, chartYear);
  if (active) {
    const sum =
      payload[0].payload?.Clarification +
      payload[0].payload?.Completed +
      payload[0].payload?.Inprogress +
      payload[0].payload?.Rejected;

    return (
      <div className="custom-tooltip">
        <Grid
          sx={{ borderBottom: "0.2px solid", padding: "10px 30px 10px 10px" }}
        >
          {`${chartMonth}, ${chartYear}`}
        </Grid>
        <Box sx={{ p: 1.2 }}>
          <Grid>{`Total Task - ${sum}`}</Grid>
          <Grid
            container
            justifyContent="space-between"
            alignItems="center"
            sx={{ mt: 1 }}
          >
            <Grid sx={{ display: "flex", alignItems: "center" }}>
              <Grid
                sx={{
                  padding: "5px",
                  background: "#5FB367",
                  height: "10px",
                  mr: 1,
                  borderRadius: "2px",
                }}
              ></Grid>
              <Grid>{`Completed`}</Grid>
              {/* <Typography className="graph-tooltip-fontweight">{`Completed`}</Typography> */}
            </Grid>
            <Grid item>{`${payload[0].payload?.Completed}`}</Grid>
          </Grid>
          <Grid container justifyContent="space-between" sx={{ mt: 1 }}>
            <Grid sx={{ display: "flex", alignItems: "center" }}>
              <Grid
                sx={{
                  padding: "5px",
                  background: "#3F80FD",
                  height: "10px",
                  mr: 1,
                  borderRadius: "2px",
                }}
              ></Grid>
              <Grid item>{`InProgress`}</Grid>
            </Grid>
            <Grid item>{`${payload[0].payload?.Inprogress}`}</Grid>
          </Grid>
          <Grid container justifyContent="space-between" sx={{ mt: 1 }}>
            <Grid sx={{ display: "flex", alignItems: "center" }}>
              <Grid
                sx={{
                  padding: "5px",
                  background: "#FF645A",
                  height: "10px",
                  mr: 1,
                  borderRadius: "2px",
                }}
              ></Grid>
              <Grid item>{`Rejected`}</Grid>
            </Grid>
            <Grid item>{`${payload[0].payload?.Rejected}`}</Grid>
          </Grid>
          <Grid container justifyContent="space-between" sx={{ mt: 1 }}>
            <Grid sx={{ display: "flex", alignItems: "center" }}>
              <Grid
                sx={{
                  padding: "5px",
                  background: "#FFAD32",
                  height: "10px",
                  mr: 1,
                  borderRadius: "2px",
                }}
              ></Grid>
              <Grid item>{`SLABreach`}</Grid>
            </Grid>
            <Grid item>{`${payload[0].payload?.Clarification}`}</Grid>
          </Grid>
        </Box>
      </div>
    );
  }
  return null;
};

const CustomizedAxisTick = (props) => {
  const { x, y, payload, activeIndex, index } = props;
  console.log(props, ":pppp");

  return (
    <g transform={`translate(${x},${y})`}>
      <foreignObject
        x={-40}
        y={-1}
        width={80}
        height={400}
        // style={{ width: "100%" }}
      >
        <div
          className={index === activeIndex ? "activecaretup" : ""}
          style={{
            maxWidth: "100%",
            padding: "5px 2px",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            textAlign: "center",
            marginTop: index === activeIndex ? "6px" : "0px",
            color: index === activeIndex ? "#1B76E0" : "#808080",
            borderRadius: "5px",
            border: index === activeIndex ? "1px solid #5E7A9B" : "#fff",
            backgroundColor: index === activeIndex ? "#F9F9F9" : "transparent",
            zIndex: "9999",
          }}
        >
          <text x={0} y={0} textAnchor="end" fill="#666">
            <span
              style={{
                fontSize: index === activeIndex ? "0.75rem" : "0.75rem",
                color: index === activeIndex ? "#1B76E0" : "#363157",
                wordWrap: "break-word",
              }}
            >
              {index === activeIndex
                ? payload?.value
                : payload?.value.length > 6
                ? `${payload?.value.slice(0, 5)}..`
                : payload?.value}
            </span>
          </text>
        </div>
      </foreignObject>
    </g>
  );
};

export default function Example(props) {
  const { ChartMonthChange, ChartYearChange, chartMonth, chartYear, chart } =
    props;
  const [activeIndex, setActiveIndex] = useState(null);
  const maxYValue = chart.reduce((max, entry) => {
    const sum =
      entry.Inprogress + entry.Completed + entry.Rejected + entry.Clarification;
    return Math.max(max, sum);
  }, 0);

  const yDomain = [0, Math.ceil(maxYValue / 5) * 5];
  const tickValues = [];
  for (let i = 0; i <= yDomain[1]; i += 5) {
    tickValues.push(i);
  }

  useEffect(() => {
    const legendWrapper = document.querySelector(".recharts-legend-wrapper");
    if (legendWrapper) {
      legendWrapper.innerHTML = `${
        JSON.parse(window.localStorage.getItem("userProduct"))?.data.role
      } Name List`;
    }
  });

  return (
    <Grid sx={{ width: "97%", margin: "auto", mt: 3, overflow: "auto" }}>
      <Box
        style={{
          border: "1px solid rgba(54, 49, 87, 0.12)",
          borderRadius: "6px",
          background: "#FFF",
          boxShadow: "0px 5.08601px 30.51603px 0px rgba(0, 0, 0, 0.10)",
          // width: "100%",
        }}
      >
        <Grid
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            padding: "0px 0px 0px 15px",
            borderBottom: "1px solid rgba(54, 49, 87, 0.14);",
          }}
        >
          <Typography>{"Comparison Chart with My Peers"}</Typography>
          <Grid>
            <Box display="flex" gap={2} sx={{ m: 2, mt: 3 }}>
              <DropDown
                month={Month}
                MonthChange={ChartMonthChange}
                value={chartMonth}
              />
              <DropDown
                month={Year}
                MonthChange={ChartYearChange}
                value={chartYear}
              />
            </Box>
          </Grid>
        </Grid>
        <Grid
          sx={{ padding: "20px 30px 30px", overflow: "auto", width: "100%" }}
          className="graph-scroll"
        >
          {chart.length !== 0 ? (
            <ResponsiveContainer height={500}>
              <BarChart
                data={chart}
                // width={chart.length * 85}
                onMouseMove={(e) => {
                  setActiveIndex(e.activeTooltipIndex);
                }}
              >
                <CartesianGrid vertical={false} />
                <XAxis
                  dataKey="assigneeName"
                  tick={(props) => (
                    <CustomizedAxisTick {...props} activeIndex={activeIndex} />
                  )}
                  angle={-90}
                />
                {/* <YAxis domain={yDomain} ticks={tickValues} width={60} /> */}
                <YAxis
                  domain={yDomain}
                  ticks={tickValues}
                  width={60}
                  stroke="#363157"
                >
                  <Label
                    value="Number of Tasks"
                    angle={-90}
                    position="insideLeft"
                    style={{
                      textAnchor: "middle",
                      // fontSize: "14px",
                      fill: "#3F3F3F",
                    }}
                  />
                </YAxis>
                <Tooltip
                  content={
                    <CustomTooltip
                      chartMonth={chartMonth}
                      chartYear={chartYear}
                    />
                  }
                  arrow={true}
                  cursor={{ fill: "#3631570F" }}
                />
                <Legend />
                <Line type="monotone" dataKey="SRM LISTS" stroke="#8884d8" />
                <Bar
                  dataKey="Completed"
                  stackId="a"
                  fill="#5FB367"
                  barSize={35}
                />
                <Bar dataKey="Inprogress" stackId="a" fill="#3F80FD" />
                <Bar dataKey="Rejected" stackId="a" fill="#FF645A" />
                <Bar
                  dataKey="Clarification"
                  stackId="a"
                  fill="#FFAD32"
                  radius={[5, 5, 0, 0]}
                />
              </BarChart>
            </ResponsiveContainer>
          ) : (
            <Typography sx={{ textAlign: "center" }}>
              {"No data found... 🧐"}
            </Typography>
          )}
        </Grid>
      </Box>
    </Grid>
  );
  // }
}

see the output
when I hover the roshan letter is the B is come in iinside 
![image](https://github.com/recharts/recharts/assets/147596479/cb0b05ac-0294-4ebd-9274-80464e4b26a2)

**Comment by nikolasrieble** [comment] 2023-11-16 12:13
Please do format the issue so that we can read it nicely.

**Comment by vel-kathir** [comment] 2023-11-16 12:23
When I hover the Roshan In X-axis the nearest person Bhanu name is overlapped why?
![image](https://github.com/recharts/recharts/assets/147596479/15dfa444-1a3d-43b6-ae60-7336c9dee583)

**Comment by ckifer** [comment] 2024-01-23 20:01
Going to close this since it never got formatted and is a duplicate of 
https://github.com/recharts/recharts/issues/1364
https://github.com/recharts/recharts/issues/1364
https://github.com/recharts/recharts/issues/1761
https://github.com/recharts/recharts/issues/3059

Please format the issue if you still need help

**Closed** 2024-01-23 20:01 UTC

**Comment by arash-zarei** [comment] 2024-06-20 20:14
> When I hover the Roshan In X-axis the nearest person Bhanu name is overlapped why? ![image](https://private-user-images.githubusercontent.com/147596479/283446921-15dfa444-1a3d-43b6-ae60-7336c9dee583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MTM5NDksIm5iZiI6MTcxODkxMzY0OSwicGF0aCI6Ii8xNDc1OTY0NzkvMjgzNDQ2OTIxLTE1ZGZhNDQ0LTFhM2QtNDNiNi1hZTYwLTczMzZjOWRlZTU4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQyMDAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTE1NDk1MjZjM2I0YzU3NzI5OTJkODJjMDk5OGEyM2Y4NTY5ZmQ4NjkyOTYzMWE0NzlhMTFhZDU3NjNmMWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TjYa5aoxjPHlWXCDNZRZAbsu6X8wnVxA_Okbwg-ttdw)
 
 
 
 
 
 i am need you code.
