### ISSUE TITLE
Make Y-axis sticky while horizontal scrolling through the graph.

### ISSUE THREAD

**Issue by damiaanh** [recharts/recharts#3059] opened 2022-11-15 13:52 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, Brush can be used to provide an horizontal scroll. This is counterintuitive on mobile. I'm believe that it should be possible to scroll horizontal by clicking/dragging the graph itself. 

I created this behaviour using a wrapper div with an `overflow-x: scroll` CSS property. This works perfect, but unfortunately the y-axis also scrolls with the rest of the graph. It would be nicer to have it fixed, just like the behaviour of the brush. I tried offsetting the margin of the y-axis with the amount scrolled. This does provide the wanted behaviour, but is shocky since this calculation is not optimized.

### What does the proposed API look like?
It should be possible to render Axis elements outside the graph, so it can be placed and styled differently from the rest. If such is the case, data can be passed to the element such that a valid scale can be determined.

**Comment by damiaanh** [comment] 2022-12-22 08:34
@ckifer For now I've made an (ugly) workable fix by using two graphs, where one of the graphs is only the the y-axis for the final product.

I do not know what could be added or changed in the API, but I would expect I could give an offset for the axis itself, as now I only can change the tick / label offset I believe. I could have then used this prop to dynamically change the offset of the y-axis to get the desired behaviour.

**Comment by ckifer** [comment] 2024-07-16 00:10
closing this as a duplicate of https://github.com/recharts/recharts/issues/1364

**Closed by ckifer** 2024-07-16 00:10 UTC
Labels: feature request
