### ISSUE TITLE
Bar is not showing on a BarChart when there is only one data point after upgrading to 2.0.10 (from 2.0.9)

### ISSUE THREAD

**Issue by marnixhoh** [recharts/recharts#2601] opened 2021-07-22 07:51 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-undefined-data-vz7e4?file=/src/index.js)

### Steps to reproduce
Pass only one data point into the `data` prop on the `BarChart` component. When multiple are passed everything works as expected.

Note that this did not happen on Recharts 2.0.9. This broke after upgrading to 2.0.10

### What is expected?
Bars to show even if there is only one data point.

### What is actually happening?
No bars are shown when there is only one data point.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 16.14.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by pabrodez** [comment] 2021-07-22 17:26
Related #2512

**Comment by andy128k** [comment] 2021-07-23 14:59
That's interesting. I observe totally opposite. 2.0.9 did not work (showed no bars) and with #2512 works properly.

OTOH, I have a pinned version of recharts `=2.0.9` with a patch on top of it (done with [patch-package](https://www.npmjs.com/package/patch-package)). So, I cannot say anything about 2.0.10.

**Comment by staevs** [comment] 2021-07-23 15:32
2.0.10 works fine for me with one data point

**Comment by pabrodez** [comment] 2021-07-23 16:16
Using latest version, did a bit of digging, and found that `Rectangle.tsx` is being passed `width= 0` and therefore returning null and not rendering at the `path`.  If I overwrite the height and other variables in the code with any values, it will actually render
![image](https://user-images.githubusercontent.com/18014700/126811277-9d547ba8-48b2-4c51-bb15-a2b9f3c7c205.png)

**Comment by andy128k** [comment] 2021-07-23 20:29
@pabrodez this is what I saw 3 months ago with 2.0.9. Function `getBandSizeOfAxis` returns `0` when there is only one data point. And this leads to a zero width bar (assuming they are vertically oriented).

**Comment by andy128k** [comment] 2021-07-23 20:53
Ok, here is my brain dump:

When there is a single data point, function `getBandSizeOfAxis` returns `0` (which is a bug itself).
There are scenarios (like mine) when `maxBarSize` is given, and my patch solves the problem.
But there are also scenarios when `maxBarSize` is `undefined` and my patch does bad job replacing `0` by `undefined`.

I see here two possible ways to solve this issue:
1. replace ` || ` by a ` ?? `. Here I am not sure if this pretty fresh operator is supported by a recharts' build tools.
2. add additional ` || 0` to the chain.
3. Revisit the implementation of the function `getBandSizeOfAxis` and make it return sane results for a single data point.

I would like to see a guidance of library maintainers here, which path to chose.

---

@marnixhoh I suggest you to specify `maxBarSize` property as a temporary workaround.

**Comment by pabrodez** [comment] 2021-07-24 15:54
@andy128k  Thanks, I've taken another look, and changing the `XAxis` `type` to `category`, or removing the `type` prop seems to work. By passing `number`, and because the default number of ticks is 5, it produces 5 ticks, being the value of `dataKey` the last of those 5. By passing to XAxis `domain={['dataMin', 'dataMax']}` it only calculates one tick and centers it properly, however the issue of bars not being drawn persists.
As an user, when there's only one single data point in a linear xaxis scale, I would prefer to se an XAxis with one single tick and centered (as mentioned above). But this is a separate issue.

**Comment by pabrodez** [comment] 2021-07-24 16:59
I also noticed that the XAxis default props include:
````javascript
  tickCount: 5,
  type: 'category',
  domain: [0, 'auto'],
```
This forces a single data point array to have 5 ticks starting from 0. If I change domain to `['dataMin', 'dataMax']` and the change to `getBandSizeOfAxis()`, now I get a nicely centered single data point with both bars drawn.

**Comment by marnixhoh** [comment] 2021-08-01 10:38
@andy128k Thank you so much for your suggestion to use `maxBarSize`. This indeed "solves" the problem for now

**Comment by ckifer** [comment] 2023-02-08 00:11
Updating the original example to the latest recharts version results in rendering the bar with or without a domain specified. Going to close this as completed

**Closed by ckifer** 2023-02-08 00:11 UTC

**Comment by otudosa** [comment] 2023-11-01 09:57
the issue is still here in version: 2.9.0

**Comment by pavsidhu** [comment] 2025-04-27 11:54
It seems this issue is still occurring - setting barSize/maxBarSize does fit it however this isn't an ideal solution - anything I can do to help?
