### ISSUE TITLE
Unable to Change Font Size of X-Axis Labels with tick Property

### ISSUE THREAD

**Issue by RodrigoRibeiroBMG** [recharts/recharts#5331] opened 2024-12-09 10:26 UTC
https://github.com/recharts/recharts/issues/5236#issuecomment-2527476321

**Comment by ckifer** [comment] 2024-12-09 16:53
If you could can you copy the contents of that comment to this issue? Generally we want the issue itself to have all relevant information

**Comment by ckifer** [comment] 2024-12-09 16:57
https://codesandbox.io/p/sandbox/line-chart-width-xaxis-padding-forked-lzhklj

This is not a bug. The same thing happens in the SVG spec itself, global CSS styles will take precedence over locally defined `fontSize`

Try removing the font-size definition in styles.css and see the local fontSize take effect

Going to close this

**Closed by ckifer** 2024-12-09 16:57 UTC
