### ISSUE TITLE
Tooltip not animating to active tick

### ISSUE THREAD

**Issue by CalgaryMichael** [recharts/recharts#1079] opened 2017-12-11 17:48 UTC
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
The example given on [this page](http://recharts.org/#/en-US/examples/SimpleLineChart) shows that the Tooltip is able to animate to the active tick. However, this functionality is lost in the [corresponding jsfiddle](http://jsfiddle.net/ndLhnegs/). It is unclear why this functionality is lost, and the docs do not seem to be of much help as to why this is happening.

In my project setup, I have the following setup for a component which will not allow the Tooltip to follow the active tick:
```
    render() {
        const data = this.getData();
        return (
            <div id={this.props.id}>
                <LineChart
                    height={this.props.height}
                    width={this.props.width}
                    data={data}
                >
                    {this.props.children}
                    <CartesianGrid stroke={flatGrey} />
                    <XAxis dataKey={this.props.xAxisKey} />
                    <YAxis dataKey={this.props.yAxisKey} />
                    <Tooltip isAnimationActive={true} />
                    <Legend iconType="circle" iconSize={8} />
                </LineChart>
            </div>
        );
    }
```
With this setup, `activeCoordinate` will always be equal to `{ x: 0, y: 0 }`

Is there something that I am missing? I was looking into handling this with `onMouseEnter`, but it seemed that this behavior should have already been executed by `handleItemMouseEnter`

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts@1.0.0-beta.6
chrome@63.0.3239.84

**Comment by mkreim** [comment] 2017-12-15 09:33
Hi,

I am observing the same problem for the bar charts. A good example can be seen here:
expected behavior: http://recharts.org/#/en-US/examples/SimpleBarChart
buggy behavior: http://jsfiddle.net/v8gxrbyu/
For me it looks like the coordinates of the tooltip are always 0,0. So the tooltip is not moving around and the cursor shows a gray box at the left side of the chart.

Also this issue seems to be a duplicate of https://github.com/recharts/recharts/issues/1039

Thanks an best regards

Michael

**Comment by menixator** [comment] 2017-12-17 16:03
@mkreim I've noticed that this issue only occurs on jsfiddles. Try it on codepen or codesandbox.io. I haven't tried to zero in on the reason though.

**Comment by mkreim** [comment] 2017-12-18 13:03
@menixator thanks a lot for your advice. However, my colleague figured already out that we can fix the problem using this pull request https://github.com/recharts/recharts/pull/1095

**Comment by CalgaryMichael** [comment] 2017-12-18 15:13
The issue from #1095 seems to be in line with the problem that I am having.

I am using the UMD version of Recharts, which does not package lodash. This was causing the `entry` to always be `undefined`. This explains why the jsfiddles were not properly showing the behavior of the Tooltip.

**Comment by xile611** [comment] 2020-03-17 03:56
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.

**Closed by xile611** 2020-03-17 03:56 UTC
