### ISSUE TITLE
X Axis renders unordered ticks while using Brushing

### ISSUE THREAD

**Issue by sirpeas** [recharts/recharts#4024] opened 2023-12-18 13:50 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recharts-issue-template-forked-nrsvz7)

### Steps to reproduce
1. Narrow brush size
2. Move brush around

### What is expected?
X Axis values to properly change

### What is actually happening?
In the above example values on x axis are not changing

| Environment | Info |
|---|---|
| Recharts | v2.10.3 |
| React | React 18.2.0 |
| System | OSX |
| Browser | Chrome |

**Comment by ckifer** [comment] 2023-12-18 18:55
Hi @sirpeas can you be more specific?

Seems to be working for me
![image](https://github.com/recharts/recharts/assets/25180830/d71c8803-91fb-4217-87b7-4a205407b7ce)

**Comment by sirpeas** [comment] 2023-12-19 02:56
1. Values on x axis does not change during brushing
2. Brush values stay the same during brushing
Video down below
https://github.com/recharts/recharts/assets/4818642/aa5b343e-592f-43c1-88b6-fe6b3970068d

**Comment by ckifer** [comment] 2023-12-19 06:01
@sirpeas can you try upgrading to the latest recharts version? The sandbox you were using was on 1.8.1

See video 
https://github.com/recharts/recharts/assets/25180830/edf495a7-97ad-4431-b31a-d98ee7c5150f
![](https://github.com/recharts/recharts/assets/25180830/edf495a7-97ad-4431-b31a-d98ee7c5150f)

**Comment by ckifer** [comment] 2023-12-19 16:43
Going to close this as I think it was only because you were on an older version, I'll re-open if we can reproduce

**Closed by ckifer** 2023-12-19 16:43 UTC
Labels: pending response
