### ISSUE TITLE
animationBegin on Tooltip

### ISSUE THREAD

**Issue by fllprbt** [recharts/recharts#1794] opened 2019-07-04 07:37 UTC
## Do you want to request a feature or report a bug?
It's a bug

## What is the current behavior?
I want my tooltip to appear with a delay (>=~250ms) because currently it is glitchy when there are many bars in a wide barchart and I move the mouse relatively fast among them. Of course this issue can be generalised for other charts as well.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
I am trying it in the default example https://jsfiddle.net/alidingling/30763kr7/ by adding to my tooltip animationBegin={250} (tried with greater values as well) but no change did occur.

## What is the expected behavior?
To see the tooltip animation begin after the specified number.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Under Chrome. I did not work with previous versions.
Versions where I can reproduce current behavior:
"recharts": "1.5.0", "1.6.2"

**Comment by rollercodester** [comment] 2019-10-04 15:02
I'm experiencing the same issue, primarily when moving the mouse pointer up-and-down along the Y-axis. The `animationDuration` property sounds like what is needed to help stop "the jitters", but as @fllprbt pointed out, it seems to be ignored.

The best I could do to tame the tooltip was set `animationEasing='ease-in'` and `animationDuration={500}`. Unfortunately, while it helps with the jitters, it also makes the tooltip a little sluggish...but it's the better experience for the charts on my end.

If I can get ahead of my current project, I may take a look and propose a fix. Feels like a regression that should be fixable.

**Comment by rollercodester** [comment] 2019-10-04 15:10
Possible dupe of https://github.com/recharts/recharts/issues/1499

**Comment by fllprbt** [comment] 2019-10-07 10:20
We managed to resolve this by passing in the content prop an actual component or a fragment (when we don't want the toolbar to be shown). Deciding when to show and not was implemented by us, based on some debouncing logic.

**Comment by xile611** [comment] 2020-03-20 10:03
Maybe what you want is change the gap of triggering the event of tooltip.
You can change `throttleDelay` of chart.
If the problem persists, please open a new issue according to the issue guide.

**Closed by xile611** 2020-03-20 10:03 UTC
Labels: Type: Bug

**Comment by krnlde** [comment] 2021-05-06 13:01
`<Tooltip isAnimationActive={false} />` helps, too.

**Comment by ranneyd** [comment] 2023-09-27 20:27
> Maybe what you want is change the gap of triggering the event of tooltip. You can change `throttleDelay` of chart. If the problem persists, please open a new issue according to the issue guide.

This. I set mine to `500` and it's not laggy at ALL now. I think what was happening (on a line chart fyi) is if I went over multiple points in one movement it would start/stop easing for each one. Once I set this I had no problems. It is a _little_ delayed if you move around fast but it's honestly kinda cute how it "catches up".
