### ISSUE TITLE
 two XAxis allowDuplicatedCategory={false}, tooltip didn't show data of second XAxis

### ISSUE THREAD

**Issue by AkramHarazem** [recharts/recharts#4235] opened 2024-02-25 10:26 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/two-xaxis-recharts-j2p3xj?file=%2Fsrc%2FApp.jsx)

### Steps to reproduce
when using  allowDuplicatedCategory={false} on XAxis, Tooltip show first XAxis data only.
you can see that in code sandbox

### What is expected?
The Tooltip should display two XAxis data when hovering over lines.

### What is actually happening?
Adding allowDuplicatedCategory={false} to XAxis component in  makes the Tooltip stop working for second XAxis data only show first XAxis data

| Environment | Info |
|---|---|
| Recharts | v2.12.1 |
| React | React |
| System | ubuntu 22.04 |
| Browser | firefox |

**Comment by ckifer** [comment] 2024-02-25 15:10
Duplicate of #2348, we can continue to track over there

**Closed** 2024-02-25 15:10 UTC
