### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'clipDot')

### ISSUE THREAD

**Issue by zahir-dct** [recharts/recharts#3635] opened 2023-06-20 13:26 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
It comes from /static/node_modules/recharts/es6/cartesian/Line.js:350:31

### What is expected?
Previously the same worked, Now it's not working.

### What is actually happening?
Uncaught TypeError: Cannot read properties of null (reading 'clipDot')
    at a.value (Line.js:350:31)
    at Wa (react-dom.production.min.js:187:188)
    at Qa (react-dom.production.min.js:186:173)
    at Gs (react-dom.production.min.js:269:427)
    at Ic (react-dom.production.min.js:250:347)
    at jc (react-dom.production.min.js:250:278)
    at Pc (react-dom.production.min.js:250:138)
    at bc (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)

| Environment | Info |
|---|---|
| Recharts | v2.3.2 |
| React | 17.0.2 |
| System | Windows/Linux |
| Browser | All |

---
"recharts": "^2.3.2"
By removing "^" from "^2.3.2", it works

**Comment by ckifer** [comment] 2023-06-20 14:11
Sorry this happened, will fix asap. This happens when? Can you make a sandbox to reproduce?

**Comment by ckifer** [comment] 2023-06-20 16:05
@zahir-dct also, `clipDot` does not exist in 2.3.2 - i'm not sure how you are using the property but it was only released in 2.7.0

**Comment by zahir-dct** [comment] 2023-06-21 06:29
> Sorry this happened, will fix asap. This happens when? Can you make a sandbox to reproduce?

https://codesandbox.io/s/vigilant-blackwell-gg5rkq?file=/package.json

**Comment by ckifer** [comment] 2023-06-21 06:32
`dot` doesn't have `null` as an acceptable type - if you use `undefined`, don't define it at all, or supply `DotProps` it will render correctly

**Comment by ckifer** [comment] 2023-06-21 06:35
I'll fix this by making sure null doesn't throw an error like this, but I don't consider this a breaking change since it follows the types defined since v2

**Closed** 2023-06-22 06:56 UTC
Labels: bug

**Comment by ckifer** [comment] 2023-06-22 07:19
Released in 2.7.2
