### ISSUE TITLE
Some dots are not active when hovered in area chart

### ISSUE THREAD

**Issue by alice0217** [recharts/recharts#4046] opened 2024-01-09 20:26 UTC
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/alice0217/min-reproduction](https://github.com/alice0217/min-reproduction)

### Steps to reproduce
npm start and the area chart should be displayed on http://localhost:3000

### What is expected?
I expected that a tooltip will show up for every dot in the area chart, i.e., every dot can be active when I hover on it.

### What is actually happening?
What's actually happening is that when there are more than two dots on the same x-axis, only the dots at the top and bottom become active when I hover on them. The ones in the middle are not. In my example, there are three dots (2, 3), (2, 4), and (2, 5). The middle dot (2, 4) wasn't active when I hover over it, even though I saw the tooltip moves closer to it. The tooltip either shows (2, 3) or (2, 5). 

[gif to demonstrate the issue](https://github.com/recharts/recharts/assets/71456398/f878777f-b7bb-429e-9cfb-df1796aea773)

| Environment | Info |
|---|---|
| Recharts | v2.10.3 |
| React | 18.2.0 |
| System | 14.0 (23A344) (macOS) |
| Browser | 120.0.6099.199 (Chrome) |

---
I find it that scatter dots in a scatter chart don't have this issue when there are multiple dots on the same x-axis. The tooltips seem very precise. Even though connecting the dots make it look like a line chart, it doesn't work in my favor as I can't fill in the area between the lines and the x-axis. If there's any other hack that I can reproduce an area chart without encountering the problem I addressed, I'd be completely down to use that. Thank you!

**Comment by ckifer** [comment] 2024-01-09 21:38
Hi, it looks like there isn't anything in your reproduction except a blank create-react-app

**Comment by ckifer** [comment] 2024-01-09 21:40
But this is known https://github.com/recharts/recharts/issues/3797

Its a current limitation - tooltip information is calculated based on an index rather than a value at this point

**Comment by alice0217** [comment] 2024-01-10 00:34
Hi @ckifer Thanks for your reply, I pushed my changes to the git repo. 

Is the limitation essentially saying tooltip wouldn't work as perfectly if there are duplicate on the same x axis? If so, do you happen to know any other hack I can implement some chart like area chart without using `AreaChart`?

**Comment by ckifer** [comment] 2024-01-10 00:41
Correct, it only finds the first value and displays it rather than all values.

The issue exists with all charts, so no workarounds by using some other chart.
In the issue I linked there is a link to https://gist.github.com/Muzietto/270dba9ba818edab44d95cab99da0365
Which may work as a workaround though I haven't personally tried it

**Comment by ckifer** [comment] 2024-01-10 06:57
Going to close this as a duplicate, we'll continue to track in the other issue

**Closed by ckifer** 2024-01-10 06:57 UTC
