### ISSUE TITLE
Keyboard tabbing through a bar chart doesn't show the tooltip like it would if we were to hover the mouse over

### ISSUE THREAD

**Issue by hangryandy** [recharts/recharts#2729] opened 2021-12-06 10:19 UTC
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keyboard-tabbing-to-show-tooltip-k0285?file=/src/index.js)

### Steps to reproduce
1. Hover over a bar - the tooltip will show
2. Press the tab to focus on a bar (`tabIndex="0"` has been added) - no tooltip shows

### What is expected?
For accessibility, we would like the tool tip to show when we tab to a bar.

### What is actually happening?
No tooltip is showing when we tab onto a bar.

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 17.0.2 |
| System | Windows 11 |
| Browser | Chrome 96.0.4664.45 |

---
We're currently going through our app to add accessibility for disabled users and for this, we need to be able to navigate the app, including the charts using the keyboard.

**Comment by vtarelkin** [comment] 2022-06-16 11:48
@hangryandy any solution founded?

**Comment by Hevia** [comment] 2022-09-07 22:43
Any updates? @hangryandy  This would be a great bugfix for our use cases. Thanks for your work :)

**Comment by mgifford** [comment] 2022-09-21 19:50
So this would likely be a problem for both sighted keyboard-only users, and blind users. Also anyone using Apple's Voice Control or Dragon Naturally Speaking. 

Thinking about it, does this pattern work for smartphone or tablet users? 

This pattern looks nice for sighted users on a desktop who use a mouse, but is that good enough? Who are we willing to exclude?

**Comment by ckifer** [comment] 2023-07-11 14:23
This is possible in the later version of recharts - use the accessibilityLayer prop on your charts (Categorical at least)

**Comment by msftedad** [comment] 2023-08-18 04:19
Hi @hangryandy, Product team is asking updated as this bug is making our team non-compliant so could your team pls get fix ETA from third-party team.

**Comment by ckifer** [comment] 2023-08-18 05:31
@msftedad not sure what you're saying here but the creator of the issue is not the a contributor to this project?

This should be able to be closed as well - add accessibilityLayer to your charts and you can use the arrow keys to enable the tooltip

**Comment by ckifer** [comment] 2023-08-18 05:33
Resolving this since it is now possible to enable accessibilityLayer on Bar (and call Cartesian) charts which allows tabbing to the chart and moving the hovered tooltip item with arrow keys

**Closed** 2023-08-18 05:33 UTC

**Comment by jamesw-msft** [comment] 2023-08-25 21:05
Hi @ckifer , what is the minimum version of recharts that supports accessibilityLayer? https://release--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-accessibility--docs

Thanks

**Comment by ckifer** [comment] 2023-08-25 21:08
@jamesw-msft 2.6 though I'd least go to 2.6.2

**Comment by msftedad** [comment] 2023-08-28 04:58
Hi @ckifer, Can we know on which version this issue is fixed so that we can verify the issue. Thanks

**Comment by ckifer** [comment] 2023-08-28 05:16
@msftedad  I'm confused - 2.6.2 should be the version as mentioned above
