### ISSUE TITLE
Hooks dont work

### ISSUE THREAD

**Issue by danthzz** [recharts/recharts#3333] opened 2023-02-06 14:37 UTC
I've refatoring to hook component but dont work how it should 

`.
    

    const initialData = [accelerationRmsGraph, speedRmsGraph];
    const getAxisYDomain = (from, to, ref, offset) => {
        const refData = initialData?.slice(from - 1, to);
        let [bottom, top] = [refData[0][ref], refData[0][ref]];
        refData.forEach((d) => {
            if (d[ref] > top) top = d[ref];
            if (d[ref] < bottom) bottom = d[ref];
        });

        return [(bottom | 0) - offset, (top | 0) + offset];
    };

    const initialState = {
        data: initialData,
        left: 'dataMin',
        right: 'dataMax',
        refAreaLeft: '',
        refAreaRight: '',
        top: 'dataMax+1',
        bottom: 'dataMin-1',
        top2: 'dataMax+20',
        bottom2: 'dataMin-20',
        animation: true,
    };

    const [zoomGraphs, setZoomGraphs] = useState(initialState,{
        left: "dataMin",
        right: "dataMax"
    });

    const zoom = () => {
        let { refAreaLeft, refAreaRight } = zoomGraphs;
        const { data } = zoomGraphs;

        if (refAreaLeft === refAreaRight || refAreaRight === '') {
            setZoomGraphs({
                refAreaLeft: '',
                refAreaRight: '',
            });
            return;
        };

        // xAxis domain
        if (refAreaLeft > refAreaRight) [refAreaLeft, refAreaRight] = [refAreaRight, refAreaLeft];

        // yAxis domain
        const [bottom, top] = getAxisYDomain(refAreaLeft, refAreaRight, 'cost', 1);
        const [bottom2, top2] = getAxisYDomain(refAreaLeft, refAreaRight, 'impression', 50);

        setZoomGraphs({
            refAreaLeft: '',
            refAreaRight: '',
            data: data?.slice(),
            left: refAreaLeft,
            right: refAreaRight,
            bottom,
            top,
            bottom2,
            top2,
        });
    };

    const zoomOut = () => {
        const { data } = zoomGraphs;
        setZoomGraphs({
            data: data?.slice(),
            refAreaLeft: '',
            refAreaRight: '',
            left: 'dataMin',
            right: 'dataMax',
            top: 'dataMax+1',
            bottom: 'dataMin',
            top2: 'dataMax+50',
            bottom2: 'dataMin+50',
        });
    };

    const { left, right, refAreaLeft, refAreaRight, top, bottom, top2, bottom2 } = zoomGraphs;
                    {accelerationRmsGraph && speedRmsGraph
                        ? (
                            <div style={{ width: '100%', flex: '1 1 auto' }}>
                                <ResponsiveContainer mt="2">
                                    <LineChart
                                        data={rmsSelector === "acceleration" ? accelerationRmsGraph : speedRmsGraph}
                                        onMouseDown={(e) => setZoomGraphs((zoomGraphs) => ({ ...zoomGraphs, left: e.activeLabel }))}
                                        onMouseMove={(e) => setZoomGraphs((zoomGraphs) => ({ ...zoomGraphs, right: e.activeLabel }))}
                                        // eslint-disable-next-line react/jsx-no-bind
                                        onMouseUp={zoom.bind()}

                                    >
                                        <CartesianGrid strokeDasharray="3 3" />

                                        <XAxis allowDataOverflow scale="time" domain={[left, right]} type="number" dataKey="name" angle="0" tickFormatter={(tick) => format(tick, 'dd/MM HH:mm')} />

                                        <YAxis allowDataOverflow domain={[bottom, top]} type="number" yAxisId="1" />

                                        <YAxis orientation="right" allowDataOverflow domain={[bottom2, top2]} type="number" yAxisId="2" />

                                        <Tooltip labelFormatter={(label) => format(label, "dd/MM/yy HH:mm:ss")} formatter={(value) => value.toFixed(4)} />
`

stay somenthing like that

**Comment by ckifer** [comment] 2023-02-06 17:06
@danthzz can you please put this into a codesandbox and explain more about what you've tried? It's hard to gather anything from your example without a reproduction.

**Comment by danthzz** [comment] 2023-02-07 11:43
https://codesandbox.io/s/highlight-zomm-line-chart-forked-qc1zkb?file=/src/App.tsx

**Comment by nikolasrieble** [comment] 2023-02-08 13:39
@danthzz Please do add more description. We need to better understand what you want to achieve, and where it fails. I can not deduce that from the code.

**Comment by danthzz** [comment] 2023-02-08 14:20
when i refactored the code to use the hook the graph disappears when zooming in

**Comment by ckifer** [comment] 2023-02-09 01:16
This just looks like incorrect refactoring. There are references to things that are not correct such as using `.bind()`, not having correct typing in your useState, etc. If you fix the errors in the codesandbox you should fix the issue.

**Comment by ckifer** [comment] 2023-02-09 01:27
https://codesandbox.io/s/highlight-zomm-line-chart-forked-holzzh

Please see the above codesandbox.

Closing as answered, this issue has nothing to do with recharts

**Closed by ckifer** 2023-02-09 01:27 UTC
Labels: needs reproduction
