### ISSUE TITLE
Don't show dots after re-render

### ISSUE THREAD

**Issue by vitaliydz** [recharts/recharts#804] opened 2017-07-26 13:21 UTC
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
After re-render a LineChart are dots does not show
## If the current behavior is a bug, please provide the steps to reproduce.
At page 3 charts. They received async data as array(that means, component and charts re-rendered 3 times).
If someone of them (charts) re-rendered with the same data - dots not show
## What is the expected behavior?
Dots must show
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
React - 15.4
recharts - 1.0.0-alpha.2
OS - Ubuntu 14.04
Browser - Chrome 59.0.3071.115 (64x)

**Comment by tmf-chris** [comment] 2017-07-28 14:04
I have this same issue; in shouldComponentUpdate if I rigorously make sure that the chart is not re-rendered with the same data then the dots show, however if the chart is ever re-rendered with the same data then the dots do not appear.

**Comment by ngub** [comment] 2017-09-28 15:27
Actually, the issue is caused by onAnimationEnd callback not being called. It should be handled by the Animate component from `react-smooth` library, so I would look for a bug there. 

As a workaround, you can disable animations for a Line component by setting `isAnimationActive` prop to `false`.

**Comment by essaji** [comment] 2017-12-19 13:11
This seems to be fixed in the latest version. I am using 1.0.0-beta.6

**Comment by christophby** [comment] 2018-04-12 16:14
running in this issue, too

**Comment by JoaoMosmann** [comment] 2018-06-05 18:48
Same here

**Comment by johnanisere** [comment] 2018-06-22 01:02
@ngub any updates? how do we make this work without losing the animation?

**Comment by drudv** [comment] 2018-07-31 10:33
Confirm the issue

**Comment by maalej** [comment] 2018-07-31 14:29
Same issue here

**Comment by zigav** [comment] 2018-09-18 11:13
Same here. Following for updates.

**Comment by prilutskiy** [comment] 2019-01-09 14:54
The same!

**Comment by felixhagspiel** [comment] 2019-01-16 15:41
Same

**Comment by gabrielweich** [comment] 2019-01-26 22:55
Same

**Comment by felipe-vicente** [comment] 2019-02-07 01:04
Hey.

I was dealing with that but just now and think I have found a way to keep dots while having the animation going.

By using react hooks (React.useEffect()) you can prevent graph component from rendering more than once after it gets new values. Here is an example (the actual code I used)

the function component receives the data via props.data

({ data }) => {
const [graphData, setGraphData] = React.useState([])

  React.useEffect(() => {
    // Functions that treats the data and return the array
    setGraphData(dataTransformer(data)) 
  }, [data]) // [data] keeps the chart data changing just once after the diff

  return (...)

}

Hope it works for you guys.

Cheers

**Comment by jake-daniels** [comment] 2022-04-21 06:51
Hi, try the solution here if you want animation active: https://github.com/recharts/recharts/issues/1426#issuecomment-1104786135

**Comment by ckifer** [comment] 2024-09-22 22:32
I'm going to close this as a duplicate because https://github.com/recharts/recharts/issues/1426 has more information

**Closed by ckifer** 2024-09-22 22:32 UTC
Labels: enhancement
