### ISSUE TITLE
I am getting weird xaxis behaviour

### ISSUE THREAD

**Issue by Avhishek05** [recharts/recharts#3459] opened 2023-03-15 17:18 UTC
<img width="391" alt="image" src="https://user-images.githubusercontent.com/23546633/225388715-053b271f-8d86-49d4-be6c-f6681c858c7a.png">

my data looks like this

`[
    {
        "name": ""
    },
    {
        "value": 1362.0180397615786,
        "name": "16-23 Feb"
    },
    {
        "value": 1407.6639293751145,
        "name": "23-2 Feb"
    },
    {
        "value": 1418.1851376647246,
        "name": "2-9 Mar"
    },
    {
        "value": 1221.4480816577939,
        "name": "9-15 Mar"
    },
    {
        "name": ""
    }
]`

it only occurs when I add `{name: ""}` at the start and end to show fix UI

otherwise, it is working properly

<img width="431" alt="image" src="https://user-images.githubusercontent.com/23546633/225389412-df742fa6-3b8f-4379-bfe8-3e21682d013e.png">

**Comment by ckifer** [comment] 2023-03-15 18:13
Hi @Avhishek05

Can you provide a reproduction of your issue?

Looks like you have a different scale set or something. 
https://codesandbox.io/s/simple-bar-chart-forked-tuirpb?file=/src/App.tsx

In that example I think I'm accomplishing what you want?

**Comment by ckifer** [comment] 2023-03-16 22:45
Going to close this. Will open it back up if we get a response

**Comment by Avhishek05** [comment] 2023-03-17 13:20
It is happening on version 1.8.5

below is the codesandbox link to reproduce
https://h3vciv.csb.app/

**Comment by ckifer** [comment] 2023-03-17 22:31
Does your scale need to be `point`? On 1.8 or on 2.5 that is what is messing up your graph. Remove that and all is good - `point` isn't a scale that you'd want to use with a bar chart.

Closing this, thanks!

**Closed by ckifer** 2023-03-17 22:31 UTC
