### ISSUE TITLE
Invalid value for prop `type` on <path> tag

### ISSUE THREAD

**Issue by minhTheGreat** [recharts/recharts#3310] opened 2023-02-02 11:11 UTC
I got an issue when I set the type of lineChart is stepAround, it shows a warning
![Screenshot_2](https://user-images.githubusercontent.com/45730043/216309068-440a9b30-566a-45ad-a193-b0ed81b9edc0.png)
How can i fix it ?

**Comment by ckifer** [comment] 2023-02-02 16:18
@minhTheGreat can you create a codesandbox reproducing the issue?

**Comment by ckifer** [comment] 2023-02-02 16:37
`stepAround` is not a valid option for `type`.

See https://github.com/recharts/recharts/blob/1216e06412fd896da484bc0a84ca85d2b415fbd9/src/shape/Curve.tsx#L45-L58

**Comment by ckifer** [comment] 2023-02-02 22:54
Going to close this as resolved, please comment back if there is something I'm missing

**Comment by minhTheGreat** [comment] 2023-02-03 02:52
oh this is custom curve that implements step curve interpolators d3JS

**Comment by ckifer** [comment] 2023-02-03 04:54
Well type definitely isn't valid on path https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path

It probably isn't getting filtered out correctly somewhere. I'll check this tomorrow. Thanks!

**Comment by ckifer** [comment] 2023-02-03 18:39
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/type

Yeah.. basically because props are just blindly spread onto the element and `type` happens to be a valid SVG property it doesn't get filtered out like it should. This is fine when the type is a string or a number cause the DOM ignores it - not fine when its a function. 

None of the actual elements `type` is valid for are used in the project. Going to add a check for a function and remove that prop from allowed attributes

**Comment by ckifer** [comment] 2023-02-03 21:03
@minhTheGreat   #3327

**Comment by ckifer** [comment] 2023-02-06 22:30
Merged in #3327 

Resolving this, will be released in next minor version

**Closed by ckifer** 2023-02-06 22:30 UTC
Labels: bug

**Comment by ckifer** [comment] 2023-02-09 17:13
Should be fixed in 2.4.0
