### ISSUE TITLE
Can't install recharts with REACT 18.0.0

### ISSUE THREAD

**Issue by sarath-gvnd** [recharts/recharts#2818] opened 2022-04-06 15:55 UTC
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^17.0.0" from recharts@2.1.9
npm ERR! node_modules/recharts
npm ERR!   recharts@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by doberkofler** [comment] 2022-04-08 09:42
Duplicate of #2813

**Comment by Nathan-Lynx** [comment] 2022-06-20 11:06
Same issue for new project, trying to npm I rechart on react 18 project

**Comment by ckifer** [comment] 2022-12-30 07:07
Closing at the other issue is resolved and recharts works with React 18

**Closed by ckifer** 2022-12-30 07:07 UTC
