### ISSUE TITLE
Time series example

### ISSUE THREAD

**Issue by Hyllesen** [recharts/recharts#956] opened 2017-10-19 05:59 UTC
I think it would be nice with an example of a chart using a _time series_ on the XAxis. I am trying to use time myself but I can't figure out from documentation how my time data should be formatted. Currently it is JavaScript Date objects.

**Comment by Hyllesen** [comment] 2017-10-20 06:27
My "solution" so far has been to simply make the time data as strings in dd/mm format. But it's a shame this hasn't been documented better as I enjoyed how well recharts worked out of the box in the layout compared to victory charts.

**Comment by ZephD** [comment] 2017-10-25 18:02
Oh, the `type="number"` is important, because the default (for x axis) is category.

**Comment by Hyllesen** [comment] 2017-10-28 19:19
@dsandmark would be nice if they could put this example in the docs!

**Comment by perymimon** [comment] 2019-05-03 16:53
maybe that can help more : 
https://github.com/recharts/recharts/issues/1137

**Comment by anikolaev** [comment] 2019-06-05 11:34
Does Recharts have any functionality to modify tick labels depending on available space as some other libraries do? Like showing either days or weeks or names of months only? It is one of the most complicated tasks to implement for time axes.

**Comment by ricardo-scandata** [comment] 2019-12-13 15:56
@anikolaev - momentjs has all of that functionality you're looking for checkout their docs they're simple and to the point https://momentjs.com/docs/#/parsing/creation-data/ 
@dsandmark thank you for the example provided! It was most helpful

**Comment by anikolaev** [comment] 2019-12-13 16:16
@ricardo-scandata momentjs has nothing to do with layout and available space. It simply generates text strings. I mean the process when depending on the available space different number of ticks is displayed with different labels (short/long month names etc). Anyway we have chosen Highcharts for our tasks.

**Comment by ricardo-scandata** [comment] 2019-12-13 16:23
@anikolaev - right the link posted is to moments data creation.  You can use breakpoints or use anytype of measurements to invoke a label from going from full date to MM/DD only, once your component reaches a width or height.

**Comment by Nawal00** [comment] 2020-04-09 14:09
how can you have the time scale to be last 24 hours from the current time? The docs don't have any example and it would be nice.

**Comment by go-mad** [comment] 2020-04-21 18:17
@anikolaev Did you find any solution?

**Comment by gaurav5430** [comment] 2020-05-28 17:52
It would be great to have some default handling for time-series data as some other libraries (like react-viz) have out of the box.

In my case, I am fine with using a tickFormatter, but I would still like recharts to have the ability to intelligently decide how many ticks should be shown based on the data. for e.g, if the data is spanned across multiple years, then show a tick for each year, but in recharts, sometimes I end up with missing ticks for years, and sometimes with multiple ticks for a year. 

Would be even better if internally recharts could handle something like what @anikolaev suggested

**Comment by EddyVinck** [comment] 2020-09-10 14:03
Thanks @dsandmark!

So to summarize: make sure the value on the XAxis is a unix timestamp and then add the following to the `XAxis` component

```jsx
<LineChart data={data}>
  <XAxis
    // Makes the chart a time series chart
    tickFormatter={unixTime => format(fromUnixTime(unixTime), 'MMM')}
    type="number"
    domain={['auto', 'auto']}
  />
</LineChart>
```

After reading the docs I'm still not entirely sure what `['auto', 'auto']` does, but I believe it positions the ticks evenly like a time series chart would. It even added a tick outside of my data range with the correct date. I even briefly checked the source code but it wasn't very clear to me since there's a lot going on.

**Comment by ZephD** [comment] 2020-09-10 14:12
['auto', 'auto'] means set the lower/upper limits (the "domain") of the axis automatically. Does not have much impact to ticks (afaik).

**Comment by athenawisdoms** [comment] 2021-01-27 05:55
Tried using `tickFormatter` and moment, but the `XAxis` and `LineChart` disappears!

**Originally:**

![image](https://user-images.githubusercontent.com/6615285/105949019-0436c500-603a-11eb-8ec6-d9df27ba3a14.png)

```
    const d = [
        {date: '2017-02-01', price: 231},
        {date: '2017-04-01', price: 453},
        {date: '2017-16-01', price: 123},
        {date: '2018-01-01', price: 234},
        {date: '2018-04-01', price: 958},
        {date: '2018-11-01', price: 163},
        {date: '2018-11-02', price: 163},
        {date: '2018-11-03', price: 163},
        {date: '2018-11-04', price: 163},
        {date: '2019-03-01', price: 293},
        {date: '2019-10-01', price: 471},
        {date: '2020-07-01', price: 881},
        {date: '2020-09-01', price: 122},
    ]

    return (
        <ResponsiveContainer width="100%" height={400}>
            <LineChart data={d}>
                <Line type="monotone" dataKey="price" stroke="#8884d8" />
                <CartesianGrid stroke="#ccc" strokeDasharray="5 5" />
                <XAxis dataKey="date" />
                <YAxis dataKey="price" />
                <Tooltip />
            </LineChart>
        </ResponsiveContainer>
    )
```

**With tickFormatter:**

![image](https://user-images.githubusercontent.com/6615285/105949109-2b8d9200-603a-11eb-9085-95656889f04b.png)

```
    return (
        <ResponsiveContainer width="100%" height={400}>
            <LineChart data={d}>
                <Line type="monotone" dataKey="price" stroke="#8884d8" />
                <CartesianGrid stroke="#ccc" strokeDasharray="5 5" />
                <XAxis 
                    dataKey="date" 
                    tickFormatter = {(date) => moment(date).format('YY')}
                    type='number'
                    domain={['auto', 'auto']}
                />
                <YAxis dataKey="price" />
                <Tooltip />
            </LineChart>
        </ResponsiveContainer>
    )
```

**Comment by ZephD** [comment] 2021-01-27 10:03
Untested, but your input date is a string, but it's excepted a number axis type.
Try inputting your data as a epoch number, and formatting as a string.

**Comment by athenawisdoms** [comment] 2021-01-28 01:36
@ZephD Great catch! I fixed that, but another problem appears!

The X axis labels are being repeated if we run the following code. Is there a fix for this? Thank you!

![image](https://user-images.githubusercontent.com/6615285/106077291-48c86c00-60df-11eb-82b5-306ac6a2a233.png)


```js
    data = [
        {date: '2000-01-01', price: 958, timestamp: 946702800000},
        {date: '2000-02-01', price: 163, timestamp: 949381200000},
        {date: '2000-03-01', price: 163, timestamp: 951886800000},
        {date: '2000-04-02', price: 163, timestamp: 954565200000},
        {date: '2000-05-03', price: 163, timestamp: 957153600000},
        {date: '2000-06-04', price: 163, timestamp: 959832000000},
        {date: '2000-07-01', price: 293, timestamp: 962424000000},
    ];

    return (
        <ResponsiveContainer width="100%" height={400}>
            <LineChart data={data}>
                <Line type="monotone" dataKey="price" stroke="#8884d8" />
                <CartesianGrid stroke="#ccc" strokeDasharray="5 5" />
                <XAxis 
                    dataKey="timestamp" 
                    tickFormatter = {(timestamp) => moment(timestamp).format('YY')}
                    type='number'
                    domain={['auto', 'auto']}
                />
                <YAxis dataKey="price" />
                <Tooltip />
            </LineChart>
        </ResponsiveContainer>
    )
```

**Comment by ZephD** [comment] 2021-01-28 09:39
I think you can set the ticks manually if you want, too.
`ticks={(timestamp) => Array.from(new Set(moment(timestamp).format('YY')))}`

**Comment by bertrand-caron** [comment] 2022-01-04 22:14
Has anyone managed to get this to work nicely with the `<Tooltip/>` component?
There is an option fore reformatting the Y value, but not the X one.
This means the tooltip can only display an EPOCH (in ms), which is not very user-friendly :(
<img width="167" alt="Screen Shot 2022-01-05 at 8 13 01 am" src="https://user-images.githubusercontent.com/4724439/148131063-133b3f89-1728-4248-989d-e7c1d778ec1e.png">

**Comment by Fresh-Cut-Grass** [comment] 2022-01-06 10:19
@bertrand-caron 
In case you are still searching: You have access to the x value under the props `label`. Then, you just need to format it (using `new Date(label)`, or a lib.
You have a whole bunch of other props too.

```js
const CustomTooltip = ({
  active,
  payload,
  label,
  coordinate,
  ...props
}) => {
  console.info({ active, coordinate, payload, label, props });
  if (active && payload && payload.length) {
    return (
      <div className={styles.CustomTooltip}>
        <p className={styles.CustomTooltip_Label}>
          <Moment format="DD/MM/YYYY">{new Date(label)}</Moment>
        </p>
        // ...
```

**Comment by lucianthorr** [comment] 2022-03-01 18:51
I got really stuck on this, being pretty new to recharts and moment.js especially because types matter and things will silently just give nonsense results if everything isn't just right.  I'm going to post what worked for me below in case it helps future me's.
```
// Given some input data
var data = [
                { date: "20210101", category: "a", value: 1000 },
                { date: "20210102", category: "a", value: 2000 },
                { date: "20210103", category: "a", value: 3000 },
                { date: "20210101", category: "b", value: 500 },
                { date: "20210102", category: "b", value: 2000 },
                { date: "20210103", category: "b", value: 1000 },
            ]
// create a numeric column to be used for the x-axis.  Use .valueOf() to get the correct unix timestamp
// There's a .unix() function but it gives the wrong results and will leave you without hair
data.forEach((row) => {
    data["ts"] = moment(ts, "YYYYMMDD").valueOf();
});
...
<XAxis
dataKey="ts" 
type="number" // as opposed to category, assures you that the tickFormatter callback receives a numeric argument
tickFormatter={(unixTimestamp) => moment(unixTimestamp).format("YYYY-MM-DD")}
domain={['auto', 'auto']}
scale="time"
>
...
</XAxis>
```

**Comment by its-kayes** [comment] 2022-09-03 07:47
`<XAxis dataKey="time" tickFormatter={timeStr => moment(timeStr).format('HH:mm')} />`

I do use that, and it's works for me. Thanks a lot

**Comment by nikolasrieble** [comment] 2023-02-13 13:56
The solution that we use is to work with d3 timeScale. I added a story to storybook to show the usage. It might be nice to write further stories and other solutions.

**Comment by ckifer** [comment] 2023-02-13 18:26
Please see examples in [this PR](https://github.com/recharts/recharts/commit/8cbd50a9700443002b910bf4b2bdc8a6da9d9fd0) that correspond with the charts [here in the storybook](https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-timeseries--with-d-3-scale)

**Comment by nikolasrieble** [comment] 2023-02-21 14:16
@Hyllesen Does the story that I have added help you? Do you have any further questions?
Unless more needs to be done, I will close the issue.

**Comment by nicholasgcoles** [comment] 2023-03-16 09:30
@nikolasrieble thank you for the storybook. It saved me a lot of time 👍 

I found that sometimes the tick values were sitting outside of the actual x-axis:
![image](https://user-images.githubusercontent.com/1975028/225573506-809fbb0c-5e71-4f5e-b571-cfeab6c55b6b.png)

To combat this I did the following:
```
export const getXAxisArgsForTimeBasedGraph = (dateStrings: string[]) => {
  // The d3 scaleTime domain requires numeric values
  const numericValues = dateStrings.map((dateString) =>
    convertDateStringToTimeValue(dateString)
  );
  const maxValue = Math.max(...numericValues)
  const minValue = Math.min(...numericValues)
  // With .nice() we extend the domain nicely.
  const timeScale = scaleTime()
    .domain([minValue, maxValue])
    .nice();

  const ticks = timeScale.ticks(5);
  // Make sure not to use ticks which fall outside of the data range
  if (ticks[0].valueOf() < minValue) {
    ticks.splice(0, 1);
  }
  if (ticks[ticks.length - 1].valueOf() > maxValue) {
    ticks.splice(ticks.length - 1, 1);
  }

  return {
    domain: timeScale.domain().map((date) => date),
    scale: timeScale,
    xAxisType: 'number' as const,
    ticks: ticks,
    tickFormatter: multiFormat
  };
};
```

**Comment by nicholasgcoles** [comment] 2023-03-17 12:35
@nikolasrieble I am actually struggling a little bit.

I can't get the tooltip line to hover over the points:
![image](https://user-images.githubusercontent.com/1975028/225905214-073da571-5018-4bab-a05a-cc79f0920484.png)

In addition to this, the line goes over the domain (makes hovering over the point nearly impossible). Also can't figure out how to adjust this.
![image](https://user-images.githubusercontent.com/1975028/225905379-46cf66eb-586e-4af9-917a-05b1451c8e48.png)

I am using the following data:
```
[
  {
    "x": "2022-12-22T00:00:00.000Z",
    "y": 19.4
  },
  {
    "x": "2023-01-02T00:00:00.000Z",
    "y": 28.1
  },
  {
    "x": "2023-01-10T00:00:00.000Z",
    "y": 27.3
  },
  {
    "x": "2023-01-11T00:00:00.000Z",
    "y": 24.9
  },
  {
    "x": "2023-01-16T00:00:00.000Z",
    "y": 30.5
  },
  {
    "x": "2023-01-18T00:00:00.000Z",
    "y": 27.8
  },
  {
    "x": "2023-01-23T00:00:00.000Z",
    "y": 28
  },
  {
    "x": "2023-01-24T00:00:00.000Z",
    "y": 31.9
  },
  {
    "x": "2023-01-25T00:00:00.000Z",
    "y": 30.6
  },
  {
    "x": "2023-01-30T00:00:00.000Z",
    "y": 33.5
  },
  {
    "x": "2023-01-31T00:00:00.000Z",
    "y": 29.3
  },
  {
    "x": "2023-02-03T00:00:00.000Z",
    "y": 32.2
  },
  {
    "x": "2023-02-06T00:00:00.000Z",
    "y": 33.2
  },
  {
    "x": "2023-02-07T00:00:00.000Z",
    "y": 31.6
  },
  {
    "x": "2023-02-08T00:00:00.000Z",
    "y": 33.2
  },
  {
    "x": "2023-02-09T00:00:00.000Z",
    "y": 36.6
  },
  {
    "x": "2023-02-13T00:00:00.000Z",
    "y": 37.3
  },
  {
    "x": "2023-02-17T00:00:00.000Z",
    "y": 33.8
  },
  {
    "x": "2023-02-21T00:00:00.000Z",
    "y": 38.3
  },
  {
    "x": "2023-02-24T00:00:00.000Z",
    "y": 37.3
  },
  {
    "x": "2023-02-27T00:00:00.000Z",
    "y": 40.9
  },
  {
    "x": "2023-03-06T00:00:00.000Z",
    "y": 45
  },
  {
    "x": "2023-03-10T00:00:00.000Z",
    "y": 40
  },
  {
    "x": "2023-03-13T00:00:00.000Z",
    "y": 45.6
  },
  {
    "x": "2023-03-16T00:00:00.000Z",
    "y": 44.5
  }
]
```

I tried loading it into the Storybook, but the actual values didn't seem to update, only the x-axis:
![image](https://user-images.githubusercontent.com/1975028/225905658-0905e749-7f4d-4b2d-9828-e5ffcdab9e7b.png)

I've tried the following:
- Removing first & last tick values (mentioned in comment above)
- Adjusting the domain (`timeScale.domain()`)
- Using count within `nice()`
- Changing tick count

**Comment by nikolasrieble** [comment] 2023-03-18 21:02
@nicholasgcoles It would be great if you could provide a code sandbox where I can reproduce the above. Then I can look into possible fixes.

**Comment by nicholasgcoles** [comment] 2023-03-20 07:18
@nikolasrieble here we go:
https://codesandbox.io/s/loving-haze-20hmg6

**Comment by nikolasrieble** [comment] 2023-03-20 19:15
It seems that your issues are caused by the back and forth of converting timestamps. I could not pin the exact issue down, but got it work correctly here 

https://codesandbox.io/s/nostalgic-cookies-1vpx2i?file=/src/App.tsx

Mostly by removing parsing, and moving it all into a single place. 
I generally recommend to pass only unix timestamps, and then simplyfiy as such: 

```
export const getXAxisArgsForTimeBasedGraph = (numericValues: number[]) => {
  const maxValue = Math.max(...numericValues);
  const minValue = Math.min(...numericValues);
  const timeScale = scaleTime().domain([minValue, maxValue]).nice(5);

  return {
    scale: timeScale,
    type: "number",
    domain: timeScale.domain(),
    tickFormatter: monthFormat,
    ticks: timeScale.ticks(5)
  };
};
```

**Comment by nicholasgcoles** [comment] 2023-03-21 08:11
@nikolasrieble thanks so much for looking into it! Can confirm it is working as expected now 👍

I think I have pinpointed the issue:

In the [storybook example ](https://github.com/recharts/recharts/blob/master/storybook/stories/Examples/TimeSeries.stories.tsx#L97) `xAxisType` is referenced, which I don't think is actually a valid property. Changing it to `type`, as you have above, fixes the issue.

**Comment by nicholasgcoles** [comment] 2023-03-21 09:04
@nikolasrieble happy to, sent through PR 👍

**Comment by ckifer** [comment] 2023-06-01 22:07
closing as completed

**Closed by ckifer** 2023-06-01 22:07 UTC
