### ISSUE TITLE
On safari, Line chart X-axis is rendered in reverse order

### ISSUE THREAD

**Issue by elijahnikov** [recharts/recharts#5091] opened 2024-10-07 12:53 UTC
## Do you want to request a feature or report a bug?

Report a bug

## What is the current behavior?

`.sort((a, b) => {
        return new Date(a.date).getTime() - new Date(b.date).getTime()
      })`

I have a date timeline in a line chart which goes from oldest -> newest. On safari, Recharts Line chart is rendering the x-axis in reverse order. On chrome its working as intended

Chrome:
<img width="288" alt="image" src="https://github.com/user-attachments/assets/28be0fd1-17a8-417a-980f-401b7bb8166c">

Safari:
<img width="279" alt="image" src="https://github.com/user-attachments/assets/4f6df7d5-da90-4bb3-9ed3-768a57523513">

## What is the expected behavior?

X-axis should be rendered in order that the object is supplied in.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

recharts: 2.9.1
safari: 18

**Comment by ckifer** [comment] 2024-10-07 14:08
This seems like a bug in Safari? I'm not sure what recharts can do here

**Comment by elijahnikov** [comment] 2024-10-07 14:16
> This seems like a bug in Safari? I'm not sure what recharts can do here

Because its recharts specific? Sorry, should I not be submitting bugs that happen when I use recharts?

**Comment by ckifer** [comment] 2024-10-07 14:49
are you able to make a reproduction in codesandbox?

**Comment by ckifer** [comment] 2024-10-07 15:06
Firefox:
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/ff993a38-35d1-4a57-b922-3c51a23f604b">

Safari:
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/26842a0e-ec2b-4785-a975-c3c28a71c89d">

**Comment by elijahnikov** [comment] 2024-10-07 15:16
No worries, thats understandable! 

Unfortunately Im also unable to recreate in codesandbox, all that I can provide is that im sorting the data before supplying it to the line chart i.e.
`.sort((a, b) => {
        return new Date(a.date).getTime() - new Date(b.date).getTime()
      })`

On my end its happening on local and preview/prod. 

Ive done a bit of reading and it may come down to how sort is done on safari. I think your original point thats its safari specific is more than likely correct

**Comment by ckifer** [comment] 2024-10-07 15:22
Hmm, ok. If there's anything more that you can give me I'll be happy to take it and try to reproduce. Are you able to post any of your code? Or a simplified version of it?

**Comment by ckifer** [comment] 2024-10-08 17:23
I'm going to close this for now since we can't reproduce. Feel free to comment back on this and I'll re-open it if needed

**Closed by ckifer** 2024-10-08 17:23 UTC
Labels: needs reproduction
